### ISSUE TITLE
1D vector multiplication does not work with Knet

### ISSUE THREAD

**Issue by kirnap** [denizyuret/Knet.jl#10]
`using Knet`
`a=[1;2;3]`
`a*a'`
`ERROR: MethodError: `gemm!` has no method matching gemm!(::Char, ::Char, ::Int64, ::Array{Int64,2}, ::Array{Int64,2}, ::Int64, ::Array{Int64,2})
 in * at linalg/matmul.jl:88
 in A_mul_Bc at operators.jl:164`

Without using Knet it works

**Comment by denizyuret** [comment]
I am closing this issue as resolved by Knet8.  Please reopen if you have further problems.
