### ISSUE TITLE
UndefVarError: UngetIndex not defined

### ISSUE THREAD

**Issue by ppalmes** [denizyuret/Knet.jl#103]
Knet update should also trigger updates in AutoGrad. There are cases when AutoGrad is not updated and causes error even though Knet is updated. I think it will good for Knet to check if AutoGrad version is the correct one and automatically update AutoGrad if the version is old.

**Comment by denizyuret** [comment]
Do you know how to do this for untagged commits?  Normally when I tag a version (Knet 0.8.2, AutoGrad 0.0.6 etc.) with the appropriate REQUIRE file, Julia does this automatically.  However if you are using the master version of Knet, I do not know an automated method to also get the master versions of the requirements like AutoGrad.

**Comment by ppalmes** [comment]
maybe programmatically check the Autograd/Knet versions or .ji dates and call Pkg.build if out of sync?

**Comment by denizyuret** [comment]
Knet 0.8.3 was released. The problem should be resolved now.
