### ISSUE TITLE
Element-wise power of KnetArray give NaN results

### ISSUE THREAD

**Issue by ognkrmms** [denizyuret/Knet.jl#108]
Element-wise powers of KnetArrays produce NaN for most of the entries but it sometimes calculates some of the entries correct.

**Comment by kirnap** [comment]
I've also encountered the same problem and here is how to replicate the error in the simplest manner:
`x = KnetArray{Float32}(randn(4,1))
 julia> x.*x
4×1 Knet.KnetArray{Float32,2}:
 1.13435
 0.0826074
 0.018514
 0.00399359

julia> x.^2
4×1 Knet.KnetArray{Float32,2}:
   1.13435
 NaN
   0.018514
   0.00399359
`

**Comment by denizyuret** [comment]
There seems to be a problem with powers of Float32 negative numbers.  There
is no issue with Float64 or positive numbers.  Is this also your experience?

**Comment by ilkerkesen** [comment]
I am able to repeat it with Float64 arrays also.

[https://gist.github.com/ilkerkesen/6a6859781402fe4a38b8a0923ba64f64](https://gist.github.com/ilkerkesen/6a6859781402fe4a38b8a0923ba64f64)

**Comment by denizyuret** [comment]
I don't get this on the aitest machine.  Is it an NVIDIA library version problem?  I have:
```
julia> include(Knet.dir("test/gpu.jl"))
(8000,8000,8000,5105)
```

Or maybe chip problem:
```
$ nvidia-smi
NVIDIA-SMI 375.39                 Driver Version: 375.39
Tesla K80
```

**Comment by ognkrmms** [comment]
I have no problem with Float64 or positive numbers on my laptop. I have
```
julia> include(Knet.dir("test/gpu.jl"))
(8000,8000,8000,5110)
```
and
```
$ nvidia-smi
NVIDIA-SMI 375.39                 Driver Version: 375.39
Geforce GT 650M
```

**Comment by denizyuret** [comment]
Fractional powers of negative numbers are not always defined (e.g. -1^0.5 =
i ) in real domain, the answers are complex.  So I am guessing that some of
the NVIDIA libraries just return NaN without checking if there is a real
valued answer for negative inputs.  We'll investigate which versions have
this problem.  But in the meantime it is safest not to use the power
operator with negative inputs.

**Comment by CarloLucibello** [comment]
this could be a solution
```julia
julia> k=KnetArray(rand(Float32,2,2))
2×2 Knet.KnetArray{Float32,2}:
 0.233875  0.487424
 0.415117  0.560328

julia> k=KnetArray(randn(Float32,2,2))
2×2 Knet.KnetArray{Float32,2}:
 1.74326  -2.52771
 2.1774    0.47341

julia> k.^2
2×2 Knet.KnetArray{Float32,2}:
 3.03896  NaN32       
 4.74106      0.224117

julia> Base.power_by_squaring.(k,2)
2×2 Knet.KnetArray{Float32,2}:
 3.03896  6.3893  
 4.74106  0.224117
```
I have to figure out how to redirect broadcast though. Can we reopen the issue?

**Comment by denglerchr** [comment]
Still have this issue in Knet 1.2.1. abs2.(M) works though, but .^( M , 2) is still bugged for me. I think using power on a KnetArray{Float32} should atleast produce a warning for the meantime.

**Comment by ekinakyurek** [comment]
@denizyuret this issue still exists in 1.2.6

**Comment by denizyuret** [comment]
This is a cudnn problem. They cannot handle powers of negative numbers. Do you want a solution only for positive integer powers? If so, we can use @CarloLucibello's `power_by_squaring` solution by (1) writing a cuda kernel for its broadcast application, or (2) see if it works out of the box for CuArrays and use that (like we did for permutedims).

**Comment by ekinakyurek** [comment]
I believe it works for CuArrays since this is used in gelu layer in Flux.

**Comment by denizyuret** [comment]
@maleadt there is a cuda math bug where pow(x,i) works correctly for double values but incorrectly for negative float32 values (gives Nan even when i is an integer). Does CuArrays also call the CUDA pow function or do you have power by squaring or something?

**Comment by denizyuret** [comment]
#498 fixes this using CuArrays, please test.

**Comment by CarloLucibello** [comment]
Knet v1.2.7 fixes the problem for me, I guess we can close this
