### ISSUE TITLE
Mean of a KnetArray

### ISSUE THREAD

**Issue by ardarslan** [denizyuret/Knet.jl#110]
Hello,

I typed following lines to console:

function method(w)
   result = mean(w)
   return result
end

a = convert(KnetArray{Float32}, randn(100,1))
g = grad(method)

When I typed method(a), I got no error. However when I typed g(a), I got the following error:

ERROR: MethodError: no method matching start(::Knet.KnetArray{Float32,2})
Closest candidates are:
  start(::SimpleVector) at essentials.jl:170
  start(::Base.MethodList) at reflection.jl:258
  start(::IntSet) at intset.jl:184
  ...
 in mean(::Base.#identity, ::AutoGrad.Rec{Knet.KnetArray{Float32,2}}) at ./statistics.jl:11
 in method(::AutoGrad.Rec{Knet.KnetArray{Float32,2}}) at ./REPL[12]:2
 in forward_pass(::Function, ::Tuple{Knet.KnetArray{Float32,2}}, ::Array{Any,1}, ::Int64) at /home/ec2-user/.julia/v0.5/AutoGrad/src/core.jl:88
 in (::AutoGrad.##gradfun#1#3{#method,Int64})(::Array{Any,1}, ::Function, ::Knet.KnetArray{Float32,2}, ::Vararg{Knet.KnetArray{Float32,2},N}) at /home/ec2-user/.julia/v0.5/AutoGrad/src/core.jl:39
 in (::AutoGrad.#gradfun#2)(::Knet.KnetArray{Float32,2}, ::Vararg{Knet.KnetArray{Float32,2},N}) at /home/ec2-user/.julia/v0.5/AutoGrad/src/core.jl:39

Best,

Arda Arslan

**Comment by denizyuret** [comment]
Added `mean(w)` and `mean(w,region)` in the latest master.  Leaving this issue open to also implement other missing functions from base/statistics.jl such as `var` and `std`.

**Comment by denizyuret** [comment]
@CarloLucibello's PR fixes this in AutoGrad only, we still do not have var/std etc. for KnetArrays. Reopening this issue. We need a full implementation of functions exported by Statistics. I tried CuArrays but it is currently slower than round trip to CPU. We should be able to do better with vectorized implementations using sum and broadcasting (must be careful about the correction argument).

**Comment by denizyuret** [comment]
This has been implemented in https://github.com/denizyuret/Knet.jl/commit/a1d6154c8233c00899120af93485b2dfbcfde947
