### ISSUE TITLE
vararg functions and AutoGrad

### ISSUE THREAD

**Issue by denizyuret** [denizyuret/Knet.jl#112]
Functions like cat, vcat, hcat, + etc. can have an arbitrary number of args, e.g. vcat(a...) is defined in Base. AutoGrad needs to record them whenever one or more args is boxed in Rec. This is not possible to specify in the type signature. Two possible solutions: 

1. Overwriting Base.vcat(a...) is risky. 
2. We can define an alternative, e.g. vcatn(a...)

vcatn(a...) goes through its args and calls recorder(vcat) (but see below) if any of them is a Rec. This is against the philosophy of using pure Julia to define Knet models, the users will not be aware and use vcat() anyway. Also, it won't be pretty when we try to apply it to +. 

We could give a warning if vcat is used in grad(f). One way to do this is to catch vcat(::Grad{N},x...) and issue an error. Then we cannot use recorder(vcat) above, that requires defining legitimate vcat(::Grad{N},x...). If we are going to define vcatn as a primitive, then we need to call recorder(vcatn) and grad(f) calls vcatn(::Grad{N},x...).

Needs more thought...

**Comment by rdeits** [comment]
It might actually be possible to specify a type signature for `vcat(args...)` where at least one of the args is of a particular type. See: https://github.com/JuliaArrays/StaticArrays.jl/pull/136#discussion_r109543567
