### ISSUE TITLE
Momentum not working

### ISSUE THREAD

**Issue by undefdev** [denizyuret/Knet.jl#114]
I'm trying to modify the lenet.jl example with momentum, but I get the following error:
>ERROR: LoadError: MethodError: no method matching Knet.Momentum(; lr=0.02, gclip=0, gamma=0.9)
Closest candidates are:
  Knet.Momentum(; lr, gamma) at /home/undef/.julia/v0.5/Knet/src/update.jl:66 got unsupported keyword argument "gclip"
  Knet.Momentum(!Matched::AbstractFloat, !Matched::AbstractFloat, !Matched::Any) at /home/undef/.julia/v0.5/Knet/src/update.jl:61 got unsupported keyword arguments "lr", "gclip", "gamma"
  Knet.Momentum(!Matched::Any, !Matched::Any, !Matched::Any) at /home/undef/.julia/v0.5/Knet/src/update.jl:61 got unsupported keyword arguments "lr", "gclip", "gamma"
  ...
 in (::Core.#kw#Type)(::Array{Any,1}, ::Type{Knet.Momentum}) at ./<missing>:0
while loading /home/undef/julia/mnist/lenet.jl, in expression starting on line 24

When leaving out gclip [`Momentum(lr=0.02, gamma=0.9`)] I get the following error instead:
>ERROR: LoadError: MethodError: no method matching length(::Knet.Momentum)
Closest candidates are:
  length(!Matched::SimpleVector) at essentials.jl:168
  length(!Matched::Base.MethodList) at reflection.jl:256
  length(!Matched::MethodTable) at reflection.jl:322
  ...
 in update!(::Array{Any,1}, ::Array{Any,1}, ::Knet.Momentum) at /home/undef/.julia/v0.5/Knet/src/update.jl:339
 in #train#1(::Float64, ::Int64, ::Int64, ::Function, ::Array{Any,1}, ::Array{Any,1}) at /home/undef/julia/mnist/lenet.jl:29
 in (::#kw##train)(::Array{Any,1}, ::#train, ::Array{Any,1}, ::Array{Any,1}) at ./<missing>:0
 in macro expansion at /home/undef/julia/mnist/lenet.jl:112 [inlined]
 in macro expansion at ./util.jl:188 [inlined]
 in main(::Array{String,1}) at /home/undef/julia/mnist/lenet.jl:111
while loading /home/undef/julia/mnist/lenet.jl, in expression starting on line 128

Tried to use Knet master instead, but then I'm getting this error:
>WARNING: could not import AutoGrad.UngetIndex into Knet
ERROR: LoadError: LoadError: UndefVarError: UngetIndex not defined
 in macro expansion; at ./none:2 [inlined]
 in anonymous at ./<missing>:?
while loading /home/undef/.julia/v0.5/Knet/src/karray.jl, in expression starting on line 995
while loading /home/undef/.julia/v0.5/Knet/src/Knet.jl, in expression starting on line 16
ERROR: LoadError: Failed to precompile Knet to /home/undef/.julia/lib/v0.5/Knet.ji.
while loading /home/undef/julia/mnist/lenet.jl, in expression starting on line 1

**Comment by denizyuret** [comment]
1. In the original bug, what were the versions of AutoGrad and Knet?
2. In the Knet master experiment, you also need to pull the AutoGrad master.

**Comment by undefdev** [comment]
1.
 - AutoGrad                  0.0.6
 - Knet                          0.8.2

2. Ah yes, I should have thought of that - however, getting the second error again with Knet and AutoGrad on master:
>ERROR: LoadError: MethodError: no method matching length(::Knet.Momentum)
Closest candidates are:
  length(!Matched::SimpleVector) at essentials.jl:168
  length(!Matched::Base.MethodList) at reflection.jl:256
  length(!Matched::MethodTable) at reflection.jl:322
  ...

**Comment by denizyuret** [comment]
Can you share your modified lenet.jl for debugging?  There may be some
usage error with Momentum. See charlm, rnnlm, optimizers under
Knet/examples for usage examples.

**Comment by undefdev** [comment]
Certainly!
```
using Knet,ArgParse,Main
!isdefined(Main,:MNIST) && include(Knet.dir("examples","mnist.jl"))
using MNIST: minibatch, accuracy


function predict(w,x,n=length(w)-4)
    for i=1:2:n
        x = pool(relu(conv4(w[i],x;padding=0) .+ w[i+1]))
    end
    x = mat(x)
    for i=n+1:2:length(w)-2
        x = relu(w[i]*x .+ w[i+1])
    end
    return w[end-1]*x .+ w[end]
end

function loss(w,x,ygold)
    ypred = predict(w,x)
    ynorm = logp(ypred,1)  # ypred .- log(sum(exp(ypred),1))
    -sum(ygold .* ynorm) / size(ygold,2)
end

lossgradient = grad(loss)
momentum = Momentum(lr=0.02, gclip=0, gamma=0.9)
function train(w, data; lr=.1, epochs=3, iters=1800)
    for epoch=1:epochs
        for (x,y) in data
            g = lossgradient(w, x, y)
            update!(w, g, momentum)
            #update!(w, g, lr=lr)
            if (iters -= 1) <= 0
                return w
            end
        end
    end
    return w
end

function weights(;atype=KnetArray{Float32})
    w = Array(Any,8)
    w[1] = xavier(5,5,1,20)
    w[2] = zeros(1,1,20,1)
    w[3] = xavier(5,5,20,50)
    w[4] = zeros(1,1,50,1)
    w[5] = xavier(500,800)
    w[6] = zeros(500,1)
    w[7] = xavier(10,500)
    w[8] = zeros(10,1)
    return map(a->convert(atype,a), w)
end

function minibatch4(x, y, batchsize; atype=KnetArray{Float32})
    data = minibatch(x,y,batchsize; atype=atype)
    for i=1:length(data)
        (x,y) = data[i]
        data[i] = (reshape(x, (28,28,1,batchsize)), y)
    end
    return data
end

function xavier(a...)
    w = rand(a...)
     # The old implementation was not right for fully connected layers:
     # (fanin = length(y) / (size(y)[end]); scale = sqrt(3 / fanin); axpb!(rand!(y); a=2*scale, b=-scale)) :
    if ndims(w) < 2
        error("ndims=$(ndims(w)) in xavier")
    elseif ndims(w) == 2
        fanout = size(w,1)
        fanin = size(w,2)
    else
        fanout = size(w, ndims(w)) # Caffe disagrees: http://caffe.berkeleyvision.org/doxygen/classcaffe_1_1XavierFiller.html#details
        fanin = div(length(w), fanout)
    end
    # See: http://jmlr.org/proceedings/papers/v9/glorot10a/glorot10a.pdf
    s = sqrt(2 / (fanin + fanout))
    w = 2s*w-s
end

function main(args=ARGS)
    s = ArgParseSettings()
    s.description="lenet.jl (c) Deniz Yuret, 2016. The LeNet model on the MNIST handwritten digit recognition problem from http://yann.lecun.com/exdb/mnist."
    s.exc_handler=ArgParse.debug_handler
    @add_arg_table s begin
        ("--seed"; arg_type=Int; default=-1; help="random number seed: use a nonnegative int for repeatable results")
        ("--batchsize"; arg_type=Int; default=128; help="minibatch size")
        ("--lr"; arg_type=Float64; default=0.1; help="learning rate")
        ("--fast"; action=:store_true; help="skip loss printing for faster run")
        ("--epochs"; arg_type=Int; default=3; help="number of epochs for training")
        ("--iters"; arg_type=Int; default=typemax(Int); help="maximum number of updates for training")
        ("--gcheck"; arg_type=Int; default=0; help="check N random gradients per parameter")
        ("--atype"; default=(gpu()>=0 ? "KnetArray{Float32}" : "Array{Float32}"); help="array and float type to use")
    end
    println(s.description)
    isa(args, AbstractString) && (args=split(args))
    o = parse_args(args, s; as_symbols=true)
    println("opts=",[(k,v) for (k,v) in o]...)
    o[:seed] > 0 && srand(o[:seed])
    atype = eval(parse(o[:atype]))
    if atype <: Array; warn("CPU conv4 support is experimental and very slow."); end

    isdefined(MNIST,:xtrn) || MNIST.loaddata()
    dtrn = minibatch4(MNIST.xtrn, MNIST.ytrn, o[:batchsize]; atype=atype)
    dtst = minibatch4(MNIST.xtst, MNIST.ytst, o[:batchsize]; atype=atype)
    w = weights(atype=atype)
    report(epoch)=println((:epoch,epoch,:trn,accuracy(w,dtrn,predict),:tst,accuracy(w,dtst,predict)))

    if o[:fast]
        @time (train(w, dtrn; lr=o[:lr], epochs=o[:epochs], iters=o[:iters]); gpu()>=0 && Knet.cudaDeviceSynchronize())
    else
        report(0)
        iters = o[:iters]
        @time for epoch=1:o[:epochs]
            train(w, dtrn; lr=o[:lr], epochs=1, iters=iters)
            report(epoch)
            if o[:gcheck] > 0
                gradcheck(loss, w, first(dtrn)...; gcheck=o[:gcheck], verbose=true)
            end
            if (iters -= length(dtrn)) <= 0; break; end
        end
    end
    return w
end


# This allows both non-interactive (shell command) and interactive calls like:
# $ julia lenet.jl --epochs 10
# julia> LeNet.main("--epochs 10")
if VERSION >= v"0.5.0-dev+7720"
    PROGRAM_FILE == "lenet.jl" && main(ARGS)
else
    !isinteractive() && !isdefined(Core.Main,:load_only) && main(ARGS)
end

# module

# SAMPLE RUN 65f57ff+ Wed Sep 14 10:02:30 EEST 2016
#
# lenet.jl (c) Deniz Yuret, 2016. The LeNet model on the MNIST handwritten digit recognition problem from http://yann.lecun.com/exdb/mnist.
# opts=(:seed,-1)(:batchsize,100)(:epochs,3)(:lr,0.1)(:gcheck,0)(:fast,true)
# ..................  
# 9.319163 seconds (5.84 M allocations: 277.927 MB, 7.37% gc time)
```

**Comment by denizyuret** [comment]
The optimization parameters (like Momentum) are defined per weight array.
 (e.g. you may choose to use Sgd on some weights, and Momentum on others).
Thus the third argument to update needs to have the same number of elements
and shape as the first argument.  See the `initoptim` function I use for
this in the examples I mentioned before.

**Comment by undefdev** [comment]
Ah! That's more flexibility than I expected. Great!
Thank you very much, I will work myself through those examples!

**Comment by denizyuret** [comment]
You are welcome, good luck.  Also see
http://denizyuret.github.io/Knet.jl/latest/reference.html#Optimization-methods-1
