### ISSUE TITLE
No Longer building on OSX (no CUDA)

### ISSUE THREAD

**Issue by clive-g-brown** [denizyuret/Knet.jl#117]
INFO: Building Knet
WARNING: Cannot find nvcc, GPU support will not be available.
make: `libknet8.so' is up to date.
WARNING: could not import AutoGrad.UngetIndex into Knet
ERROR: LoadError: LoadError: UndefVarError: UngetIndex not defined
 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in macro expansion; at ./none:2 [inlined]
 in anonymous at ./<missing>:?
 in eval(::Module, ::Any) at ./boot.jl:234
 in eval(::Module, ::Any) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in process_options(::Base.JLOptions) at ./client.jl:242
 in _start() at ./client.jl:321
 in _start() at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
while loading /Users/clivebrown/.julia/v0.5/Knet/src/karray.jl, in expression starting on line 995
while loading /Users/clivebrown/.julia/v0.5/Knet/src/Knet.jl, in expression starting on line 16
================================[ ERROR: Knet ]=================================

LoadError: Failed to precompile Knet to /Users/clivebrown/.julia/lib/v0.5/Knet.ji.
while loading /Users/clivebrown/.julia/v0.5/Knet/deps/build.jl, in expression starting on line 9

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: Knet had build errors.

 - packages with build errors remain installed in /Users/clivebrown/.julia/v0.5
 - build the package(s) and all dependencies with `Pkg.build("Knet")`
 - build a single package by running its `deps/build.jl` script

===============================================================================

**Comment by ilkerkesen** [comment]
I think you need a newer version of AutoGrad. Could you please follow the instructions below and see what happens then?

```Pkg.update()
Pkg.add("AutoGrad")
Pkg.checkout("AutoGrad")
Pkg.add("Knet")
Pkg.checkout("Knet")
Pkg.build("Knet")```

I think you may skip Pkg.add steps if you already installed the packages.

**Comment by clive-g-brown** [comment]
yes - fixed. thanks!!
