### ISSUE TITLE
0.6 support

### ISSUE THREAD

**Issue by jpfairbanks** [denizyuret/Knet.jl#118]
This package looks great. Have you started on julia-v0.6 support? I just ran the tests for the latest stable release using Julia v0.6-pre.beta and they failed (without GPU).

**Comment by denizyuret** [comment]
Will start soon.  The big issue is AutoGrad, it touches a lot of broadcasting operations whose syntax has changed in 0.6.  Also of concern is continuing 0.4 support as it seems faster than 0.5, but I am not sure if I can support 0.4 and 0.6 at the same time.  May have to branch...

**Comment by jpfairbanks** [comment]
The way we handled this on LightGraphs.jl is to support at most 2 versions of julia at a time. When it comes time to stop supporting julia v0.4.z we have a new release of our package tagged as x.y.z which is the last version supporting julia 0.4 and introduce x.y+1.0 which supports only julia version 0.5+. 

This allows you to say "everyone who is still using julia 0.4 can keep using Knet x.y.z" and "everyone who can upgrade julia should move to the x.y+1.0 version". We have found this a manageable trade off between maintenance time and staying current.

**Comment by jpfairbanks** [comment]
It looks like the .travis.yml file has been updated for nightly but not 0.6.  @denizyuret did you intend to skip support for 0.6 and go right to 0.7?

**Comment by denizyuret** [comment]
I am working on 0.6 support right now, I haven't looked at 0.7 yet.  But I
suspect the 0.6-0.7 transition will be much simpler than the 0.5-0.6
transition.

**Comment by jpfairbanks** [comment]
PR #155 just adds 0.6 to the list of versions tested on CI
