### ISSUE TITLE
Knet Test failing on version no.

### ISSUE THREAD

**Issue by akaysh** [denizyuret/Knet.jl#120]
```
julia> Pkg.update("Knet")
INFO: Updating METADATA...
INFO: Computing changes...
INFO: No packages to install, update or remove

julia> Pkg.build("Knet")
INFO: Building Knet
INFO: Compiling CUDA kernels.
make: 'libknet8.so' is up to date.

julia> Pkg.test("Knet")
INFO: Computing test dependencies for Knet...
INFO: Installing BaseTestNext v0.2.2
INFO: Testing Knet
INFO: Knet using GPU 0
Test Summary: | Pass  Total
  kptr        |    1      1
  1.819469 seconds (1.21 M allocations: 53.322 MB, 6.66% gc time)
WARNING: cudnn.cudnnCreate error 6

 in cudnnCreate() at /home/akshay/.julia/v0.5/Knet/src/gpu.jl:16
 in cudnnhandle(::Int64) at /home/akshay/.julia/v0.5/Knet/src/gpu.jl:120
 in macro expansion; at /home/akshay/.julia/v0.5/Knet/test/gpu.jl:9 [inlined]
 in macro expansion; at ./test.jl:672 [inlined]
 in macro expansion; at /home/akshay/.julia/v0.5/Knet/test/gpu.jl:4 [inlined]
 in anonymous at ./<missing>:?
 in include_from_node1(::String) at ./loading.jl:488 (repeats 2 times)
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318gpu: Test Failed
  Expression: all((p->begin 
            p > Knet.Cptr(0)
        end),(Knet.cublashandle(),Knet.cudnnhandle()))
 in record(::Base.Test.DefaultTestSet, ::Base.Test.Fail) at ./test.jl:428
 in do_test(::Base.Test.Returned, ::Expr) at ./test.jl:281
 in macro expansion; at /home/akshay/.julia/v0.5/Knet/test/gpu.jl:9 [inlined]
 in macro expansion; at ./test.jl:672 [inlined]
 in macro expansion; at /home/akshay/.julia/v0.5/Knet/test/gpu.jl:4 [inlined]
 in anonymous at ./<missing>:?
 in include_from_node1(::String) at ./loading.jl:488 (repeats 2 times)
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
(Knet.cudaDriverVersion,Knet.cudaRuntimeVersion,Knet.cublasVersion,Knet.cudnnVersion) = (8000,8000,8000,6021)
Test Summary: | Pass  Fail  Total
  gpu         |    7     1      8
ERROR: LoadError: LoadError: Some tests did not pass: 7 passed, 1 failed, 0 errored, 0 broken.
 in finish(::Base.Test.DefaultTestSet) at ./test.jl:495
 in macro expansion; at ./test.jl:679 [inlined]
 in macro expansion; at /home/akshay/.julia/v0.5/Knet/test/gpu.jl:4 [inlined]
 in anonymous at ./<missing>:?
 in include_from_node1(::String) at ./loading.jl:488 (repeats 2 times)
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
while loading /home/akshay/.julia/v0.5/Knet/test/gpu.jl, in expression starting on line 3
while loading /home/akshay/.julia/v0.5/Knet/test/runtests.jl, in expression starting on line 184
WARNING: cudnn.cudnnDestroy error 3

 in (::Knet.##5#6)() at /home/akshay/.julia/v0.5/Knet/src/gpu.jl:16
 in _atexit() at ./initdefs.jl:114
 in _start() at ./client.jl:365=============================================================================[ ERROR: Knet ]==============================================================================

failed process: Process(`/home/akshay/julia/bin/julia -Cx86-64 -J/home/akshay/julia/lib/julia/sys.so --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=yes --compilecache=yes /home/akshay/.julia/v0.5/Knet/test/runtests.jl`, ProcessExited(1)) [1]

==========================================================================================================================================================================
INFO: Removing BaseTestNext v0.2.2
ERROR: Knet had test errors
 in #test#61(::Bool, ::Function, ::Array{AbstractString,1}) at ./pkg/entry.jl:740
 in (::Base.Pkg.Entry.#kw##test)(::Array{Any,1}, ::Base.Pkg.Entry.#test, ::Array{AbstractString,1}) at ./<missing>:0
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}})() at ./pkg/dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}}, ::String) at ./file.jl:59
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at ./pkg/dir.jl:31
 in (::Base.Pkg.Dir.#kw##cd)(::Array{Any,1}, ::Base.Pkg.Dir.#cd, ::Function, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at ./<missing>:0
 in #test#3(::Bool, ::Function, ::String, ::Vararg{String,N}) at ./pkg/pkg.jl:258
 in test(::String, ::Vararg{String,N}) at ./pkg/pkg.jl:258
```

**Comment by akaysh** [comment]
I am using CUDA toolkit version 8 and cuDNN version 6. Also I am able to successfully build CUDA samples and they work just fine.

**Comment by denizyuret** [comment]
Can you let me know your julia, Knet, and AutoGrad versions?

**Comment by maltintas45** [comment]
I have got the same issue. 

`Pkg.test("Knet")
INFO: Computing test dependencies for Knet...
INFO: Cloning cache of BaseTestNext from https://github.com/JuliaCI/BaseTestNext.jl.git
INFO: Cloning cache of Combinatorics from https://github.com/JuliaMath/Combinatorics.jl.git
INFO: Cloning cache of IterTools from https://github.com/JuliaCollections/IterTools.jl.git
INFO: Cloning cache of Polynomials from https://github.com/JuliaMath/Polynomials.jl.git
INFO: Installing BaseTestNext v0.2.2
INFO: Installing Combinatorics v0.4.1
INFO: Installing IterTools v0.1.0
INFO: Installing Polynomials v0.1.6
INFO: Testing Knet
Test Summary: | Pass  Total
  kptr        |    1      1
  5.720421 seconds (1.56 M allocations: 68.857 MB, 4.91% gc time)
gpu: Error During Test
  Test threw an exception of type ErrorException
  Expression: all((p->begin 
            p > Knet.Cptr(0)
        end),(Knet.cublashandle(),Knet.cudnnhandle()))
  cudnn.cudnnCreate error 6
   in cudnnCreate() at /home/heysem/.julia/v0.5/Knet/src/gpu.jl:9
   in cudnnhandle(::Int64) at /home/heysem/.julia/v0.5/Knet/src/gpu.jl:133
   in macro expansion; at /home/heysem/.julia/v0.5/Knet/test/gpu.jl:9 [inlined]
   in macro expansion; at ./test.jl:674 [inlined]
   in macro expansion; at /home/heysem/.julia/v0.5/Knet/test/gpu.jl:4 [inlined]
   in anonymous at ./<missing>:?
   in include_from_node1(::String) at ./loading.jl:488 (repeats 2 times)
   in process_options(::Base.JLOptions) at ./client.jl:265
   in _start() at ./client.jl:321
gpu: Error During Test
  Test threw an exception of type UndefVarError
  Expression: all((v->begin 
            v > 0
        end),@show((Knet.cudaDriverVersion,Knet.cudaRuntimeVersion,Knet.cublasVersion,Knet.cudnnVersion)))
  UndefVarError: cudnnVersion not defined
   in macro expansion; at ./show.jl:218 [inlined]
   in macro expansion; at /home/heysem/.julia/v0.5/Knet/test/gpu.jl:10 [inlined]
   in macro expansion; at ./test.jl:674 [inlined]
   in macro expansion; at /home/heysem/.julia/v0.5/Knet/test/gpu.jl:4 [inlined]
   in anonymous at ./<missing>:?
   in include_from_node1(::String) at ./loading.jl:488 (repeats 2 times)
   in process_options(::Base.JLOptions) at ./client.jl:265
   in _start() at ./client.jl:321
Test Summary: | Pass  Error  Total
  gpu         |    6      2      8
ERROR: LoadError: LoadError: Some tests did not pass: 6 passed, 0 failed, 2 errored, 0 broken.
 in finish(::Base.Test.DefaultTestSet) at ./test.jl:498
 in macro expansion; at ./test.jl:681 [inlined]
 in macro expansion; at /home/heysem/.julia/v0.5/Knet/test/gpu.jl:4 [inlined]
 in anonymous at ./<missing>:?
 in include_from_node1(::String) at ./loading.jl:488 (repeats 2 times)
 in process_options(::Base.JLOptions) at ./client.jl:265
 in _start() at ./client.jl:321
while loading /home/heysem/.julia/v0.5/Knet/test/gpu.jl, in expression starting on line 3
while loading /home/heysem/.julia/v0.5/Knet/test/runtests.jl, in expression starting on line 188
===================================================[ ERROR: Knet ]===================================================

failed process: Process(`/usr/bin/julia -Cx86-64 -J/usr/lib/x86_64-linux-gnu/julia/sys.so --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=yes --compilecache=yes /home/heysem/.julia/v0.5/Knet/test/runtests.jl`, ProcessExited(1)) [1]

=====================================================================================================================
INFO: Removing BaseTestNext v0.2.2
INFO: Removing Combinatorics v0.4.1
INFO: Removing IterTools v0.1.0
INFO: Removing Polynomials v0.1.6
ERROR: Knet had test errors
 in #test#61(::Bool, ::Function, ::Array{AbstractString,1}) at ./pkg/entry.jl:748
 in (::Base.Pkg.Entry.#kw##test)(::Array{Any,1}, ::Base.Pkg.Entry.#test, ::Array{AbstractString,1}) at ./<missing>:0
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}})() at ./pkg/dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}}, ::String) at ./file.jl:59
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at ./pkg/dir.jl:31
 in (::Base.Pkg.Dir.#kw##cd)(::Array{Any,1}, ::Base.Pkg.Dir.#cd, ::Function, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at ./<missing>:0
 in #test#3(::Bool, ::Function, ::String, ::Vararg{String,N}) at ./pkg/pkg.jl:258
 in test(::String, ::Vararg{String,N}) at ./pkg/pkg.jl:258
`
Julia version 0.5
System Ubuntu 14.04
Cuda 7.0
Cudnn 4.0

'Pkg.installed()
Dict{String,VersionNumber} with 6 entries:
  "AutoGrad" => v"0.0.7"
  "Compat"   => v"0.30.0"
  "Knet"     => v"0.8.3"
  "TextWrap" => v"0.2.0"
  "GZip"     => v"0.3.0"
  "ArgParse" => v"0.5.0"
'

**Comment by denizyuret** [comment]
Error 6 is defined in cudnn.h as: CUDNN_STATUS_ARCH_MISMATCH
This looks like a hardware library compatibility problem.
Can you compile / run cudnn based C programs successfully?
Could https://github.com/denizyuret/Knet.jl/pull/154 help?
