### ISSUE TITLE
Pkg.build("Knet") and Pkg.test("Knet") fail

### ISSUE THREAD

**Issue by finmod** [denizyuret/Knet.jl#131]
On Windows 10 laptop, after a fresh install with Pkg.add("Knet"), Pkg.build("Knet") and Pkg.test("Knet") fail as below:

               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.2 (2017-05-06 16:34 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> Pkg.build("Knet")
INFO: Building Knet
INFO: Compiling CUDA kernels.
================================[ ERROR: Knet ]=================================

LoadError: could not spawn `make`: no such file or directory (ENOENT)
while loading C:\Users\Denis\.julia\v0.5\Knet\deps\build.jl, in expression starting on line 6

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: Knet had build errors.

 - packages with build errors remain installed in C:\Users\Denis\.julia\v0.5
 - build the package(s) and all dependencies with `Pkg.build("Knet")`
 - build a single package by running its `deps/build.jl` script

================================================================================

julia>

Pkg.test("Knet")

t .\<missing>:0
   in #gradcheck#17(::Array{Tuple{Symbol,Int64},1}, ::Array{Any,1}, ::Function, ::Function, ::Array{Float64,4}) at C:\Users\Denis\.julia\v0.5\AutoGrad\src\gradcheck.jl:29
   in (::AutoGrad.#kw##gradcheck)(::Array{Any,1}, ::AutoGrad.#gradcheck, ::Function, ::Array{Float64,4}) at .\<missing>:0
   in macro expansion; at C:\Users\Denis\.julia\v0.5\Knet\test\conv.jl:88 [inlined]
   in macro expansion; at .\test.jl:674 [inlined]
   in macro expansion; at C:\Users\Denis\.julia\v0.5\Knet\test\conv.jl:25 [inlined]
   in macro expansion; at .\test.jl:674 [inlined]
   in anonymous at .\<missing>:?
   in include_from_node1(::String) at .\loading.jl:488 (repeats 2 times)
   in process_options(::Base.JLOptions) at .\client.jl:265
   in _start() at .\client.jl:321
cpuconv: Error During Test
  Test threw an exception of type ErrorException
  Expression: isapprox(pool(unpool(ax; mode=2); mode=2),ax)
  Cannot find libknet8, please rerun Pkg.build("Knet").
   in #poolx#302(::Int64, ::Int64, ::Int64, ::Int64, ::Int64, ::Float64, ::Void, ::Function, ::Array{Float64,4}, ::Array{Float64,4}, ::Array{Float64,4}) at C:\Users\Denis\.julia\v0.5\Knet\src\conv.jl:537
   in (::Knet.#kw##poolx)(::Array{Any,1}, ::Knet.#poolx, ::Array{Float64,4}, ::Array{Float64,4}, ::Array{Float64,4}) at .\<missing>:0
   in #unpool#221(::Int64, ::Int64, ::Array{Any,1}, ::Function, ::Array{Float64,4}) at C:\Users\Denis\.julia\v0.5\Knet\src\conv.jl:159
   in (::Knet.#kw##unpool)(::Array{Any,1}, ::Knet.#unpool, ::Array{Float64,4}) at .\<missing>:0
   in macro expansion; at C:\Users\Denis\.julia\v0.5\Knet\test\conv.jl:89 [inlined]
   in macro expansion; at .\test.jl:674 [inlined]
   in macro expansion; at C:\Users\Denis\.julia\v0.5\Knet\test\conv.jl:25 [inlined]
   in macro expansion; at .\test.jl:674 [inlined]
   in anonymous at .\<missing>:?
   in include_from_node1(::String) at .\loading.jl:488 (repeats 2 times)
   in process_options(::Base.JLOptions) at .\client.jl:265
   in _start() at .\client.jl:321
cpuconv: Error During Test
  Test threw an exception of type ErrorException
  Expression: gradcheck(pool,ax; kwargs=[(:alpha,2)])
  Cannot find libknet8, please rerun Pkg.build("Knet").
   in #pool#301(::Int64, ::Int64, ::Int64, ::Int64, ::Int64, ::Int64, ::Void, ::Function, ::Array{Float64,4}) at C:\Users\Denis\.julia\v0.5\Knet\src\conv.jl:508
   in (::Knet.#kw##pool)(::Array{Any,1}, ::Knet.#pool, ::Array{Float64,4}) at .\<missing>:0
   in #gradcheck#17(::Array{Tuple{Symbol,Int64},1}, ::Array{Any,1}, ::Function, ::Function, ::Array{Float64,4}) at C:\Users\Denis\.julia\v0.5\AutoGrad\src\gradcheck.jl:29
   in (::AutoGrad.#kw##gradcheck)(::Array{Any,1}, ::AutoGrad.#gradcheck, ::Function, ::Array{Float64,4}) at .\<missing>:0
   in macro expansion; at C:\Users\Denis\.julia\v0.5\Knet\test\conv.jl:92 [inlined]
   in macro expansion; at .\test.jl:674 [inlined]
   in macro expansion; at C:\Users\Denis\.julia\v0.5\Knet\test\conv.jl:25 [inlined]
   in macro expansion; at .\test.jl:674 [inlined]
   in anonymous at .\<missing>:?
   in include_from_node1(::String) at .\loading.jl:488 (repeats 2 times)
   in process_options(::Base.JLOptions) at .\client.jl:265
   in _start() at .\client.jl:321
cpuconv: Error During Test
  Test threw an exception of type ErrorException
  Expression: gradcheck(unpool,ax; kwargs=[(:alpha,2)])
  Cannot find libknet8, please rerun Pkg.build("Knet").
   in #poolx#302(::Int64, ::Int64, ::Int64, ::Int64, ::Int64, ::Float64, ::Void, ::Function, ::Array{Float64,4}, ::Array{Float64,4}, ::Array{Float64,4}) at C:\Users\Denis\.julia\v0.5\Knet\src\conv.jl:537
   in (::Knet.#kw##poolx)(::Array{Any,1}, ::Knet.#poolx, ::Array{Float64,4}, ::Array{Float64,4}, ::Array{Float64,4}) at .\<missing>:0
   in #unpool#221(::Int64, ::Int64, ::Array{Any,1}, ::Function, ::Array{Float64,4}) at C:\Users\Denis\.julia\v0.5\Knet\src\conv.jl:159
   in (::Knet.#kw##unpool)(::Array{Any,1}, ::Knet.#unpool, ::Array{Float64,4}) at .\<missing>:0
   in #gradcheck#17(::Array{Tuple{Symbol,Int64},1}, ::Array{Any,1}, ::Function, ::Function, ::Array{Float64,4}) at C:\Users\Denis\.julia\v0.5\AutoGrad\src\gradcheck.jl:29
   in (::AutoGrad.#kw##gradcheck)(::Array{Any,1}, ::AutoGrad.#gradcheck, ::Function, ::Array{Float64,4}) at .\<missing>:0
   in macro expansion; at C:\Users\Denis\.julia\v0.5\Knet\test\conv.jl:93 [inlined]
   in macro expansion; at .\test.jl:674 [inlined]
   in macro expansion; at C:\Users\Denis\.julia\v0.5\Knet\test\conv.jl:25 [inlined]
   in macro expansion; at .\test.jl:674 [inlined]
   in anonymous at .\<missing>:?
   in include_from_node1(::String) at .\loading.jl:488 (repeats 2 times)
   in process_options(::Base.JLOptions) at .\client.jl:265
   in _start() at .\client.jl:321
cpuconv: Error During Test
  Test threw an exception of type ErrorException
  Expression: isapprox(pool(unpool(ax; alpha=2); alpha=2),ax)
  Cannot find libknet8, please rerun Pkg.build("Knet").
   in #poolx#302(::Int64, ::Int64, ::Int64, ::Int64, ::Int64, ::Float64, ::Void, ::Function, ::Array{Float64,4}, ::Array{Float64,4}, ::Array{Float64,4}) at C:\Users\Denis\.julia\v0.5\Knet\src\conv.jl:537
   in (::Knet.#kw##poolx)(::Array{Any,1}, ::Knet.#poolx, ::Array{Float64,4}, ::Array{Float64,4}, ::Array{Float64,4}) at .\<missing>:0
   in #unpool#221(::Int64, ::Int64, ::Array{Any,1}, ::Function, ::Array{Float64,4}) at C:\Users\Denis\.julia\v0.5\Knet\src\conv.jl:159
   in (::Knet.#kw##unpool)(::Array{Any,1}, ::Knet.#unpool, ::Array{Float64,4}) at .\<missing>:0
   in macro expansion; at C:\Users\Denis\.julia\v0.5\Knet\test\conv.jl:94 [inlined]
   in macro expansion; at .\test.jl:674 [inlined]
   in macro expansion; at C:\Users\Denis\.julia\v0.5\Knet\test\conv.jl:25 [inlined]
   in macro expansion; at .\test.jl:674 [inlined]
   in anonymous at .\<missing>:?
   in include_from_node1(::String) at .\loading.jl:488 (repeats 2 times)
   in process_options(::Base.JLOptions) at .\client.jl:265
   in _start() at .\client.jl:321
cpuconv: Error During Test
  Test threw an exception of type ErrorException
  Expression: gradcheck(pool,ax; kwargs=[(:alpha,2),(:mode,1)])
  Cannot find libknet8, please rerun Pkg.build("Knet").
   in #pool#301(::Int64, ::Int64, ::Int64, ::Int64, ::Int64, ::Int64, ::Void, ::Function, ::Array{Float64,4}) at C:\Users\Denis\.julia\v0.5\Knet\src\conv.jl:512
   in (::Knet.#kw##pool)(::Array{Any,1}, ::Knet.#pool, ::Array{Float64,4}) at .\<missing>:0
   in #gradcheck#17(::Array{Tuple{Symbol,Int64},1}, ::Array{Any,1}, ::Function, ::Function, ::Array{Float64,4}) at C:\Users\Denis\.julia\v0.5\AutoGrad\src\gradcheck.jl:29
   in (::AutoGrad.#kw##gradcheck)(::Array{Any,1}, ::AutoGrad.#gradcheck, ::Function, ::Array{Float64,4}) at .\<missing>:0
   in macro expansion; at C:\Users\Denis\.julia\v0.5\Knet\test\conv.jl:95 [inlined]
   in macro expansion; at .\test.jl:674 [inlined]
   in macro expansion; at C:\Users\Denis\.julia\v0.5\Knet\test\conv.jl:25 [inlined]
   in macro expansion; at .\test.jl:674 [inlined]
   in anonymous at .\<missing>:?
   in include_from_node1(::String) at .\loading.jl:488 (repeats 2 times)
   in process_options(::Base.JLOptions) at .\client.jl:265
   in _start() at .\client.jl:321
cpuconv: Error During Test
  Test threw an exception of type ErrorException
  Expression: gradcheck(unpool,ax; kwargs=[(:alpha,2),(:mode,1)])
  Cannot find libknet8, please rerun Pkg.build("Knet").
   in #poolx#302(::Int64, ::Int64, ::Int64, ::Int64, ::Int64, ::Float64, ::Void, ::Function, ::Array{Float64,4}, ::Array{Float64,4}, ::Array{Float64,4}) at C:\Users\Denis\.julia\v0.5\Knet\src\conv.jl:537
   in (::Knet.#kw##poolx)(::Array{Any,1}, ::Knet.#poolx, ::Array{Float64,4}, ::Array{Float64,4}, ::Array{Float64,4}) at .\<missing>:0
   in #unpool#221(::Int64, ::Int64, ::Array{Any,1}, ::Function, ::Array{Float64,4}) at C:\Users\Denis\.julia\v0.5\Knet\src\conv.jl:159
   in (::Knet.#kw##unpool)(::Array{Any,1}, ::Knet.#unpool, ::Array{Float64,4}) at .\<missing>:0
   in #gradcheck#17(::Array{Tuple{Symbol,Int64},1}, ::Array{Any,1}, ::Function, ::Function, ::Array{Float64,4}) at C:\Users\Denis\.julia\v0.5\AutoGrad\src\gradcheck.jl:29
   in (::AutoGrad.#kw##gradcheck)(::Array{Any,1}, ::AutoGrad.#gradcheck, ::Function, ::Array{Float64,4}) at .\<missing>:0
   in macro expansion; at C:\Users\Denis\.julia\v0.5\Knet\test\conv.jl:96 [inlined]
   in macro expansion; at .\test.jl:674 [inlined]
   in macro expansion; at C:\Users\Denis\.julia\v0.5\Knet\test\conv.jl:25 [inlined]
   in macro expansion; at .\test.jl:674 [inlined]
   in anonymous at .\<missing>:?
   in include_from_node1(::String) at .\loading.jl:488 (repeats 2 times)
   in process_options(::Base.JLOptions) at .\client.jl:265
   in _start() at .\client.jl:321
cpuconv: Error During Test
  Test threw an exception of type ErrorException
  Expression: isapprox(pool(unpool(ax; alpha=2,mode=1); alpha=2,mode=1),ax)
  Cannot find libknet8, please rerun Pkg.build("Knet").
   in #poolx#302(::Int64, ::Int64, ::Int64, ::Int64, ::Int64, ::Float64, ::Void, ::Function, ::Array{Float64,4}, ::Array{Float64,4}, ::Array{Float64,4}) at C:\Users\Denis\.julia\v0.5\Knet\src\conv.jl:537
   in (::Knet.#kw##poolx)(::Array{Any,1}, ::Knet.#poolx, ::Array{Float64,4}, ::Array{Float64,4}, ::Array{Float64,4}) at .\<missing>:0
   in #unpool#221(::Int64, ::Int64, ::Array{Any,1}, ::Function, ::Array{Float64,4}) at C:\Users\Denis\.julia\v0.5\Knet\src\conv.jl:159
   in (::Knet.#kw##unpool)(::Array{Any,1}, ::Knet.#unpool, ::Array{Float64,4}) at .\<missing>:0
   in macro expansion; at C:\Users\Denis\.julia\v0.5\Knet\test\conv.jl:97 [inlined]
   in macro expansion; at .\test.jl:674 [inlined]
   in macro expansion; at C:\Users\Denis\.julia\v0.5\Knet\test\conv.jl:25 [inlined]
   in macro expansion; at .\test.jl:674 [inlined]
   in anonymous at .\<missing>:?
   in include_from_node1(::String) at .\loading.jl:488 (repeats 2 times)
   in process_options(::Base.JLOptions) at .\client.jl:265
   in _start() at .\client.jl:321
cpuconv: Error During Test
  Test threw an exception of type ErrorException
  Expression: gradcheck(conv41,(aw,ax); rtol=TOL,kwargs=[(:alpha,2)])
  Cannot find libknet8, please rerun Pkg.build("Knet").
   in im2col!(::Array{Float64,4}, ::Array{Float64,4}, ::Array{Float64,2}, ::Int64, ::Int64, ::Int64, ::Int64, ::Int64, ::Int64) at C:\Users\Denis\.julia\v0.5\Knet\src\conv.jl:480
   in #conv4#296(::Int64, ::Int64, ::Int64, ::Int64, ::Int64, ::Array{Any,1}, ::Function, ::Array{Float64,4}, ::Array{Float64,4}) at C:\Users\Denis\.julia\v0.5\Knet\src\conv.jl:408
   in (::Knet.#kw##conv4)(::Array{Any,1}, ::Knet.#conv4, ::Array{Float64,4}, ::Array{Float64,4}) at .\<missing>:0
   in #conv41#59(::Array{Any,1}, ::Function, ::Tuple{Array{Float64,4},Array{Float64,4}}) at C:\Users\Denis\.julia\v0.5\Knet\test\conv.jl:5
   in (::#kw##conv41)(::Array{Any,1}, ::#conv41, ::Tuple{Array{Float64,4},Array{Float64,4}}) at .\<missing>:0
   in #gradcheck#17(::Array{Tuple{Symbol,Int64},1}, ::Array{Any,1}, ::Function, ::Function, ::Tuple{Array{Float64,4},Array{Float64,4}}) at C:\Users\Denis\.julia\v0.5\AutoGrad\src\gradcheck.jl:29
   in (::AutoGrad.#kw##gradcheck)(::Array{Any,1}, ::AutoGrad.#gradcheck, ::Function, ::Tuple{Array{Float64,4},Array{Float64,4}}) at .\<missing>:0
   in macro expansion; at C:\Users\Denis\.julia\v0.5\Knet\test\conv.jl:98 [inlined]
   in macro expansion; at .\test.jl:674 [inlined]
   in macro expansion; at C:\Users\Denis\.julia\v0.5\Knet\test\conv.jl:25 [inlined]
   in macro expansion; at .\test.jl:674 [inlined]
   in anonymous at .\<missing>:?
   in include_from_node1(::String) at .\loading.jl:488 (repeats 2 times)
   in process_options(::Base.JLOptions) at .\client.jl:265
   in _start() at .\client.jl:321
cpuconv: Error During Test
  Test threw an exception of type ErrorException
  Expression: gradcheck(deconv41,(aw,ax); rtol=TOL,kwargs=[(:alpha,2)])
  Cannot find libknet8, please rerun Pkg.build("Knet").
   in col2im!(::Array{Float64,4}, ::Array{Float64,4}, ::Array{Float64,2}, ::Int64, ::Int64, ::Int64, ::Int64, ::Int64, ::Int64) at C:\Users\Denis\.julia\v0.5\Knet\src\conv.jl:491
   in #conv4x#298(::Int64, ::Int64, ::Int64, ::Int64, ::Int64, ::Array{Any,1}, ::Function, ::Array{Float64,4}, ::Array{Float64,4}, ::Array{Float64,4}) at C:\Users\Denis\.julia\v0.5\Knet\src\conv.jl:463
   in (::Knet.#kw##conv4x)(::Array{Any,1}, ::Knet.#conv4x, ::Array{Float64,4}, ::Array{Float64,4}, ::Array{Float64,4}) at .\<missing>:0
   in #deconv4#227(::Array{Any,1}, ::Function, ::Array{Float64,4}, ::Array{Float64,4}) at C:\Users\Denis\.julia\v0.5\Knet\src\conv.jl:178
   in (::Knet.#kw##deconv4)(::Array{Any,1}, ::Knet.#deconv4, ::Array{Float64,4}, ::Array{Float64,4}) at .\<missing>:0
   in #deconv41#60(::Array{Any,1}, ::Function, ::Tuple{Array{Float64,4},Array{Float64,4}}) at C:\Users\Denis\.julia\v0.5\Knet\test\conv.jl:6
   in (::#kw##deconv41)(::Array{Any,1}, ::#deconv41, ::Tuple{Array{Float64,4},Array{Float64,4}}) at .\<missing>:0
   in #gradcheck#17(::Array{Tuple{Symbol,Int64},1}, ::Array{Any,1}, ::Function, ::Function, ::Tuple{Array{Float64,4},Array{Float64,4}}) at C:\Users\Denis\.julia\v0.5\AutoGrad\src\gradcheck.jl:29
   in (::AutoGrad.#kw##gradcheck)(::Array{Any,1}, ::AutoGrad.#gradcheck, ::Function, ::Tuple{Array{Float64,4},Array{Float64,4}}) at .\<missing>:0
   in macro expansion; at C:\Users\Denis\.julia\v0.5\Knet\test\conv.jl:99 [inlined]
   in macro expansion; at .\test.jl:674 [inlined]
   in macro expansion; at C:\Users\Denis\.julia\v0.5\Knet\test\conv.jl:25 [inlined]
   in macro expansion; at .\test.jl:674 [inlined]
   in anonymous at .\<missing>:?
   in include_from_node1(::String) at .\loading.jl:488 (repeats 2 times)
   in process_options(::Base.JLOptions) at .\client.jl:265
   in _start() at .\client.jl:321
Test Summary: | Error  Total
  conv        |    52     52
  cpuconv     |    52     52
ERROR: LoadError: LoadError: Some tests did not pass: 0 passed, 0 failed, 52 errored, 0 broken.
 in finish(::Base.Test.DefaultTestSet) at .\test.jl:498
 in macro expansion; at .\test.jl:681 [inlined]
 in anonymous at .\<missing>:?
 in include_from_node1(::String) at .\loading.jl:488 (repeats 2 times)
 in process_options(::Base.JLOptions) at .\client.jl:265
 in _start() at .\client.jl:321
while loading C:\Users\Denis\.julia\v0.5\Knet\test\conv.jl, in expression starting on line 24
while loading C:\Users\Denis\.julia\v0.5\Knet\test\runtests.jl, in expression starting on line 188
================================[ ERROR: Knet ]=================================

failed process: Process(`'C:\Users\Denis\AppData\Local\Julia-0.5.2\bin\julia' -Cx86-64 '-JC:\Users\Denis\AppData\Local\Julia-0.5.2\lib\julia\sys.dll' --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=yes --compilecache=yes 'C:\Users\Denis\.julia\v0.5\Knet\test\runtests.jl'`, ProcessExited(1)) [1]

================================================================================
INFO: No packages to install, update or remove
ERROR: Knet had test errors
 in #test#61(::Bool, ::Function, ::Array{AbstractString,1}) at .\pkg\entry.jl:748
 in (::Base.Pkg.Entry.#kw##test)(::Array{Any,1}, ::Base.Pkg.Entry.#test, ::Array{AbstractString,1}) at .\<missing>:0
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}})() at .\pkg\dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}}, ::String) at .\file.jl:48
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at .\pkg\dir.jl:31
 in (::Base.Pkg.Dir.#kw##cd)(::Array{Any,1}, ::Base.Pkg.Dir.#cd, ::Function, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at .\<missing>:0
 in #test#3(::Bool, ::Function, ::String, ::Vararg{String,N}) at .\pkg\pkg.jl:258
 in test(::String, ::Vararg{String,N}) at .\pkg\pkg.jl:258

julia>

**Comment by denizyuret** [comment]
It seems like you don't have the "make" program installed.  Please consult
knet-users mailing list for help, I do not have experience with windows
machines.

**Comment by AStupidBear** [comment]
@denizyuret @finmod Knet dosen't support CUDA on Windows right now . 
Look at this [line](https://github.com/denizyuret/Knet.jl/blob/master/src/Knet.jl#L10). Maybe modify it to ```const libknet8 = Libdl.find_library(["libknet8.so", "libknet8.dll"], [dirname(@__FILE__)])``` will work. I don't have a Windows machine with GPU installed, so I'm not sure about this.

**Comment by amellnik** [comment]
I'm starting to play around with this to see if I can get it working on Windows and will make any updates in #50.

**Comment by fatihtalu** [comment]
The previous version of Knet was running on my windows machine. But Knet v0.8.3 is not.

**Comment by maltintas45** [comment]
@finmod To get rid of  the error, "could not spawn make: no such file or directory (ENOENT)" on windows, please follow this steps;

- install cmake from http://gnuwin32.sourceforge.net/packages/make.htm
- than modify this[ line](https://github.com/denizyuret/Knet.jl/blob/e25d5f7d786b960815d58a6fc1b27c54dbfe2ce5/deps/build.jl#L7) as _run(`**cmake**`)_

**Comment by amellnik** [comment]
@maltintas45 It's going to be quite a bit more complicated than that -- CMake is not a drop-in replacement for the `make` tool and this will require quite a bit of modification to work.

**Comment by denizyuret** [comment]
Latest master supports windows machines.
