### ISSUE TITLE
Gradients for KnetArray

### ISSUE THREAD

**Issue by jgbos** [denizyuret/Knet.jl#134]
What options are there for extending new gradients for `KnetArray`?  I have an architecture that would need to use the matrix inverse and the determinant.  From `AutoGrad.jl`, I just need to do the following for CPU:

```julia
import Base: inv, det
@primitive inv(x), dy, y -(y*dy*y)
@primitive det(x), dy, y (dy.*y.*inv(x))
```

But this won't work for `KnetArray`.

**Comment by denizyuret** [comment]
inv() and det() need to be defined for KnetArray.

**Comment by jgbos** [comment]
Closing this as you provided the solution, just needs some coding.

**Comment by CarloLucibello** [comment]
@jgbos you could sen a PR with those snippets of code to AutoGrad and Knet, i think people could find them usefull (I do)
