### ISSUE TITLE
Julia 0.6 is released, would it be supported soon?

### ISSUE THREAD

**Issue by ngphuoc** [denizyuret/Knet.jl#137]

**Comment by denizyuret** [comment]
Yes, I am planning to work on this during the summer (a large portion of
AutoGrad.jl needs to be rewritten).

**Comment by RoyiAvital** [comment]
Great!
Hopefully 0.7 and 1.0 will be out soon and the framework will be stabilized.

This is one of the best Julia projects out there.

**Comment by xukai92** [comment]
Is there an expected date when the 0.6 compatible version will be released?

**Comment by denizyuret** [comment]
It was released last week.

**Comment by xukai92** [comment]
All right. but it seems on the GitHub home page the tests still fail?

**Comment by denizyuret** [comment]
They pass on my local machine.  I am investigating the problem with the
badges.
