### ISSUE TITLE
KnetArray on Mac 

### ISSUE THREAD

**Issue by kadir-gunel** [denizyuret/Knet.jl#138]
Hello,

I am having difficulties to create KnetArrays. During installation of Knet, cuda libs are recognized and everything went smoothly with some warnings. But when I try to create a KnetArray it prints out 
bad device id -1. 
In order to check if cuda libs are accessible, I installed cublas library which comes with cudadrv lib. And when I test cudadrv lib it sees my gpu and all tests are passed. 

Could you please help me to solve this problem ?  

I am running OS X 10.12.5 with 1080ti. Installed cuda-toolkit version 8 and cuDNN v6.

**Comment by denizyuret** [comment]
There is a problem with CFLAGS in the Makefile with 1080Ti in Knet 0.8.3.
To see if this is the problem in your case please remove "-arch=compute_30
-code=sm_30" from Knet/src/Makefile and do a "make clean; make" under src
followed by Pkg.build("Knet") in Julia.

**Comment by kadir-gunel** [comment]
I tried but it did not work. Still getting -1 .

**Comment by denizyuret** [comment]
It seems Julia/Knet is not recognizing your GPU.  Try the following to
determine the problem:

Knet.gpu()
Knet.gpuCount()
Knet.nvmlDeviceGetMemoryInfo(0)
include(Knet.dir("test/gpu.jl"))

Please copy the output from these commands in your response.

**Comment by kadir-gunel** [comment]
`> julia> Knet.gpu()`
`-1`

`julia> Knet.gpuCount()`
`0`

`julia> Knet.nvmlDeviceGetMemoryInfo(0)`
` `
`julia> include(Knet.dir("test/gpu.jl"))`  First asks me to install Combinatorics package. After installing that package, it returns nothing ; like in the previous command.

**Comment by denizyuret** [comment]
It seems Knet cannot find some NVIDIA libraries, in particular
libnvidia-ml.so.  If you can solve this problem (e.g. by defining some
environment variables etc.) things should work after a Pkg.build("Knet").
To test whether a library is visible to julia try:

julia> Libdl.find_library(["libnvidia-ml"], [])

This should return a string if the library can be found. Unfortunately I do
not have a mac with nvidia installed, so I am not sure what the correct
path is.

deniz

**Comment by kadir-gunel** [comment]
Hello,
I think I found out the problem.  As you mentioned I tried to find the location of the libnvidia-ml. And it turns out that the nvidia drivers do not come with this library to macs.  Due to that I can't create KnetArray.

**Comment by denizyuret** [comment]
That is odd. NVML is used by basic utilities such as nvidia-smi.  Here is
the website:

https://developer.nvidia.com/nvidia-management-library-nvml

**Comment by kadir-gunel** [comment]
Instead, there is : https://github.com/phvu/cuda-smi

**Comment by kadir-gunel** [comment]
Before closing this issue, I was curious about something. Could it be possible to use Arrayfire.jl for creating GPU arrays and use Knet library ? 
I am asking this because I still could not find a solution for my machine other than formatting and installing ubuntu.
And lastly, with the new version of Os X (High Sierra) egpu support is coming. Do you have plans to make it work for macs with gpus ?

**Comment by kadir-gunel** [comment]
Answer to my first question is no. Knet expects KnetArray for activation functions and probably for autograd too. 
Hope KnetArray will be available for all platforms.

**Comment by denizyuret** [comment]
1. You can work with Knet without using KnetArrays on the CPU (i.e. just use regular Julia Arrays).

2. The nvidia-ml library is only used to probe for the gpu's on the system, it is not essential.  We can probably write a patch that will use other nvidia libs if nvidia-ml not found.  Reopening the issue as a reminder.

**Comment by denizyuret** [comment]
I made the nvidia-ml dependency optional in the latest master, but I can't test it without a Mac that has a GPU.  Somebody please test and close this if it works.  (You can get the latest master using Pkg.checkout("Knet")).

**Comment by kadir-gunel** [comment]
It works now.
Thank you.
