### ISSUE TITLE
Tutorial syntax

### ISSUE THREAD

**Issue by rand5** [denizyuret/Knet.jl#142]
I was following the first MNIST example on the homepage, but ran into the following error when executing
```
using MNIST: xtrn, ytrn, xtst, ytst, minibatch
```
```
UndefVarError: xtrn not defined
```
I am wondering if maybe the syntax changed since this was originally written.

**Comment by ereday** [comment]
Hi,
Please run the `MNIST.loaddata()` before `using MNIST: xtrn, ytrn, xtst, ytst, minibatch`
So, for the example in homepage you can go with the following snippet:

```
using Knet
include(Knet.dir("examples","mnist.jl"))
MNIST.loaddata()
using MNIST: xtrn, ytrn, xtst, ytst, minibatch
dtrn = minibatch(xtrn, ytrn, 100)
dtst = minibatch(xtst, ytst, 100)
```

**Comment by denizyuret** [comment]
This has been fixed in the tutorial / readme in the latest release.
