### ISSUE TITLE
Convolution Conjugate?

### ISSUE THREAD

**Issue by AStupidBear** [denizyuret/Knet.jl#148]
Convolution conjugate (or fractional conjugate) is used in recurrent CNN. Is this operation supported in Knet?

**Comment by denizyuret** [comment]
Does cudnn support it?  If so it should be easy to integrate.

**Comment by AStupidBear** [comment]
I think that operation is called deconv4 in Knet. But I don't know how to use it/

```julia
using Knet
x = rand(10, 10, 3, 2)
w = rand(5, 5, 3, 4)
y = conv4(w, x)
wy = rand(5, 5, 4, 3)
deconv4(w, y)
deconv4(wy, y)
```
gave me  an error

**Comment by AStupidBear** [comment]
I modified the source code

```julia
function Knet.dcdims(w,x; transpose = false, padding=0, stride=1, o...)
    N = ndims(x)
    ntuple(N) do i
        if i < N-1
            pi = (if isa(padding,Number); padding; else padding[i]; end)
            si = (if isa(stride,Number); stride; else stride[i]; end)
            si*(size(x,i)-1) + size(w,i) - 2*pi
        elseif i == N-1
            transpose ? size(w, N - 1) : size(w,N)
        else
            size(x,N)
        end
    end
end

function Knet.deconv4(w,x; o...)
    y = similar(x,Knet.dcdims(w,x; transpose = true, o...))
    return Knet.conv4x(w,y,x;o...)
end

using Knet
x = rand(10, 10, 3, 2)
w = rand(5, 5, 3, 4)
y = conv4(w, x)
deconv4(w, y)
```

and now there's no error

**Comment by AStupidBear** [comment]
However, that's still not exactly the formal convolution conjugate/transpose. See [here](https://i.stack.imgur.com/GlqLM.png) and https://datascience.stackexchange.com/questions/6107/what-are-deconvolutional-layers

**Comment by AStupidBear** [comment]
Like deconvolution, convolution conjugate/transpose is not directly supported in CUDNN.

**Comment by denizyuret** [comment]
@AStupidBear, PR #233 in the latest master by @ilkerkesen fixed the deconvolution implementation, could one of you test this and close this issue if everything works?
