### ISSUE TITLE
Use GPUArray / KnetArray

### ISSUE THREAD

**Issue by davidbp** [denizyuret/Knet.jl#150]
Hello,

I really like the library, but, as in most deep learning toolkits, I  miss  non Nvidia GPU arrays.

Would it be feasible to use another type of array in Knet? For example GPUArray (https://github.com/JuliaGPU/GPUArrays.jl) types.

It would be nice to have an standard for "GPUArray" in julia and it would be even nicer if we could use it in AMD and Nvidia devices.

**Comment by ilkerkesen** [comment]
See my issues in GPUArrays issue tracker,

[https://github.com/JuliaGPU/GPUArrays.jl/issues/created_by/ilkerkesen](https://github.com/JuliaGPU/GPUArrays.jl/issues/created_by/ilkerkesen)

**Comment by davidbp** [comment]
I've seen them, does that mean are you trying to make it possible in knet?
In that case I would be thrilled to help, if I can.

**Comment by denizyuret** [comment]
That would be great David!  GPUArrays is developed by @SimonDanisch and we
are collaborating. As soon as we have some of Ilker's issues resolved it
should be possible to use GPUArrays in Knet.

**Comment by SimonDanisch** [comment]
Those issues should be solved on master, see https://github.com/JuliaGPU/GPUArrays.jl/pull/37 :)

**Comment by denizyuret** [comment]
At this point we need to make sure that GPUArrays by @SimonDanisch and CuArrays by @MikeInnes pass the unit tests under Knet/test and can run the examples under Knet/examples. I created two Knet branches (named GPUArrays and CuArrays) for this purpose where the KnetArray related code is commented out and KnetArray is defined to be GPUArray or CuArray. My first attempts did not pass many of the tests with CuArray or GPUArray. Please feel free to use these branches as test beds for the different array types and let's fix/implement the broken/missing array ops.

David, it would be great if you have the time to run Knet unit tests on GPUArray and CuArray and report the broken functionality to the respective package owners.

**Comment by SimonDanisch** [comment]
I tried to make CLArrays pass! [7000](https://github.com/JuliaGPU/CLArrays.jl) tests pass now, but would need some help with the remaining tests -
 they only fail and I'd need deeper knowledge of the code to correct those!
Everything but CLArrays itself should be tagged by now, so you need to clone it. I'll see if I can register it today!

**Comment by SimonDanisch** [comment]
See #168

**Comment by denizyuret** [comment]
Oh no!  Yet another array type?

**Comment by SimonDanisch** [comment]
That's what we discussed in Boston! Now it's only CLArrays and CuArrays, using the same abstract interface and inheriting from GPUArrays. See https://github.com/JuliaGPU/GPUArrays.jl/pull/64 & [the (unfinished) docs](https://juliagpu.github.io/GPUArrays.jl/latest/)
. So it's actually less array types after all and you can freely swap them out ;)

**Comment by SimonDanisch** [comment]
So can we expect any help for passing the last tests?

**Comment by denizyuret** [comment]
Which branch of CLArrays and which version of the tests were you using?
 i.e. if you help replicate your setup we can help.

**Comment by SimonDanisch** [comment]
I'm tagging CLArrays + CLBLAS right now, so you need to check out those. So that's:
```julia
Pkg.add("CLBLAS")
Pkg.checkout("CLBLAS")
Pkg.add("CLArrays")
Pkg.checkout("CLArrays")
Pkg.build("CLArrays")
```
Then you need:
https://github.com/denizyuret/Knet.jl/pull/168

I just tried this on a fresh computer and found a couple of regressions and improvements.
I will have a look at it!

**Comment by denizyuret** [comment]
And how do I run the unit tests?  Should I just replace KnetArray with
CLArray and try the original tests under Knet?

**Comment by SimonDanisch** [comment]
I think on that branch it's just pkg test... but I've mainly just evaled the runtests file in atom ;)

**Comment by denizyuret** [comment]
CuArrays fully supported in 1.4.0.
