### ISSUE TITLE
Creation of dynamic graphs for NLP

### ISSUE THREAD

**Issue by kadir-gunel** [denizyuret/Knet.jl#162]
I want to implement a variant of RNN (say Vanilla RNN or GRU) for language modeling. And one thing that I notice is that in order to do batching for different sentence lengths I have to use either padding or bucketing which is a special trick that is used by specially for static graph "creators" tools like tensorflow, theano, etc.

On the other hand, if I misunderstood please correct me, one of Knet's philosophy is creation of dynamic graphs in order to eliminate such issues.

So my question is how? If I implement a RNN, and put each sentence with different lengths in a batch can Knet automagically handle this? Or do I have to also implement this special batching mechanism ?

B.R.

**Comment by kirnap** [comment]
The basic answer is that you need to implement batching mechanism by yourself. The details of implementation depends on a need. Let's say you have seq2seq encoder-decoder model, then you have two candidate minibatches one in encoder side and another in decoder side.

In the encoder side, you have to do the padding from the beginning of a sentence (to have fast runnig code). For example, if you have 2 sentences of length 2 and 4, then the first two word of the short sentence is special padding character and corresponding mask is zero. Finally you need to multiply that mask with your lstm state as I provide in that [link](https://github.com/kirnap/ku-dependency-parser/blob/master/lm/lm_model.jl#L26)

In the decoder side, you should not get any error for padding characters meaning that padded character has no contribution to loss value as I provide in that [link](https://github.com/kirnap/ku-dependency-parser/blob/9c1fed0f44a3f9773b31e378912a67c8a41f3a29/parser/modelutils.jl#L195)

**Comment by ozanarkancan** [comment]
Hi,

Knet does not create a computational graph for each instance in a batch. It creates a cg for the expressions in the batch form. What you described is called as auto-batching. Knet does not have the auto-batching feature yet. You may try to split & merge your intermediate results in order to compute individual subgraphs.
