### ISSUE TITLE
Policy Gradient Reinforcement Learning with Knet

### ISSUE THREAD

**Issue by etotheipluspi** [denizyuret/Knet.jl#18]
I'm trying to implement a policy gradient method using Knet. To do this, I need to multiply the loss gradients from by a scalar before doing backprop on the rest of the net. Is there a recommended way to do that through the Knet API? If there is a way to run a part of the computational graph that would do the job as well.

**Comment by rejuvyesh** [comment]
Is `gscale` in `update!` not enough?

**Comment by etotheipluspi** [comment]
That should work thanks!
