### ISSUE TITLE
Pooling bug

### ISSUE THREAD

**Issue by cemgultekin** [denizyuret/Knet.jl#182]
Merhaba,
AWS'de kullandığım bilgisayarda benzer pool örnekleri için aşağıdaki gibi sonuçlar alıyorum:

julia> x=KnetArray(randn(50,1,1,200));

julia> y=pool(x,window=[9,1],padding=[10,0]);

julia> maximum(abs(x))
3.61540001065606

julia> maximum(abs(y))
1.7976931348623157e308

**Comment by ilkerkesen** [comment]
Could you please make it without abs? When you perform maximum pooling, you eliminate most of the negative values and I strongly believe that 3.6154 comes from a negative value in array x.

**Comment by cemgultekin** [comment]
Here is a smaller result for demonstration. In y there are huge values which are incorrect. I was constantly taking Inf32 outputs in CNNs.
julia> x=KnetArray(randn(Float32,3,1,1,2));

julia> y=pool(x,window=[3,1],padding=[4,0]);

julia> x
3×1×1×2 Knet.KnetArray{Float32,4}:
[:, :, 1, 1] =
 -0.310875
  0.330121
 -0.351972

[:, :, 1, 2] =
 -0.720901 
 -0.922792 
 -0.0962182

julia> y
3×1×1×2 Knet.KnetArray{Float32,4}:
[:, :, 1, 1] =
 -3.40282f38
  0.330121  
 -0.351972  

[:, :, 1, 2] =
 -3.40282f38
 -0.720901  
 -0.0962182

**Comment by denizyuret** [comment]
Your padding size is larger than your window size.  Therefore the maximum of the values lying outside your data window are defined (by CUDNN) as -Inf, which is -3.40282f38 for Float32 and -1.7976931348623157e308 for Float64. I think this is CUDNN's default behavior and there is no bug.
