### ISSUE TITLE
CUDA kernel build issue

### ISSUE THREAD

**Issue by philtomson** [denizyuret/Knet.jl#187]
There possibly needs to be some Makefile tweakage:

> julia> Pkg.add("Knet")
> INFO: Cloning cache of AutoGrad from https://github.com/denizyuret/AutoGrad.jl.git
> INFO: Cloning cache of Knet from https://github.com/denizyuret/Knet.jl.git
> INFO: Installing AutoGrad v0.0.9
> INFO: Installing Knet v0.8.5
> INFO: Building Knet
> INFO: Compiling CUDA kernels.
> julia cuda1.jl > cuda1.cu
> nvcc -c -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-options "-O3 -Wall -fPIC -fopenmp" cuda1.cu -o cuda1.o
> ERROR: No supported gcc/g++ host compiler found, but clang-3.8 is available.
>        Use 'nvcc -ccbin clang-3.8' to use that instead.
> Makefile:21: recipe for target 'cuda1.o' failed
> make: *** [cuda1.o] Error 1

Ok, so I went into the Makefile at ~/.julia/v0.6/Knet/src/Makefile and changed CFLAGS to add the -ccbin clang-3.8 (as it seemed to suggest):

CFLAGS := **-ccbin clang-3.8** -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-options "$(CFLAGS)"

Then:

> julia> Pkg.build("Knet")
> INFO: Building Knet
> INFO: Compiling CUDA kernels.
> nvcc -c -ccbin clang-3.8 -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-options "-O3 -Wall -fPIC -fopenmp" cuda1.cu -o cuda1.o
> ...
> nvcc -c -ccbin clang-3.8 -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-options "-O3 -Wall -fPIC -fopenmp" conv.cpp -o conv.o
> In file included from conv.cpp:6:
> In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/algorithm:62:
> In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/bits/stl_algo.h:59:
> In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/cstdlib:77:
> /usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/bits/std_abs.h:101:3: error: 
>       unknown type name '__float128'
>   __float128
>   ^
> /usr/bin/../lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/bits/std_abs.h:102:7: error: 
>       unknown type name '__float128'
>   abs(__float128 __x)

I tried -ccbin clang-4.0 with no success and finally ended up changing to -ccbin gcc-7

And that worked. 

This was with Julia Version 0.6.2-pre.0 on Ubuntu 17.10 with CUDA 8.

**Comment by denizyuret** [comment]
The latest master uses CUDAdrv and CUDAapi to discover the compiler tools if they are installed. Can you Pkg.add these and try to rebuild Knet to see if this solves your setup?

**Comment by philtomson** [comment]
Seems to work for me now when I did a rebuild of Knet.
