### ISSUE TITLE
Build arbitrary graph in Knet?

### ISSUE THREAD

**Issue by AStupidBear** [denizyuret/Knet.jl#19]
In Mocha.jl, I can build arbitrary graph using ```Concat Layer``` and ```Split Layer``` like this [issue](https://github.com/pluskid/Mocha.jl/issues/204). How can I implement this in Knet?

**Comment by denizyuret** [comment]
Knet8 supports models implemented in regular Julia, including array indexing and concatenation commands which should take care of this issue.  Please reopen if you have further problems.
