### ISSUE TITLE
Feature request: view of KnetArray

### ISSUE THREAD

**Issue by ngphuoc** [denizyuret/Knet.jl#201]
This is useful in when we need to pack multiple matrices for speed or update sub-matrices without slicing. I may run faster. Applications are situations like in the lstm function https://github.com/denizyuret/Knet.jl/blob/master/examples/rnnlm/rnnlm.jl

**Comment by denizyuret** [comment]
Contiguous slices of KnetArrays are already implemented as views. We should
clarify this if not clear in docs.

**Comment by ngphuoc** [comment]
Thanks! I've just check that continuous array ranges are indeed implemented as view, but not the non-contiguous one.  The docs says "(ii) array ranges (e.g. a[:,3:5]) are handled as views with shared pointers instead of copies when possible" but does not mention contiguous or not. Yes, please mention it in the docs.
