### ISSUE TITLE
Allow non-zero dropout in test time

### ISSUE THREAD

**Issue by ilkerkesen** [denizyuret/Knet.jl#204]
Here's the reference,

[https://github.com/soumith/ganhacks#17-use-dropouts-in-g-in-both-train-and-test-phase](https://github.com/soumith/ganhacks#17-use-dropouts-in-g-in-both-train-and-test-phase)

I don't know if there are another papers.

**Comment by denizyuret** [comment]
Would it be ok if we had a keyword argument (e.g. force) that people can
use to change the default behavior?

**Comment by ilkerkesen** [comment]
Yes, it's OK by me.

**Comment by denizyuret** [comment]
Hmm, I just looked at @doc dropout, it seems it already does what you want:

"""

    dropout(x, p)



Given an array `x` and probability `0<=p<=1`, just return `x` if

testing, return an array `y` in which each element is 0 with

probability `p` or `x[i]/(1-p)` with probability `1-p` if training.

Training mode is detected automatically based on the type of `x`,

which is `AutoGrad.Rec` during gradient calculation.  Use the keyword

argument `training::Bool` to change the default mode and

`seed::Number` to set the random number seed for reproducible

results. See [(Srivastava et al. 2014)](
http://jmlr.org/papers/v15/srivastava14a.html)
for a reference.



"""
