### ISSUE TITLE
Problems with Knet on Macbook Pro

### ISSUE THREAD

**Issue by jeffreylu9** [denizyuret/Knet.jl#207]
It seems that Knet can't find the GPU on my Macbook Pro. Specifically, I get the following error when trying to use the KnetArray{Float32} type:

ERROR: LoadError: KnetPtr: bad device id -1.

I looked at issue #138 but couldn't resolve my problem. Any tips?

**Comment by denizyuret** [comment]
What version of Knet are you using?  The latest master version may have
fixed the problem: you can try it using Pkg.checkout("Knet");
Pkg.build("Knet").  If this works, it will make it into the next release
which is going to be released within a week.

Do you have CUDA etc. installed and in your library PATH?  You can try the
following for diagnosis:

- Knet.gpuCount()
- Libdl.find_library(["libcudart"],[])

**Comment by jeffreylu9** [comment]
The first command results in 0 and the second command returns an empty string. On a Mac, what CUDA libraries is Knet looking for, and how can I make sure they are installed properly?

**Comment by denizyuret** [comment]
Make sure the correct NVIDIA driver
<http://www.nvidia.com/Download/index.aspx>, CUDA toolkit
<https://developer.nvidia.com/cuda-downloads> and CUDNN library
<https://developer.nvidia.com/cudnn> has been downloaded and installed.
Make sure you can compile and run the sample code included in the CUDA
toolkit.

**Comment by jeffreylu9** [comment]
I checked my CUDA installation and ran the sample deviceQuery code with the following output: 

./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "GeForce GT 750M"
  CUDA Driver Version / Runtime Version          9.0 / 9.0
  CUDA Capability Major/Minor version number:    3.0
  Total amount of global memory:                 2048 MBytes (2147024896 bytes)
  ( 2) Multiprocessors, (192) CUDA Cores/MP:     384 CUDA Cores
  GPU Max Clock rate:                            926 MHz (0.93 GHz)
  Memory Clock rate:                             2508 Mhz
  Memory Bus Width:                              128-bit
  L2 Cache Size:                                 262144 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(65536), 2D=(65536, 65536), 3D=(4096, 4096, 4096)
  Maximum Layered 1D Texture Size, (num) layers  1D=(16384), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(16384, 16384), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 1 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Supports Cooperative Kernel Launch:            No
  Supports MultiDevice Co-op Kernel Launch:      No
  Device PCI Domain ID / Bus ID / location ID:   0 / 1 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 9.0, CUDA Runtime Version = 9.0, NumDevs = 1
Result = PASS

I also reran the Knet commands. gpuCount() still gives 0, but now the libcudart library is able to be found.

**Comment by denizyuret** [comment]
What is the result of the following:
```
using Knet: @cuda
p=Cuint[0]
@cuda(cudart,cudaGetDeviceCount,(Ptr{Cuint},),p)
Int(p[1])
```

**Comment by jeffreylu9** [comment]
I get the following: 

julia> using Knet: @cuda

julia> p = Cuint[0]
1-element Array{UInt32,1}:
 0x00000000

julia> @cuda(cudart,cudaGetDeviceCount,(Ptr{Cuint},),p)

julia> Int(p[1])
1

**Comment by denizyuret** [comment]
Ok. This is what gpuCount is supposed to do.  Make sure you have the latest
master with Pkg.checkout("Knet") and Pkg.build("Knet").  The code is in
.julia/v0.6/Knet/src/gpu.jl

**Comment by jeffreylu9** [comment]
Now Knet is complaining about how it can't find libnvidia-ml:
```
ERROR: LoadError: Cannot find libnvidia-ml, please install it and rerun Pkg.build("Knet").
Stacktrace:
 [1] nvmlDeviceGetMemoryInfo(::Int64) at /Users/Jeffrey/.julia/v0.6/Knet/src/gpu.jl:189
 [2] perfChoose(::Array{Knet.cudnnConvolutionFwdAlgoPerf_t,1}, ::Int32) at /Users/Mousie/.julia/v0.6/Knet/src/conv.jl:637
 [3] #conv4_algo#322(::Ptr{Void}, ::Array{Any,1}, ::Function, ::Knet.KnetArray{Float32,4}, ::Knet.KnetArray{Float32,4}, ::Knet.KnetArray{Float32,4}) at /Users/Jeffrey/.julia/v0.6/Knet/src/conv.jl:584
...
```
I think the issue is with a call to gpufree() on line 637 of conv.jl, which is equivalent to calling  nvmlDeviceGetMemoryInfo(), which fails because the library isn't installed. It seems like this needs to be addressed similarly to #138?

**Comment by denizyuret** [comment]
Oh, another sneaky nvml call.  I pushed a fix to master, can you try again
after updating?

**Comment by jeffreylu9** [comment]
Yup, it works now. Thanks for the help and quick replies!

**Comment by denizyuret** [comment]
Thanks for testing on the mac!
