### ISSUE TITLE
vae demo pyplot dependency

### ISSUE THREAD

**Issue by denizyuret** [denizyuret/Knet.jl#225]
I keep getting errors in PyPlot install in the VAE demo: https://gist.github.com/denizyuret/bb7493305af63d07eb4473e8593a0231 
Do we have to use PyPlot?  I'd much rather use a non-python package if possible. At some point I fiddled with it a bit and managed to install it, is there a more foolproof out-of-the-box way I don't know about?

**Comment by ilkerkesen** [comment]
OK, I'll look for what I can do, I think Images pkg will be adequate to do this.
