### ISSUE TITLE
function add_32_12 in library not found

### ISSUE THREAD

**Issue by ppalmes** [denizyuret/Knet.jl#23]
Architecture:          ppc64le
Byte Order:            Little Endian
CPU(s):                184
On-line CPU(s) list:   0-151,160-191
Thread(s) per core:    8
Core(s) per socket:    5
Socket(s):             4
NUMA node(s):          4
Model:                 8247-42L
CPU max MHz:           3923.0000

Machine:

Architecture:          ppc64le
Byte Order:            Little Endian
CPU(s):                184
On-line CPU(s) list:   0-151,160-191
Thread(s) per core:    8
Core(s) per socket:    5
Socket(s):             4
NUMA node(s):          4

I got this error after this command:
julia charlm.jl --data 100.txt --epochs 10 --winit 0.3 --save shakespeare.jld

ERROR: LoadError: ccall: could not find function add_32_12 in library 
 in .+(::Knet.KnetArray{Float32,2}, ::Knet.KnetArray{Float32,2}) at /localhome/paulito/.julia/v0.6/Knet/src/cuda12.jl:69
 in lstm(::Knet.KnetArray{Float32,2}, ::Knet.KnetArray{Float32,2}, ::Knet.KnetArray{Float32,2}, ::Knet.KnetArray{Float32,2}, ::Knet.KnetArray{Float32,2}) at /localhome/paulito/.julia/v0.6/Knet/examples/charlm.jl:137
 in predict(::Array{Any,1}, ::Array{Any,1}, ::Knet.KnetArray{Float32,2}) at /localhome/paulito/.julia/v0.6/Knet/examples/charlm.jl:156
 in loss(::Array{Any,1}, ::Array{Any,1}, ::Array{BitArray{2},1}, ::UnitRange{Int64}) at /localhome/paulito/.julia/v0.6/Knet/examples/charlm.jl:169
 in map(::CharLM.##15#19{Array{Any,1},Array{Any,1}}, ::Array{Any,1}) at ./essentials.jl:124
 in macro expansion at ./util.jl:184 [inlined]
 in train!(::Array{Any,1}, ::Array{Any,1}, ::Dict{Char,Int64}, ::Dict{Symbol,Any}) at /localhome/paulito/.julia/v0.6/Knet/examples/charlm.jl:222
 in main(::Array{String,1}) at /localhome/paulito/.julia/v0.6/Knet/examples/charlm.jl:95
 in include_from_node1(::String) at ./loading.jl:481
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
while loading /localhome/paulito/.julia/v0.6/Knet/examples/charlm.jl, in expression starting on line 301

**Comment by denizyuret** [comment]
Can you try Pkg.update() and Pkg.build("Knet")?  Let me know if this does
not fix it.

**Comment by denizyuret** [comment]
It seems in mnist it is trying to multiply an Array and a KnetArray. Try
converting both weights and data to KnetArrays.

**Comment by denizyuret** [comment]
About the library not found issue: try going to Knet/src, run "make clean"
and "make" manually to recompile libknet8. Then make sure it is seen in
julia by checking the value of Knet.libknet8. If that is an empty string
not good... If it is the right path but some functions are not found we
have another problem. I have not tested on ppc and julia6, so I'd be
interested in debugging this.

**Comment by ppalmes** [comment]
I'm just running the included examples. It seems I'm missing cetain
libraries? I'm running Julia Version 0.6.0-dev.439.

Do you think because of the Julia version?

Housing.main("--epochs 10")
housing.jl (c) Deniz Yuret, 2016. Linear regression model for the Housing
dataset from the UCI Machine Learning
Repository.
opts=(:seed,-1)(:epochs,10)(:lr,0.1)(:atype,"KnetArray")(:test,0.0)(:gcheck,0)(:fast,false)
INFO: Downloading
https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data
to /localhome/paulito/.julia/v0.6/Knet/src/../data/housing.data
  % Total    % Received % Xferd  Average Speed   Time    Time     Time
 Current
                                 Dload  Upload   Total   Spent    Left
 Speed
100 49082  100 49082    0     0  87664      0 --:--:-- --:--:-- --:--:--
87803
size(data) = (14,506)
ERROR: ccall: could not find function add_64_01 in library
 in .+(::Float64, ::Knet.KnetArray{Float64,2}) at
/localhome/paulito/.julia/v0.6/Knet/src/cuda01.jl:95
 in .+(::Knet.KnetArray{Float64,2}, ::Int64) at
/localhome/paulito/.julia/v0.6/Knet/src/cuda01.jl:48
 in main(::String) at
/localhome/paulito/.julia/v0.6/Knet/examples/housing.jl:43

**Comment by ppalmes** [comment]
Yes, I manually compiled the src with no issues. I can see the
*libknet8.so *but Knet.libknet8 is ""

**Comment by ppalmes** [comment]
I recompiled manually the Knet/src and deleted the Knet.ji... Now,
Knet.libknet8 has proper path. It seems that the code should check if
Knet.libknet8 is empty and delete Knet.ji to recompile it?

**Comment by ppalmes** [comment]
After manually compiling Knet and deleting Knet.ji, runexamples.jl in ppc
works except for verbose warnings in some of the tests.

**Comment by denizyuret** [comment]
Ah, it was a corrupt Knet.ji file!  I thought I added a command to
regenerate it in the build script, so Pkg.build("Knet") should have
resolved it, but maybe this doesn't work in Julia 0.6.   I will test
further...
