### ISSUE TITLE
Pkg.build("CUDAdrv") fails on Windows 10 with Pkg.build("Knet") 

### ISSUE THREAD

**Issue by finmod** [denizyuret/Knet.jl#230]
Can you please point me in the right direction to resolve this set up problem of Knet.jl on Windows 10? 

Pkg.build("Knet") gives: 

  | | |_| | | | (_| |  |  Version 0.6.1 (2017-10-24 22:15 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> Pkg.build("Knet")
INFO: Building Knet
WARNING: Method definition colon(Base.VersionNumber, Base.VersionNumber) in module CUDAapi2 at C:\Users\Denis\.julia\v0.6\Knet\deps\compatibility.jl:22 overwritten in module CUDAapi at C:\Users\Denis\.julia\v0.6\CUDAapi\src\compatibility.jl:20.
WARNING: CUDAdrv.jl has not been successfully built, and will not work properly.
WARNING: Please run Pkg.build("CUDAdrv") and restart Julia.
WARNING: CUDAdrv failed with ErrorException("CUDAdrv.jl has not been configured.")
INFO: Compiling Knet cache.

julia>

Whereas Pkg.build("CUDAdrv") gives:

julia> Pkg.build("CUDAdrv")
INFO: Building CUDAdrv
===============================[ ERROR: CUDAdrv ]===============================

LoadError: Could not find CUDA driver
while loading C:\Users\Denis\.julia\v0.6\CUDAdrv\deps\build.jl, in expression starting on line 104

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: CUDAdrv had build errors.

 - packages with build errors remain installed in C:\Users\Denis\.julia\v0.6
 - build the package(s) and all dependencies with `Pkg.build("CUDAdrv")`
 - build a single package by running its `deps/build.jl` script

================================================================================

julia>

On the Windows side, deviceQuery gives:

C:\ProgramData\NVIDIA Corporation\CUDA Samples\v9.0\bin\win64\Release>deviceQuery
deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "Quadro K1100M"
  CUDA Driver Version / Runtime Version          9.0 / 9.0
  CUDA Capability Major/Minor version number:    3.0
  Total amount of global memory:                 2048 MBytes (2147483648 bytes)
  ( 2) Multiprocessors, (192) CUDA Cores/MP:     384 CUDA Cores
  GPU Max Clock rate:                            706 MHz (0.71 GHz)
  Memory Clock rate:                             1400 Mhz
  Memory Bus Width:                              128-bit
  L2 Cache Size:                                 262144 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(65536), 2D=(65536, 65536), 3D=(4096, 4096, 4096)
  Maximum Layered 1D Texture Size, (num) layers  1D=(16384), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(16384, 16384), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 1 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  CUDA Device Driver Mode (TCC or WDDM):         WDDM (Windows Display Driver Model)
  Device supports Unified Addressing (UVA):      Yes
  Supports Cooperative Kernel Launch:            No
  Supports MultiDevice Co-op Kernel Launch:      No
  Device PCI Domain ID / Bus ID / location ID:   0 / 2 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 9.0, CUDA Runtime Version = 9.0, NumDevs = 1
Result = PASS

C:\ProgramData\NVIDIA Corporation\CUDA Samples\v9.0\bin\win64\Release>

**Comment by denizyuret** [comment]
1. Make sure you have the latest Knet: Pkg.update(); Pkg.checkout("Knet")
2. Try Pkg.rm("CUDAdrv"); Pkg.rm("CUDAapi") -- seems to be causing issues
and they are not required.
3. Make sure you have Visual Studio with C++ support installed.
4. Make sure you have the latest CUDA toolkit installed.
5. Make sure you have the latest cuDNN installed.
6. Try Pkg.build("Knet") again.

**Comment by finmod** [comment]
Spot on. 
You should give these commands in the install section of the README to avoid being side-tracked by CUDAdrv and CUDAapi instructions which appear in other notebooks. 
Installing CuDNN is simple by following instructions from NVIDIA and copying libraries into the designated folders.

Testing the knet-tutorial notebook, I obtain the same order of magnitude for @time except for CNN model where I get:

@time cnnmodels = [ copy(train!(wcnn, dtrn)) for epoch=1:60 ]; # ~127 seconds
5666.771553 seconds (110.96 M allocations: 1.463 TiB, 6.28% gc time)

Is this due to my weak hardware, a Dell Precision M3800 with NVIDIA Quadro K1100M or is there something still not right in the setup?

**Comment by denizyuret** [comment]
What is the timing in other cnn examples like examples/lenet or
examples/DeepLearningFrameworks? Are you sure your data/model are using
KnetArrays rather than cpu Arrays? Is Knet.gpu() returning >= 0, detecting
your hardware?

**Comment by finmod** [comment]
Knet.gpu() returns -1. The output of deviceQuery is given above and banwidthTest is:

C:\ProgramData\NVIDIA Corporation\CUDA Samples\v9.0\bin\win64\Release>bandwidthTest
[CUDA Bandwidth Test] - Starting...
Running on...

 Device 0: Quadro K1100M
 Quick Mode

 Host to Device Bandwidth, 1 Device(s)
 PINNED Memory Transfers
   Transfer Size (Bytes)        Bandwidth(MB/s)
   33554432                     9671.7

 Device to Host Bandwidth, 1 Device(s)
 PINNED Memory Transfers
   Transfer Size (Bytes)        Bandwidth(MB/s)
   33554432                     9628.5

 Device to Device Bandwidth, 1 Device(s)
 PINNED Memory Transfers
   Transfer Size (Bytes)        Bandwidth(MB/s)
   33554432                     32242.3

Result = PASS

NOTE: The CUDA Samples are not meant for performance measurements. Results may vary when GPU Boost is enabled.

C:\ProgramData\NVIDIA Corporation\CUDA Samples\v9.0\bin\win64\Release>

**Comment by denizyuret** [comment]
OK, this means Knet is not able to see your GPU.  Try uninstalling CUDAapi,
CUDAdrv, remove ~/.julia/lib/v0.6/Knet.ji and rebuild Knet using
Pkg.build("Knet").  After "using Knet" if everything is working you should
see "gpu() => 0".

**Comment by finmod** [comment]
Implementing these steps I still get Knet.gpu() => -1. Julia does not find CUDA whereas Windows confirms that it is there and working.

The indications coming from Windows are that Knet.jl does not find the correct Windows folders. Both deviceQuery at C:\ProgramData\NVIDIA Corporation\CUDA Samples\v9.0\bin\win64\Release and C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin give the same GPU device but the two folders do not have the same libraries in there. In paricular, cudnn is in here: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin and not in Program Data. This is because NVIDIA told me to put cudnn files in Program Files.

In addition, the CUDA path in the system environment variables is: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0. In which Windows folder do you try to find the cuda.lib, cuda1, nvml, cudadnn and others for Knet.jl to build?

Hope this helps.

**Comment by denizyuret** [comment]
These seem to be the correct locations. What does Pkg.build("Knet") output?
It needs Visual Studio with C++ to compile its kernels. Some VS versions
are incompatible with some cuda versions etc.

**Comment by finmod** [comment]
I give up for now. Some indications on which fail-safe [CUDA-Visual Studio] combination on Windows 10 are required from NVIDIA to improve the dissemination of the technique. This is to avoid days of install/reinstall/build trials leading consistently to failure.

**Comment by denizyuret** [comment]
The latest cuda does not work with the latest vs 2017. I used VS 2015.
There is a working Amazon AMI if you'd like to take a look.

**Comment by finmod** [comment]
Thank you for mentioning Amazon AMI. For now, I will investigate Knet on JuliaPro with MKL to quantify potential improvement with respect to standard Julia 0.6.2 and excluding Knet.gpu(). 

Let me return to my original curiosity in Knet.jl, do you have an example of parameter estimation by MLE labelled as backpropagation in Deep Learning:   https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/pdfs/41%20DeepLearning.pdf ? Should I open this topic as a separate issue?

**Comment by denizyuret** [comment]
Check out the github readme/tutorial, full docs and the examples directory.

**Comment by denizyuret** [comment]
The latest Knet master uses CUDAapi to discover library locations.  Please test on your windows setup if you get a chance: On a fresh Julia, VS and CUDA/CuDNN install just try `Pkg.add("Knet"); using Knet; gpu()`
