### ISSUE TITLE
VGG example broken on MacOS

### ISSUE THREAD

**Issue by denizyuret** [denizyuret/Knet.jl#231]
https://groups.google.com/d/msgid/knet-users/77b71d29-4ed0-45b9-b43b-be83751226dc%40googlegroups.com?utm_medium=email&utm_source=footer 

When I tried, Images tried to load Quartz something or other instead of ImageMagick.  Then it gave a dimension error.  I think this is a problem with Images (if the image is read in different ways by different packages).  If this is the case we should (1) open an issue to Images (or whichever package is responsible), and (2) catch it in vgg or imagenet code and conditionally fix it.

**Comment by denizyuret** [comment]
@kirnap, did we send a bug report to Images.jl?

**Comment by kirnap** [comment]
Yes, you can find it [here](https://github.com/JuliaImages/Images.jl/issues/693)
