### ISSUE TITLE
Use GPUArrays instead of direct cuda implementation

### ISSUE THREAD

**Issue by DennisRutjes** [denizyuret/Knet.jl#239]
**Just a Tip!**
Knet is direct dependent on Cuda libraries, maybe a better option is to depend on the  more Abstract GPU array, the user can choose the backend OpenCL/CUDA. 
Same way as Plots.jl is an abstraction for GR,Gadfly etc.

**_Love Knet though, keep up the good work y'all!_**

**Comment by DennisRutjes** [comment]
Reading in issues duplicate

**Comment by denizyuret** [comment]
Yup. Waiting for other gpu array types to cover more ops and get performant.
