### ISSUE TITLE
KnetArray newbie question

### ISSUE THREAD

**Issue by xukai92** [denizyuret/Knet.jl#243]
What's the difference between

```julia
w = Any[ 0.1f0*randn(Float32,10,784), zeros(Float32,10,1) ]
w = map(KnetArray, w)
```

and

```julia
w = Any[ KnetArray(0.1f0*randn(Float32,10,784)), KnetArray(zeros(Float32,10,1)) ]
```

, of which the 2nd one throws error for a lot of built-in functions about type mis-match

**Comment by denizyuret** [comment]
The first one may end up giving you a KnetArray[] rather than Any[], i.e.
map changes the array type. This may cause a problem with AutoGrad, which
tries to override types of w elements.

**Comment by xukai92** [comment]
I see. Thx!
