### ISSUE TITLE
Dir Denizyuret

### ISSUE THREAD

**Issue by mingtaojia** [denizyuret/Knet.jl#247]
![image](https://user-images.githubusercontent.com/10954535/34437891-4ad4b6b2-ecdd-11e7-909e-1bb469a062af.png)

when i install this package by using Pkg.add("Knet"),it prompted such warnings, did it means that GPU could not be used, and how to solve it,?

**Comment by denizyuret** [comment]
I have tested with Visual Studio 2015 (with c++ support) and CUDA 9.1.

**Comment by denizyuret** [comment]
The latest Knet master uses CUDAapi package for library discovery.  Please test on a fresh install of Julia, VS, CUDA, CuDNN: `Pkg.add("Knet"); Pkg.checkout("Knet"); Pkg.build("Knet"); using Knet; gpu()`.
