### ISSUE TITLE
The control flow of  `dropout` source code maybe wrong 

### ISSUE THREAD

**Issue by wucutin** [denizyuret/Knet.jl#258]
In the `dropout` source code [https://github.com/denizyuret/Knet.jl/blob/ffea2e180f8b605ec19242037434ce6a84693437/src/dropout.jl#L15-L28](url)
![screenshot from 2018-01-15 08-44-37](https://user-images.githubusercontent.com/5056561/34922917-f3df2b5c-f9d0-11e7-8bfe-fc51fa2a505f.png)

there maybe a omit of control flow, based on the principle and the description above the code, it don't work, maybe the follows is better:
```julia
function dropout(x, p; seed = 0, training = false)
          if !training
             x
          else
             if 0<p<1
                if seed !=0;setseed(seed);end
                dropout!(p,x,similar(x))
             elseif p==0
                x
             elseif p==1
                zeros(x)
             else
                error("Dropout probability not in [0:1]: $p")
             end
       end
 end
```

**Comment by CarloLucibello** [comment]
the two codes are equivalent

**Comment by wucutin** [comment]
>the two codes are equivalent
At begining, I thought it's just careless glitch,  because in 0.6.1 in my macbook, the REPL throw some error of control flow before 11days ago. I just test the `dropout` in newest 0.6.2 in Ubuntu, it's OK. 
**Thanks the team and contributors of Knet, it's very excellent framework of deeplearning**
