### ISSUE TITLE
Knet not respecting CUDA_VISIBLE_DEVICES?

### ISSUE THREAD

**Issue by davidavdav** [denizyuret/Knet.jl#259]
Hello, 

I have trouble running Knet under a Slurm resource manager.  I understand that Slurm sets the environment variable `CUDA_VISIBLE_DEVICES` to a list of devices available to the process that is spawned by Slurm.   In a configuration with 2 GPUs per node, I 
 - can run a Knet job (the char-rnn example), when I request Slurm `--gres gpu:2`, resulting in `ENV{"CUDA_VISIBLE_DEVICES"}=="0,1"`, and Knet uses only 1 of the allotted 2 GPUs
 - can *not* run a Knet job, when I request Slurm `--gres gpu:1`, resulting in `ENV{"CUDA_VISIBLE_DEVICES"}=="0"`, with error message
```julia
ERROR: LoadError: KnetPtr: bad device id -1.
Stacktrace:
 [1] Knet.KnetPtr(::Int64) at /home/david/.julia/v0.6/Knet/src/kptr.jl:73
```
In the second case, `Knet.gpuCount() == 2` (which should be 1, because only one GPU is assigned to the Julia process).

**Comment by cangumeli** [comment]
Do you have nvml working properly?  You can check this simply by evaluating `Knet.nvmlfound`. If nvml doesn't exist, regular cuda API is used. This may cause the problem.

**Comment by davidavdav** [comment]
It looks like it is.  

I run the test script `slurm-knet.jl`:
```julia
using Knet

key = "CUDA_VISIBLE_DEVICES"
if key in keys(ENV)
    @show key
    @show ENV[key]
end 
@show Knet.nvmlfound
@show Knet.gpuCount()
```
When I request both gpus:
```bash
srun --gres gpu:2 --pty bash
julia slurm-knet.jl
key = "CUDA_VISIBLE_DEVICES"
ENV[key] = "0,1"
Knet.nvmlfound = true
Knet.gpuCount() = 2
```
When I request 1 gpu (out of two physical gpus)
```bash
srun --gres gpu:1 --pty bash 
julia slurm-knet.jl
key = "CUDA_VISIBLE_DEVICES"
ENV[key] = "0"
Knet.nvmlfound = true
Knet.gpuCount() = 2
```
The last line is not correct, I think.  The gpucount should be 1.

**Comment by denizyuret** [comment]
@ilkerkesen  how did you solve this in our slurm setup?

**Comment by ozanarkancan** [comment]
Hi,

We configured the cgroup in the corresponding configuration files.

slurm.conf:
```
ProctrackType=proctrack/cgroup
TaskPlugin=task/cgroup
```

cgroup.conf:
```
CgroupAutomount=yes 
CgroupReleaseAgentDir="slurm/17.02.4/etc/cgroup" 
AllowedDevicesFile=slurm/17.02.4/etc/cgroup_allowed_devices_file.conf

ConstrainCores=yes 
ConstrainDevices=yes
ConstrainRAMSpace=yes 
ConstrainKmemSpace=yes
ConstrainSwapSpace=no
```
cgroup_allowed_devices_file.conf:
```
/dev/sda*
/dev/cpu/*
/dev/nvidia*
/dev/mem
```

@davidavdav Is your configuration similar?
