### ISSUE TITLE
cudnn.cudnnPoolingForward error 9

### ISSUE THREAD

**Issue by arkynoah** [denizyuret/Knet.jl#261]
I use latest Knet with Julia 0.5.2. Cuda compilation tools, release 8.0, V8.0.44  with cuDNN v7.0.5 (Dec 5, 2017), for CUDA 8.0 Knet passes all test. But I fail at pool function such that

pool(KnetArray{Float32}(ones(3,4,5)))
ERROR: cudnn.cudnnPoolingForward error 9
 in macro expansion at /home/mcyavuz/.julia/v0.5/Knet/src/gpu.jl:13 [inlined]
 in #pool#228(::Ptr{Void}, ::Int64, ::Array{Any,1}, ::Function, ::Knet.KnetArray{Float32,3}) at /home/mcyavuz/.julia/v0.5/Knet/src/conv.jl:129
 in (::Knet.#kw##pool)(::Array{Any,1}, ::Knet.#pool, ::Knet.KnetArray{Float32,3}) at ./<missing>:0

I remove the ~/.julia folder and install Knet again. No hope.
Except pooling I can use Knet in full.

cuDNN also passed the test suggested by cuDNN v7.0.5 Code Samples and User Guide for Ubuntu16.04 (Deb)

**Comment by ilkerkesen** [comment]
Latest Knet (v0.9.0) does not support Julia v0.5. Could you please try it again with Julia v0.6?

**Comment by arkynoah** [comment]
I am at Julia v0.6.
I still get similar errors, I am at CUDA 8.
ERROR: cudnn.cudnnSetPoolingNdDescriptor error 3
Stacktrace:
 [1] macro expansion at /home/mcyavuz/.julia/v0.6/Knet/src/gpu.jl:18 [inlined]
 [2] (::Knet.##call#295#297)(::Int64, ::Int64, ::Int64, ::Int64, ::Int64, ::Type{T} where T, ::Knet.KnetArray{Float32,2}) at /home/mcyavuz/.julia/v0.6/Knet/src/conv.jl:286
 [3] #pool#229(::Ptr{Void}, ::Int64, ::Array{Any,1}, ::Function, ::Knet.KnetArray{Float32,2}) at /home/mcyavuz/.julia/v0.6/Knet/src/conv.jl:126
 [4] pool(::Knet.KnetArray{Float32,2}) at /home/mcyavuz/.julia/v0.6/Knet/src/conv.jl:124

**Comment by ilkerkesen** [comment]
Could you also provide the code snippets that threw those error backtraces?

**Comment by denizyuret** [comment]
cudnn.h says:

CUDNN_STATUS_BAD_PARAM        = 3

So one or more of the parameters in the call are considered bad by the
cudnn library.

**Comment by arkynoah** [comment]
4D Arrays pooling operation is just fine. My problem was with 3D arrays.
not working snippet given above: pool(KnetArray{Float32}(ones(3,4,5)))
working snippet: pool(KnetArray{Float32}(ones(3,3,3,3)))

**Comment by denizyuret** [comment]
Can't you just use 4-D with the 4th D equal to 1?

**Comment by arkynoah** [comment]
Sure that works. Thanks.
