### ISSUE TITLE
ERROR: curand.curandGenerateNormal error 102

### ISSUE THREAD

**Issue by CarloLucibello** [denizyuret/Knet.jl#264]
occasionally when calling `randn!(similar(a)))` when `a` is a KnetArray

**Comment by Sophylax** [comment]
I cannot seem to replicate the error. Could you provide a self-contained snippet that exhibits the problem?

**Comment by denizyuret** [comment]
You may also look at curand.h to see what error 102 is.

**Comment by Sophylax** [comment]
As far as I've gathered it is CURAND_STATUS_ALLOCATION_FAILED. I've tried calling the code with a sufficiently big KnetArray but I've failed to allocate a KnetArray due to limited memory before getting the curand error.

**Comment by denizyuret** [comment]
It could be CURAND itself does not have enough memory to initialized.  This
may happen if all of GPU memory is filled with KnetArrays before the first
CURAND call is made.

**Comment by CarloLucibello** [comment]
Hi, I'm sorry I cannot come with a reduced example, but essentually I encounter the problem when I run a certain script for the second time  from the REPL, something like:
```julia
julia> include("scipt.jl")

julia> main()
## many calls to randn! but ok here

julia> main()
....
ERROR: curand.curandGenerateNormal error 102 
...
```
I tried to call `knetgc()` at the begin of main but doesn't seem to fix the issue

**Comment by Sophylax** [comment]
I have managed to replicate the error after successfully calling `randn!` once. Are you calling `setseed` inside the script? If so that will regenerate the RNG which can lead to 102 error if there is not enough memory to actually regenerate it. 

Calling `knetgc()` should free the `KnetPtr`s that had been reclaimed by julia gc, but since that didn't work perhaps your objects in the `main()` aren't reclaimed by julia gc.

**Comment by CarloLucibello** [comment]
I was using 'setseed'  indeed, thanks @Sophylax. Maybe  i was doing setseed before knetgc(), I don't know, it was some rapidly changing research code. If 'setseed' is the problem, should we change it to call 'knetgc()' internally?

**Comment by denizyuret** [comment]
knetgc is really slow, not everybody may want the cost.

**Comment by CarloLucibello** [comment]
but `setseed` is called rarely, so maybe the impact would not be relevant. Otherwise, some way to point the user to the source of the error should be thought of.

**Comment by denizyuret** [comment]
My experiments with calls to setseed, rand! and randn! monitored using Knet.gpuinfo() indicate that the setseed in fact does not allocate extra space (possibly because I do a curandInit during initialization) but the first call to rand! or randn! still does. Need to understand exactly why rand! or randn! is allocating to solve this problem.

**Comment by ohspite** [comment]
I came across this error today, triggered by the `rand!` call in `dropout`. One of the workarounds in #181 was to run something like `rand!(KnetArray(ones(10)))` immediately after initializing the GPU, and that also worked in my case to prevent the error.

A minimal example to reproduce this behavior seems like it might be hardware dependent.  In the code I'm working with, the accuracy of a newly initialized network is calculated on the train/test sets (during which the dropout layer doesn't call `rand!`), and then the error occurs on the first training minibatch.  I'm using a K80, and immediately before that first training batch, the `nvidia-smi` shows that the memory usage is 11421 / 11441 MB.  

The error occurs on the **second** call to `dropout` in training mode. This is a Lenet-ish model with dropout applied to the input data, and then to the output of the first convolution layer, and so on; the error occurs when calling `dropout` on the output of the first convolution.

The top of the error message is below:

```
(:epoch, 0, :training, 0.4371035940803383, :validation, 0.4514666666666667)
ERROR: LoadError: curand.curandGenerateUniform error 102
Stacktrace:
 [1] macro expansion at /home/udm/.julia/v0.6/Knet/src/gpu.jl:18 [inlined]
 [2] rand!(::Knet.KnetArray{Float32,4}) at /home/udm/.julia/v0.6/Knet/src/random.jl:4
 [3] dropout!(::Float64, ::Knet.KnetArray{Float32,4}, ::Knet.KnetArray{Float32,4}) at /home/udm/.julia/v0.6/Knet/src/dropout.jl:53
 [4] #dropout#566(::Int64, ::Bool, ::Function, ::Knet.KnetArray{Float32,4}, ::Float64) at /home/udm/.julia/v0.6/Knet/src/dropout.jl:20
 [5] (::Knet.#kw##dropout)(::Array{Any,1}, ::Knet.#dropout, ::Knet.KnetArray{Float32,4}, ::Float64) at ./<missing>:0
 [6] (::AutoGrad.##rfun#7#10{Knet.#dropout})(::Array{Any,1}, ::Function, ::AutoGrad.Rec{Knet.KnetArray{Float32,4}}, ::Vararg{Any,N} where N) at /home/udm/.julia/v0.6/AutoGrad/src/core.jl:124
 [7] (::AutoGrad.#kw##rfun#9)(::Array{Any,1}, ::AutoGrad.#rfun#9, ::AutoGrad.Rec{Knet.KnetArray{Float32,4}}, ::Vararg{Any,N} where N) at ./<missing>:0
 [8] dropout(::AutoGrad.Rec{Knet.KnetArray{Float32,4}}, ::Float64) at /home/udm/.julia/v0.6/Knet/src/dropout.jl:44
 [9] #predict#13(::Float64, ::Function, ::AutoGrad.Rec{Array{Knet.KnetArray{Float32,N} where N,1}}, ::Knet.KnetArray{Float32,4}) at /home/udm/src/ornl/mxnet-research/knet-cnn-coda.jl:288
```
