### ISSUE TITLE
MethodError: hcat(::Int64, ::Int64, ::Int64, ::Int64, ::Int64, ::Int64) is ambiguous. Candidates:   hcat(a::Union{AbstractArray, Number}, as::Union{AbstractArray, Number}...) in Knet at /home/jrun/.julia/v0.6/Knet/src/karray.jl:305

### ISSUE THREAD

**Issue by yusufys** [denizyuret/Knet.jl#278]
Hello Mr. Yuret! Thanks for your efforts.

in short, I was just trying to apply the Logistic Regression Algorithm ,so far this is what I've wrote:
```
using Plots
using Knet
x = [1 1;1 2;2 2;2 1;3 1;3 2]
y = [1 1 1 0 0 0]'


sigmoid(z) = 1 ./ (1 + exp.(-z))

pred(w, x) = sigmoid(w[1] * x .+ w[2]);

function loss(w, x, y)
    yhat = pred(w,x)
    return -sum(y .* log.(yhat) + (1-y) .* log.(1-yhat))
end
lossgradient  = grad(loss)
```
**But I keep getting this error**

> MethodError: hcat(::Int64, ::Int64, ::Int64, ::Int64, ::Int64, ::Int64) is ambiguous. Candidates:
  hcat(a::Union{AbstractArray, Number}, as::Union{AbstractArray, Number}...) in Knet at /home/jrun/.julia/v0.6/Knet/src/karray.jl:305
  hcat(a::Union{AbstractArray, Knet.KnetArray, Number}, as::Union{AbstractArray, Knet.KnetArray, Number}...) in Knet at /home/jrun/.julia/v0.6/Knet/src/karray.jl:306
  hcat(X::T...) where T<:Number in Base at abstractarray.jl:1069
Possible fix, define
  hcat(::T<:Number, ::Vararg{T<:Number,N} where N)
Stacktrace:
 [1] include_string(::String, ::String) at ./loading.jl:522

Notice that I've tried this code on My Linux Machine, on my Windows machine and also on Juliabox.com and didn't work! can you tell me what's wrong with my code? 

Note: I did also run the command Pkg.update("Knet") and Pkg.update(), but it didn't update anything if there's a bugfix for this.

**Comment by kirnap** [comment]
Could you please checkout with the latest master by running:
```julia
Pkg.checkout("Knet")
```

**Comment by yusufys** [comment]
It Worked! Thanks Mr. Kirnap for your help.
