### ISSUE TITLE
trying to do a build on windows

### ISSUE THREAD

**Issue by blairn** [denizyuret/Knet.jl#285]
```
julia> Pkg.add("Knet")
INFO: Installing Knet v0.9.0
INFO: Removing CUDAapi v0.4.1
INFO: Building Knet
WARNING: Found multiple CUDA toolkit installations: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1 and C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
INFO: cuda1.jl
WARNING: Method definition colon(Base.VersionNumber, Base.VersionNumber) in module CUDAapi2 at D:\JuliaPro-0.6.2.1\pkgs-0.6.2.1\v0.6\Knet\deps\compatibility.jl:22 overwritten in module CUDAapi2 at D:\JuliaPro-0.6.2.1\pkgs-0.6.2.1\v0.6\Knet\src\../deps\compatibility.jl:22.
INFO: `'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\bin\nvcc.exe' -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe' --compiler-options '/Ox /LD' -c cuda1.cu`
cuda1.cu
INFO: cuda01.jl
INFO: `'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\bin\nvcc.exe' -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe' --compiler-options '/Ox /LD' -c cuda01.cu`
cuda01.cu
INFO: cuda11.jl
INFO: `'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\bin\nvcc.exe' -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe' --compiler-options '/Ox /LD' -c cuda11.cu`
cuda11.cu
INFO: cuda12.jl
INFO: `'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\bin\nvcc.exe' -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe' --compiler-options '/Ox /LD' -c cuda12.cu`
cuda12.cu
INFO: cuda13.jl
INFO: `'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\bin\nvcc.exe' -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe' --compiler-options '/Ox /LD' -c cuda13.cu`
cuda13.cu
INFO: cuda16.jl
INFO: `'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\bin\nvcc.exe' -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe' --compiler-options '/Ox /LD' -c cuda16.cu`
cuda16.cu
INFO: cuda17.jl
INFO: `'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\bin\nvcc.exe' -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe' --compiler-options '/Ox /LD' -c cuda17.cu`
cuda17.cu
INFO: cuda20.jl
INFO: `'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\bin\nvcc.exe' -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe' --compiler-options '/Ox /LD' -c cuda20.cu`
cuda20.cu
INFO: cuda21.jl
INFO: `'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\bin\nvcc.exe' -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe' --compiler-options '/Ox /LD' -c cuda21.cu`
cuda21.cu
INFO: cuda22.jl
INFO: `'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\bin\nvcc.exe' -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe' --compiler-options '/Ox /LD' -c cuda22.cu`
cuda22.cu
INFO: `'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\bin\nvcc.exe' -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe' --compiler-options '/Ox /LD' -c conv.cpp`
conv.cpp
INFO: `'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\bin\nvcc.exe' -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe' --compiler-options '/Ox /LD' --shared -o libknet8.dll cuda1.obj cuda01.obj cuda11.obj cuda12.obj cuda13.obj cuda16.obj cuda17.obj cuda20.obj cuda21.obj cuda22.obj conv.obj`
cuda1.obj
cuda01.obj
cuda11.obj
cuda12.obj
cuda13.obj
cuda16.obj
cuda17.obj
cuda20.obj
cuda21.obj
cuda22.obj
conv.obj
   Creating library libknet8.lib and object libknet8.exp
INFO: Compiling Knet cache.
INFO: Package database updated

julia> Pkg.test("Knet")
INFO: Testing Knet
Test Summary: | Pass  Total
kptr          |    1      1
 50.928406 seconds (3.93 M allocations: 213.203 MiB, 0.67% gc time)
gpu: Error During Test
  Test threw an exception of type ErrorException
  Expression: all((p->begin
            p > Knet.Cptr(0)
        end), (Knet.cublashandle(), Knet.cudnnhandle()))
  Could not find cudnn library
  Stacktrace:
   [1] find_library(::String, ::Array{String,1}) at D:\JuliaPro-0.6.2.1\pkgs-0.6.2.1\v0.6\Knet\src\../deps\discovery.jl:48
   [2] find_library(::String) at D:\JuliaPro-0.6.2.1\pkgs-0.6.2.1\v0.6\Knet\src\../deps\discovery.jl:21
   [3] cudnnCreate at D:\JuliaPro-0.6.2.1\pkgs-0.6.2.1\v0.6\Knet\src\gpu.jl:244 [inlined]
   [4] cudnnhandle(::Int64) at D:\JuliaPro-0.6.2.1\pkgs-0.6.2.1\v0.6\Knet\src\gpu.jl:195
   [5] macro expansion at D:\JuliaPro-0.6.2.1\pkgs-0.6.2.1\v0.6\Knet\test\gpu.jl:9 [inlined]
   [6] macro expansion at .\test.jl:860 [inlined]
   [7] macro expansion at D:\JuliaPro-0.6.2.1\pkgs-0.6.2.1\v0.6\Knet\test\gpu.jl:4 [inlined]
   [8] anonymous at .\<missing>:?
gpu: Error During Test
  Test threw an exception of type UndefVarError
  Expression: all((v->begin
            v > 0
        end), @show((Knet.cudaDriverVersion, Knet.cudaRuntimeVersion, Knet.cublasVersion, Knet.cudnnVersion)))
  UndefVarError: cudnnVersion not defined
  Stacktrace:
   [1] macro expansion at .\show.jl:243 [inlined]
   [2] macro expansion at D:\JuliaPro-0.6.2.1\pkgs-0.6.2.1\v0.6\Knet\test\gpu.jl:10 [inlined]
   [3] macro expansion at .\test.jl:860 [inlined]
   [4] macro expansion at D:\JuliaPro-0.6.2.1\pkgs-0.6.2.1\v0.6\Knet\test\gpu.jl:4 [inlined]
   [5] anonymous at .\<missing>:?
Test Summary: | Pass  Error  Total
gpu           |    5      2      7
ERROR: LoadError: LoadError: Some tests did not pass: 5 passed, 0 failed, 2 errored, 0 broken.
while loading D:\JuliaPro-0.6.2.1\pkgs-0.6.2.1\v0.6\Knet\test\gpu.jl, in expression starting on line 3
while loading D:\JuliaPro-0.6.2.1\pkgs-0.6.2.1\v0.6\Knet\test\runtests.jl, in expression starting on line 237
====================================================[ ERROR: Knet ]=====================================================
failed process: Process(`'D:\JuliaPro-0.6.2.1\Julia-0.6.2\bin\julia.exe' -Cx86-64 '-JD:\JuliaPro-0.6.2.1\Julia-0.6.2\lib\julia\sys.dll' --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=yes --compilecache=yes 'D:\JuliaPro-0.6.2.1\pkgs-0.6.2.1\v0.6\Knet\test\runtests.jl'`, ProcessExited(1)) [1]

========================================================================================================================ERROR: Knet had test errors
```

It looks like it is so very close to working. Any ideas what I should try next?

I'm running Julia 6.2 if it makes a difference

**Comment by denizyuret** [comment]
Can you see if the latest master works?  Try Pkg.checkout ("Knet") before a
Pkg.build ("Knet") again.

**Comment by blairn** [comment]
ok, am doing so. 

Knet.gpu() returns 0 if that helps.

Another weirdness, Pkg.add("Knet") runs the build process, but when I Pkg.build("Knet") it just hangs.

I'll wait and see, but currently I've got 3% processor usage, so I don't think it is building :/

**Comment by blairn** [comment]
Yeah, I am real certain it is frozen. I'll head off to bed and leave it overnight, see if it wakes up and builds or something. 

In saying that, if I do a build after doing a normal add, it does the same thing (ie, freezes). 

I may be able to have a look tomorrow and see if I can work out why it is doing this. If I can't I'll try clearing out julia and reinstalling it.

The last line we see is

INFO: Building Knet

It doesn't get to the warning about multiple CUDA toolkit installations, and processor drops to 0

**Comment by blairn** [comment]
ok, reboots later, and rebuilt.

julia> Pkg.checkout("Knet")
INFO: Checking out Knet master...
INFO: Pulling Knet latest master...
INFO: No packages to install, update or remove

julia> Pkg.build("Knet")
INFO: Building Knet
INFO: Compiling Knet cache.

julia> Pkg.test("Knet")
INFO: Testing Knet
Test Summary: | Pass  Total
kptr          |    1      1
  5.938777 seconds (3.86 M allocations: 209.078 MiB, 5.57% gc time)
gpu: Error During Test
  Test threw an exception of type ErrorException
  Expression: all((p->begin
            p > Knet.Cptr(0)
        end), (Knet.cublashandle(), Knet.cudnnhandle()))
  Cannot find cudnn
  Stacktrace:
   [1] cudnnCreate() at D:\JuliaPro-0.6.2.1\pkgs-0.6.2.1\v0.6\Knet\src\gpu.jl:246
   [2] cudnnhandle(::Int64) at D:\JuliaPro-0.6.2.1\pkgs-0.6.2.1\v0.6\Knet\src\gpu.jl:196
   [3] macro expansion at D:\JuliaPro-0.6.2.1\pkgs-0.6.2.1\v0.6\Knet\test\gpu.jl:9 [inlined]
   [4] macro expansion at .\test.jl:860 [inlined]
   [5] macro expansion at D:\JuliaPro-0.6.2.1\pkgs-0.6.2.1\v0.6\Knet\test\gpu.jl:4 [inlined]
   [6] anonymous at .\<missing>:?
gpu: Error During Test
  Test threw an exception of type UndefVarError
  Expression: all((v->begin
            v > 0
        end), @show((Knet.cudaDriverVersion, Knet.cudaRuntimeVersion, Knet.cublasVersion, Knet.cudnnVersion)))
  UndefVarError: cudnnVersion not defined
  Stacktrace:
   [1] macro expansion at .\show.jl:243 [inlined]
   [2] macro expansion at D:\JuliaPro-0.6.2.1\pkgs-0.6.2.1\v0.6\Knet\test\gpu.jl:10 [inlined]
   [3] macro expansion at .\test.jl:860 [inlined]
   [4] macro expansion at D:\JuliaPro-0.6.2.1\pkgs-0.6.2.1\v0.6\Knet\test\gpu.jl:4 [inlined]
   [5] anonymous at .\<missing>:?
Test Summary: | Pass  Error  Total
gpu           |    5      2      7
ERROR: LoadError: LoadError: Some tests did not pass: 5 passed, 0 failed, 2 errored, 0 broken.
while loading D:\JuliaPro-0.6.2.1\pkgs-0.6.2.1\v0.6\Knet\test\gpu.jl, in expression starting on line 3
while loading D:\JuliaPro-0.6.2.1\pkgs-0.6.2.1\v0.6\Knet\test\runtests.jl, in expression starting on line 237
====================================================[ ERROR: Knet ]=====================================================

failed process: Process(`'D:\JuliaPro-0.6.2.1\Julia-0.6.2\bin\julia.exe' -Cx86-64 '-JD:\JuliaPro-0.6.2.1\Julia-0.6.2\lib\julia\sys.dll' --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=yes --compilecache=yes 'D:\JuliaPro-0.6.2.1\pkgs-0.6.2.1\v0.6\Knet\test\runtests.jl'`, ProcessExited(1)) [1]

========================================================================================================================
ERROR: Knet had test errors

julia>

Same problems.

**Comment by blairn** [comment]
ok, so, I go in and do some testing.... :) I mean, why not?

using Knet
y = rand(1000,1000)
...
x = KnetArray(y)
...

@time y .* 12

  0.031507 seconds (5.78 k allocations: 7.917 MiB)
1000×1000 Array{Float64,2}:
...

@time x .* 12
  0.003083 seconds (389 allocations: 23.958 KiB)
1000×1000 Knet.KnetArray{Float64,2}:
...

Apart from the tests failing, it seems to be working.

**Comment by denizyuret** [comment]
It says cudnn cannot be found. My guess is that this library is either not
installed, or CUDAapi cannot find it. If it is installed please open an
issue with CUDAapi.jl. If not please install and retry. (cudnn is needed
for cnns fast rnns etc)

**Comment by blairn** [comment]
And we have our bug.

https://github.com/JuliaGPU/CUDAapi.jl/issues/36

CUDAapi can't detect CUDA 9.1

I guess installing an earlier version may work?

**Comment by denizyuret** [comment]
In your case it seems like cudnn (which is installed separately from cuda)
is the only thing not detected?

**Comment by blairn** [comment]
It was a bad cudnn install.

It works now!

**Comment by blairn** [comment]
Nope.... it isn't. Closed before last test.

julia> Pkg.checkout("Knet")
INFO: Checking out Knet master...
INFO: Pulling Knet latest master...
INFO: No packages to install, update or remove

julia> Pkg.build("Knet")
INFO: Building Knet
INFO: cuda1.jl
INFO: `'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\bin\nvcc.exe' -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe' --compiler-options '/Ox /LD' -c cuda1.cu`
cuda1.cu
INFO: cuda01.jl
INFO: `'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\bin\nvcc.exe' -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe' --compiler-options '/Ox /LD' -c cuda01.cu`
cuda01.cu
INFO: cuda11.jl
INFO: `'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\bin\nvcc.exe' -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe' --compiler-options '/Ox /LD' -c cuda11.cu`
cuda11.cu
INFO: cuda12.jl
INFO: `'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\bin\nvcc.exe' -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe' --compiler-options '/Ox /LD' -c cuda12.cu`
cuda12.cu
INFO: cuda13.jl
INFO: `'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\bin\nvcc.exe' -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe' --compiler-options '/Ox /LD' -c cuda13.cu`
cuda13.cu
INFO: cuda16.jl
INFO: `'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\bin\nvcc.exe' -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe' --compiler-options '/Ox /LD' -c cuda16.cu`
cuda16.cu
INFO: cuda17.jl
INFO: `'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\bin\nvcc.exe' -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe' --compiler-options '/Ox /LD' -c cuda17.cu`
cuda17.cu
INFO: cuda20.jl
INFO: `'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\bin\nvcc.exe' -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe' --compiler-options '/Ox /LD' -c cuda20.cu`
cuda20.cu
INFO: cuda21.jl
INFO: `'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\bin\nvcc.exe' -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe' --compiler-options '/Ox /LD' -c cuda21.cu`
cuda21.cu
INFO: cuda22.jl
INFO: `'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\bin\nvcc.exe' -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe' --compiler-options '/Ox /LD' -c cuda22.cu`
cuda22.cu
INFO: `'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\bin\nvcc.exe' -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe' --compiler-options '/Ox /LD' --shared -o libknet8.dll cuda1.obj cuda01.obj cuda11.obj cuda12.obj cuda13.obj cuda16.obj cuda17.obj cuda20.obj cuda21.obj cuda22.obj conv.obj`
cuda1.obj
cuda01.obj
cuda11.obj
cuda12.obj
cuda13.obj
cuda16.obj
cuda17.obj
cuda20.obj
cuda21.obj
cuda22.obj
conv.obj
   Creating library libknet8.lib and object libknet8.exp
INFO: Compiling Knet cache.

julia> Pkg.test("Knet")
INFO: Testing Knet
Test Summary: | Pass  Total
kptr          |    1      1
 17.415347 seconds (3.91 M allocations: 211.942 MiB, 1.80% gc time)
(Knet.cudaDriverVersion, Knet.cudaRuntimeVersion, Knet.cublasVersion, Knet.cudnnVersion) = (9010, 9010, 9010, 7101)
Test Summary: | Pass  Total
gpu           |    7      7
  2.645771 seconds (688.80 k allocations: 38.211 MiB, 0.39% gc time)
Test Summary: | Pass  Total
distributions |    3      3
  2.137643 seconds (1.51 M allocations: 80.839 MiB, 1.13% gc time)
Test Summary: | Pass  Total
dropout       |    3      3
  1.612092 seconds (622.55 k allocations: 33.384 MiB, 0.70% gc time)
Test Summary: | Pass  Total
loss          |   18     18
  4.031420 seconds (2.41 M allocations: 124.338 MiB, 0.93% gc time)
rnn: Error During Test
  Got an exception of type InexactError outside of a @test
  InexactError()
  Stacktrace:
   [1] #rnnparam#480(::Ptr{Void}, ::Bool, ::Function, ::Knet.RNN, ::Knet.KnetArray{Float64,3}, ::Int64, ::Int64, ::Int64) at D:\JuliaPro-0.6.2.1\pkgs-0.6.2.1\v0.6\Knet\src\rnn.jl:226
   [2] (::Knet.#kw##rnnparam)(::Array{Any,1}, ::Knet.#rnnparam, ::Knet.RNN, ::Knet.KnetArray{Float64,3}, ::Int64, ::Int64, ::Int64) at .\<missing>:0
   [3] #rnnparams#483(::Ptr{Void}, ::Bool, ::Function, ::Knet.RNN, ::Knet.KnetArray{Float64,3}) at D:\JuliaPro-0.6.2.1\pkgs-0.6.2.1\v0.6\Knet\src\rnn.jl:295
   [4] (::Knet.#kw##rnnparams)(::Array{Any,1}, ::Knet.#rnnparams, ::Knet.RNN, ::Knet.KnetArray{Float64,3}) at .\<missing>:0
   [5] #rnninit#484(::Ptr{Void}, ::Int64, ::Float64, ::Bool, ::Bool, ::Symbol, ::Type{T} where T, ::Int64, ::Int64, ::Knet.#xavier, ::Knet.#xavier, ::Bool, ::Knet.#rnninit, ::Int64, ::Int64) at D:\JuliaPro-0.6.2.1\pkgs-0.6.2.1\v0.6\Knet\src\rnn.jl:400
   [6] (::Knet.#kw##rnninit)(::Array{Any,1}, ::Knet.#rnninit, ::Int64, ::Int64) at .\<missing>:0
   [7] macro expansion at D:\JuliaPro-0.6.2.1\pkgs-0.6.2.1\v0.6\Knet\test\rnn.jl:18 [inlined]
   [8] macro expansion at .\test.jl:860 [inlined]
   [9] macro expansion at D:\JuliaPro-0.6.2.1\pkgs-0.6.2.1\v0.6\Knet\test\rnn.jl:16 [inlined]
   [10] anonymous at .\<missing>:?
   [11] include_from_node1(::String) at .\loading.jl:576
   [12] include(::String) at .\sysimg.jl:14
   [13] include_from_node1(::String) at .\loading.jl:576
   [14] include(::String) at .\sysimg.jl:14
   [15] process_options(::Base.JLOptions) at .\client.jl:305
   [16] _start() at .\client.jl:371
Test Summary: | Pass  Error  Total
rnn           |   92      1     93
ERROR: LoadError: LoadError: Some tests did not pass: 92 passed, 0 failed, 1 errored, 0 broken.
while loading D:\JuliaPro-0.6.2.1\pkgs-0.6.2.1\v0.6\Knet\test\rnn.jl, in expression starting on line 5
while loading D:\JuliaPro-0.6.2.1\pkgs-0.6.2.1\v0.6\Knet\test\runtests.jl, in expression starting on line 237
====================================================[ ERROR: Knet ]=====================================================
failed process: Process(`'D:\JuliaPro-0.6.2.1\Julia-0.6.2\bin\julia.exe' -Cx86-64 '-JD:\JuliaPro-0.6.2.1\Julia-0.6.2\lib\julia\sys.dll' --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=yes --compilecache=yes 'D:\JuliaPro-0.6.2.1\pkgs-0.6.2.1\v0.6\Knet\test\runtests.jl'`, ProcessExited(1)) [1]

========================================================================================================================ERROR: Knet had test errors

**Comment by findmyway** [comment]
Interesting, I've just test it on my Win10 and all tests passed.

**Comment by denizyuret** [comment]
What version of Visual Studio, Cuda and Cudnn did you try with?

**Comment by findmyway** [comment]
@denizyuret 

I have installed both VS2017 and VS2015 on my computer for daily development. Not sure is it  related.

```
nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Mon_Jan__9_17:32:33_CST_2017
Cuda compilation tools, release 8.0, V8.0.60
```
```
The Cudnn version:
![image](https://user-images.githubusercontent.com/5612003/37942771-5ac7dea0-31a7-11e8-9880-589514398882.png)

```

Test log:

```
julia> Pkg.build("Knet")
INFO: Building Knet
INFO: cuda1.jl
INFO: `'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\nvcc.exe' -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe' --compiler-options '/Ox /LD' -c cuda1.cu`
cuda1.cu
INFO: cuda01.jl
INFO: `'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\nvcc.exe' -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe' --compiler-options '/Ox /LD' -c cuda01.cu`
cuda01.cu
INFO: cuda11.jl
INFO: `'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\nvcc.exe' -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe' --compiler-options '/Ox /LD' -c cuda11.cu`
cuda11.cu
INFO: cuda12.jl
INFO: `'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\nvcc.exe' -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe' --compiler-options '/Ox /LD' -c cuda12.cu`
cuda12.cu
INFO: cuda13.jl
INFO: `'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\nvcc.exe' -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe' --compiler-options '/Ox /LD' -c cuda13.cu`
cuda13.cu
INFO: cuda16.jl
INFO: `'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\nvcc.exe' -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe' --compiler-options '/Ox /LD' -c cuda16.cu`
cuda16.cu
INFO: cuda17.jl
INFO: `'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\nvcc.exe' -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe' --compiler-options '/Ox /LD' -c cuda17.cu`
cuda17.cu
INFO: cuda20.jl
INFO: `'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\nvcc.exe' -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe' --compiler-options '/Ox /LD' -c cuda20.cu`
cuda20.cu
INFO: cuda21.jl
INFO: `'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\nvcc.exe' -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe' --compiler-options '/Ox /LD' -c cuda21.cu`
cuda21.cu
INFO: cuda22.jl
INFO: `'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\nvcc.exe' -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe' --compiler-options '/Ox /LD' -c cuda22.cu`
cuda22.cu
INFO: `'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\nvcc.exe' -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe' --compiler-options '/Ox /LD' -c conv.cpp`
conv.cpp
INFO: `'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\nvcc.exe' -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe' --compiler-options '/Ox /LD' --shared -o libknet8.dll cuda1.obj cuda01.obj cuda11.obj cuda12.obj cuda13.obj cuda16.obj cuda17.obj cuda20.obj cuda21.obj cuda22.obj conv.obj`
cuda1.obj
cuda01.obj
cuda11.obj
cuda12.obj
cuda13.obj
cuda16.obj
cuda17.obj
cuda20.obj
cuda21.obj
cuda22.obj
conv.obj
   Creating library libknet8.lib and object libknet8.exp
INFO: Compiling Knet cache.

julia> Pkg.test("Knet")
INFO: Testing Knet
Test Summary: | Pass  Total
kptr          |    1      1
 15.446043 seconds (11.52 M allocations: 644.810 MiB, 2.25% gc time)
(Knet.cudaDriverVersion, Knet.cudaRuntimeVersion, Knet.cublasVersion, Knet.cudnnVersion) = (8000, 8000, 8000, 6021)
Test Summary: | Pass  Total
gpu           |    7      7
  1.634473 seconds (674.51 k allocations: 37.394 MiB, 0.71% gc time)
Test Summary: | Pass  Total
distributions |    3      3
  2.299432 seconds (1.61 M allocations: 85.017 MiB, 1.28% gc time)
Test Summary: | Pass  Total
dropout       |    3      3
  2.176672 seconds (622.27 k allocations: 33.363 MiB, 0.28% gc time)
Test Summary: | Pass  Total
loss          |   18     18
  4.125488 seconds (2.48 M allocations: 127.481 MiB, 0.98% gc time)
Test Summary: | Pass  Total
rnn           | 1776   1776
 83.649590 seconds (101.58 M allocations: 6.796 GiB, 1.49% gc time)
Test Summary: | Pass  Total
karray        |  244    244
 14.189229 seconds (5.04 M allocations: 266.162 MiB, 0.69% gc time)
Test Summary: | Pass  Total
update!       |   20     20
111.436646 seconds (89.11 M allocations: 3.836 GiB, 1.32% gc time)
Test Summary: | Pass  Total
conv          |  138    138
 32.817844 seconds (7.50 M allocations: 385.351 MiB, 46.08% gc time)
Test Summary: | Pass  Total
linalg        |  184    184
 18.678145 seconds (7.34 M allocations: 376.392 MiB, 0.75% gc time)
21:55:11 broadcast: array-scalar
21:55:30 broadcast: array-vector
21:55:44 broadcast: array-array
21:55:49 broadcast: ndims
Test Summary: | Pass  Total
broadcast     | 3779   3779
21:55:50 broadcast: done
 39.433371 seconds (18.96 M allocations: 1.544 GiB, 1.86% gc time)
Test Summary: | Pass  Total
unary         | 1600   1600
 42.781911 seconds (14.86 M allocations: 746.015 MiB, 0.84% gc time)
Test Summary: | Pass  Total
reduction     | 1728   1728
 41.845022 seconds (38.37 M allocations: 1.624 GiB, 4.59% gc time)
Test Summary: | Pass  Total
batchnorm     |  130    130
 53.639740 seconds (47.56 M allocations: 2.013 GiB, 2.04% gc time)
INFO: Knet tests passed

julia> VERSION
v"0.6.2"

julia> Pkg.status("Knet")
 - Knet                          0.9.0+             master

julia> using Knet

julia> gpu()
0
```

I'm very glad to help address the windows related issue, let me know if you need more information.

**Comment by denizyuret** [comment]
This is great, thanks.

**Comment by blairn** [comment]
I'll rebuild tonight! See what it does
