### ISSUE TITLE
Feature request: cuBLAS Strided Batched Matrix Multiply

### ISSUE THREAD

**Issue by ngphuoc** [denizyuret/Knet.jl#295]
This feature would enable networks which use matrices as inputs, states, and outputs. It allows running on mini batches of matrices.

ref: https://devblogs.nvidia.com/cublas-strided-batched-matrix-multiply/

**Comment by cangumeli** [comment]
What kind of Julia interface do you recommend for this operation?

**Comment by ngphuoc** [comment]
I think it is best that the same code can run on both CPU and GPU. I think the syntax in `@tensor` in TensorOperations.jl would be an approach. The second is mapslices (https://github.com/JuliaComputing/ArrayFire.jl/issues/187). And the third option, which may has simplest syntax and need extension overload on CPU, is to extend existing blas operators.

**Comment by cangumeli** [comment]
What about a `bmm` function that simply takes two 3d arrays and perform batch matrix multiplication?

Your third option seems very optimal in terms of syntax, but I'm not sure about changing default behaviour of julia matrix multiplication.

**Comment by ngphuoc** [comment]
Yes, that would be reasonable. Users can override `*` for their personal need. An additional `bmm!(out, batch1, batch2)` would be helpful.

**Comment by ngphuoc** [comment]
And a `btranspose` if it is faster than `permutedims`.

**Comment by Roger-luo** [comment]
Just to mention, I have added a `gemmBatchedStrided` wrapper in CuArrays.jl: https://github.com/JuliaGPU/CuArrays.jl/pull/190

**Comment by denizyuret** [comment]
PR #363 was merged with master. @ngphuoc does this resolve this issue?

**Comment by ngphuoc** [comment]
I works great! Thanks
