### ISSUE TITLE
Ambiguity in rnnforw usage

### ISSUE THREAD

**Issue by kirnap** [denizyuret/Knet.jl#299]
```julia
# Let's say I have a usual rnn data-structures, namely, r_b and wr_b
# I want to create initial state, e.g.,zeros
julia> instate = zeros(r_b.dataType, r_b.hiddenSize, 1);
julia> hout = cout = (gpu() >=0 ? KnetArray(instate) : instate); 
julia> input = KnetArray(randn(r_b.dataType,1078));
julia> size(hout)
(256, 1)
julia> hout2 = reshape(hout, 256, 1, 1);cout2 = reshape(cout, 256, 1, 1);
# both of the following lines works perfectly fine
juila> yout, hout, cout, _ = rnnforw(r_b, wr_b, input, hout, cout, hy=true, cy=true);
julia> yout, hout, cout, _ = rnnforw(r_b, wr_b, input, hout2, cout2, hy=true, cy=true);
```
However, as a user, I would prefer single-uniform(returning the same shape) rnnforw function. To feel safe for possible bugs.

**Comment by denizyuret** [comment]
We have three different possible inputs (x shape) to the RNN:
1-D: for single instance single time step
2-D: for batch of instances single time step i.e. (X,B)
3-D: for batches of instances for multiple time steps i.e. (X,B,T)

The most general hidden size has dimensions (H,B,L).  If the user is working with 1-D inputs, i.e. no batching, she may prefer to feed the hidden vector also as a 1-D vector. If she is working with minibatches but has no layers, then conceptually it is simpler to use a 2-D hidden matrix (H,B).

The Julia convention is to assume the missing dimensions as 1, i.e. you can ask size(x, 12) and you will get 1 if x has lower than 12 dimensions. I think this usage is consistent with the Julia standard.

**Comment by denizyuret** [comment]
Having said that, the output hiddens are currently always 3-D.

**Comment by kirnap** [comment]
I think "The Julia convention is to assume the missing dimensions as 1" argument solves that problem. Thank you!
