### ISSUE TITLE
Annoying stack-overflow error 

### ISSUE THREAD

**Issue by ngphuoc** [denizyuret/Knet.jl#314]
The following snippet causes endless stack-overflow errors

```julia
using Knet
a = rand(3)
a .* KnetArray(a)
```
I encounter this very often due to my complex data processing step. I had to pkill julia every time I got this error. 

Is there a way to catch this error and give an alternative shorter error message?

**Comment by denizyuret** [comment]
Yes.  This is a known problem caused by the broadcasting hack for Julia 0.6
(only when you try to operate on two incompatible arrays).  Broadcasting
was completely changed for 0.7, so the next version should not have this
problem.

**Comment by denizyuret** [comment]
Mixing array types does not cause stack-overflow in latest release. Instead you get an Array answer. Is this ok?

**Comment by ngphuoc** [comment]
An Array answer would be fine! But in julia v0.7 I got a "no method matching" error instead of an Array answer! There is no stackoverflow error now.

```julia
julia> using Knet

julia> w = KnetArray(rand(2,3))
2×3 Knet.KnetDisplay{Float64,2}:
 0.0619187  0.778375  0.801637
 0.176027   0.55352   0.608172

julia> x = rand(3,4)
3×4 Array{Float64,2}:
 0.527576  0.304551  0.97076   0.378788
 0.682434  0.341415  0.288515  0.897143
 0.20335   0.472759  0.892548  0.304457

julia> w*x
ERROR: MethodError: no method matching *(::KnetArray{Float64,2}, ::Array{Float64,2})
Closest candidates are:
  *(::Any, ::Any, ::Any, ::Any...) at operators.jl:502
...
```
