### ISSUE TITLE
cat 4D arrays along channel dimension

### ISSUE THREAD

**Issue by Evizero** [denizyuret/Knet.jl#319]
It would be really useful to be able to `cat` combatible outputs of  `conv4` along the channel dimension. For example for Dense Conv Nets: https://arxiv.org/abs/1608.06993 . 

I could not find a build-in way to do this with Knet, so i tried to hack up my own implementation to address my current use case. AFAICT it works and has an ok performance, but it is nowhere near generic enough to make a PR out of it. So I'll leave my snippet here as reference in case someone would like to implement it properly at some point.

```julia
function ccat(A::KnetArray{T,4}, B::KnetArray{T,4}) where T
    h1, w1, c1, m1 = size(A)
    h2, w2, c2, m2 = size(B)
    @assert h1 == h2 && w1 == w2 && m1 == m2
    c3 = c1 + c2
    C = similar(A, (h1 * w1 * c3, m1))
    off = h1 * w1 * c1
    C[1:off,:] = A
    C[off+1:end,:] = B
    reshape(C, (h1, w1, c3, m1))
end

ccat_r = Knet.recorder(ccat)
ccat(X::Knet.Rec...) = ccat_r(X...)

function ccat(::Type{Knet.Grad{1}}, dy, y, A, B)
    h1, w1, c1, m1 = size(A)
    h2, w2, c2, m2 = size(B)
    h3, w3, c3, m3 = size(dy)
    C = reshape(dy, (h3*w3*c3, m3))
    off = h1 * w1 * c1
    reshape(C[1:off,:], (h1, w1, c1, m1))
end

function ccat(::Type{Knet.Grad{2}}, dy, y, A, B)
    h1, w1, c1, m1 = size(A)
    h2, w2, c2, m2 = size(B)
    h3, w3, c3, m3 = size(dy)
    C = reshape(dy, (h3*w3*c3, m3))
    off = h1 * w1 * c1
    reshape(C[off+1:end,:], (h2, w2, c2, m2))
end
```

**Comment by denizyuret** [comment]
The new cat fallback using CuArrays should fix this, please test.
