### ISSUE TITLE
KnetArray linear indexing does not work

### ISSUE THREAD

**Issue by kirnap** [denizyuret/Knet.jl#32]
`a = randn(256,10000);
x = convert(Knet.KnetArray, a);
x[[1,2,3]]` creates the following error:

`ERROR: MethodError: no method matching getindex(::Knet.KnetArray{Float64,2}, ::Array{Int64,1})`

**Comment by denizyuret** [comment]
You can implement this as x[1:3].  Do you need non-contiguous indices?

**Comment by denizyuret** [comment]
Currently only Integer, Range, or Colon indices are supported for KnetArray.  To get the rest to work, we need to complete the missing getindex methods.  

In Julia, a[[1,3,5]] calls:
```
getindex(A::AbstractArray, I...) at abstractarray.jl:751
_getindex(l::Base.LinearIndexing, A::AbstractArray, i::Union{AbstractArray,Colon,Real}) at multidimensional.jl:275
_unsafe_getindex(::Base.LinearIndexing, A::AbstractArray, I::Union{AbstractArray,Colon,Real}...) at multidimensional.jl:291
_unsafe_getindex!(dest::AbstractArray, src::AbstractArray, I::Union{AbstractArray,Colon,Real}...) at multidimensional.jl:340
```
and a[[true,false,true]] calls:
```
_unsafe_getindex(::Base.LinearFast, src::AbstractArray, I::AbstractArray{Bool,N<:Any}) at multidimensional.jl:321
```
These need to be ported to KnetArrays.  We get them for free if we inherit from AbstractArray, but that has other problems such as inefficient operations getting called inadvertently on KnetArrays.  However as a temporary workaround you can try modifying the type declaration of KnetArray in karray.jl to inherit from AbstractArray:
```
type KnetArray{T,N} <: AbstractArray
```

**Comment by denizyuret** [comment]
Implemented the following indexing options:
  * 1-D:  Int, Colon, UnitRange, StepRange, Array{Int}, BitArray, CartesianIndex, Array{CartesianIndex} (1-D includes linear indexing of multidimensional arrays)                                                                                    
  * 2-D: (Colon,Union{Int,Colon,UnitRange,StepRange,Array{Int}}), (Union{Int,UnitRange,Colon}...) (in any order)           
  * N-D: (Int...)                    
The 1-D support is complete, 2-D and N-D are still missing a lot.
