### ISSUE TITLE
Question about Building Knet under Windows10

### ISSUE THREAD

**Issue by the-butterfly** [denizyuret/Knet.jl#326]
I've using the latest `Knet` under `Julia Pro 0.6.4`,  But I got a problem:
```
julia> Pkg.build("Knet")
INFO: Building Knet
WARNING: no compilers found, **libknet8** will not be built.
INFO: Compiling Knet cache.
```
**What should I do to fix the problem?**
BTW, when I using gradients, it breaks
```
# cold start   # using examples `Knet_CNN.ipynb`
@time for (x,y) in minibatch(xtrn,ytrn,BATCHSIZE;shuffle=true,xtype=KnetArray)
    grads = lossgradient(model, x, y)
    update!(model, grads, optim)
end

> Cannot find libknet8, please rerun Pkg.build("Knet").
> Stacktrace:
> ……

```

Could anyone helps?

**Comment by denizyuret** [comment]
Do you have Visual Studio installed as in
https://github.com/denizyuret/Knet.jl/blob/master/deps/README.windows

**Comment by the-butterfly** [comment]
@denizyuret Oh, it's my negligence. I'll have a try. And really thanks for your fast reply.

**Comment by the-butterfly** [comment]
I have tried both `msvc toolset 14.1` and `MSVS 14.0`, but it doesn't work still.
BTW, I use the `vcvars64.bat` provided by MS straightly on `CMD command line`.
```
julia> Pkg.build("Knet")
INFO: Building Knet
WARNING: no compilers found, libknet8 will not be built.
INFO: Compiling Knet cache.

julia> ENV["PATH"]
E:\\Develop\\IDEs\\JuliaPro\\Julia-0.6.4\\bin;C:\\Program Files (x86)\\MSBuild\\14.0\\bin\\amd64;C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\amd64; ……

shell> cl test.cpp
……
test.cpp
Microsoft (R) Incremental Linker Version 14.00.24225.1
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:test.exe
test.obj

shell> test

julia>

```

I am really confused about how the program find compilers?
Can I do anything to fix it?

**Comment by denizyuret** [comment]
It uses a package called CUDAapi to find the compilers. See if you can test
CUDAapi first. Once that works Knet/deps/build.jl should use it to discover
and use the compilers.

**Comment by the-butterfly** [comment]
Thanks, I think it's a problem by `CUDAapi` and try to fix it.

**Comment by the-butterfly** [comment]
Now, everything works fine after update. Please close this issue.
