### ISSUE TITLE
JLD2 vs Knet load behave differently

### ISSUE THREAD

**Issue by denizyuret** [denizyuret/Knet.jl#344]
When loading [this file](http://people.csail.mit.edu/deniz/data/mnist.jld2) we seem to have a problem:
```
using JLD2, FileIO
a1 = FileIO.load("mnist.jld2","dtst")
a2 = Knet.load("mnist.jld2","dtst")
first(a1) => ok
first(a2) => error
```
As far as I can tell, a1 and a2 are identical except for the xtype field.  
```
for n in fieldnames(Knet.Data)
    println(n,"\t",getfield(a1,n)==getfield(a2,n))
end
x	true
y	true
batchsize	true
length	true
partial	true
indices	true
shuffle	true
xsize	true
ysize	true
xtype	false
ytype	true
```
Both a1.xtype and a2.xtype print the same but they seem to be not equal! If I replace a2.xtype = a1.xtype it starts working.  You may want to check how types are saved...

**Comment by ekinakyurek** [comment]
I actualy do nothing for types, it is very strange. I could not see why this is happening. Do you have any idea?

**Comment by ekinakyurek** [comment]
this issue is still exist, very interesting

**Comment by ekinakyurek** [comment]
I think @JeffBezanson may have a comment on that.

**Comment by JeffBezanson** [comment]
Is the TypeVar N === to the one inside the Array type in the body field?

**Comment by ekinakyurek** [comment]
```JULIA
julia> a1.xtype.var == a2.xtype.var
false

julia> a1.xtype.var
N

julia> a2.xtype.var
N
```

**Comment by ekinakyurek** [comment]
We were replicating deepcopy in our saving code. So, I found this JuliaLang/julia#30911
