### ISSUE TITLE
when running rnnlm-batch.jl and bilstm-tagger.jl and treenn.jl with GPU,it occurs some errors about the gpu device

### ISSUE THREAD

**Issue by THuang001** [denizyuret/Knet.jl#351]
when runing rnnlm-batch.jl with the command line:"julia-0.6.2 knet/rnnlm-batch.jl --gpu 128 128 0 600
",it occurs the followed error:
WARNING: Array(::Type{T}, m::Int) where T is deprecated, use Array{T}(m) instead.
Stacktrace:
 [1] depwarn(::String, ::Symbol) at ./deprecated.jl:70
 [2] Array(::Type{Any}, ::Int64) at ./deprecated.jl:57
 [3] initweights(::Type{T} where T, ::Int64, ::Int64, ::Int64, ::Int64, ::Float64) at /home/taohuang/treelstm_julia/knet/treenn.jl:220 (repeats 2 times)
 [4] main(::Array{String,1}) at /home/taohuang/treelstm_julia/knet/treenn.jl:43
 [5] include_from_node1(::String) at ./loading.jl:576
 [6] include(::String) at ./sysimg.jl:14
 [7] process_options(::Base.JLOptions) at ./client.jl:305
 [8] _start() at ./client.jl:371
while loading /home/taohuang/treelstm_julia/knet/treenn.jl, in expression starting on line 327
ERROR: LoadError: KnetPtr: bad device id -1.
Stacktrace:
 [1] Knet.KnetPtr(::Int64) at /home/taohuang/.julia/v0.6/Knet/src/kptr.jl:73
 [2] Type at /home/taohuang/.julia/v0.6/Knet/src/karray.jl:104 [inlined]
 [3] Type at /home/taohuang/.julia/v0.6/Knet/src/karray.jl:110 [inlined]
 [4] convert(::Type{Knet.KnetArray{Float32,2}}, ::Array{Float64,2}) at /home/taohuang/.julia/v0.6/Knet/src/karray.jl:146
 [5] convert(::Type{Knet.KnetArray{Float32,N} where N}, ::Array{Float64,2}) at /home/taohuang/.julia/v0.6/Knet/src/karray.jl:145
 [6] _collect(::Array{Any,1}, ::Base.Generator{Array{Any,1},TreeNN.##13#14{UnionAll}}, ::Base.EltypeUnknown, ::Base.HasShape) at ./array.jl:488
 [7] initweights(::Type{T} where T, ::Int64, ::Int64, ::Int64, ::Int64, ::Float64) at /home/taohuang/treelstm_julia/knet/treenn.jl:230
 [8] initweights(::Type{T} where T, ::Int64, ::Int64, ::Int64, ::Int64) at /home/taohuang/treelstm_julia/knet/treenn.jl:220
 [9] main(::Array{String,1}) at /home/taohuang/treelstm_julia/knet/treenn.jl:43
 [10] include_from_node1(::String) at ./loading.jl:576
 [11] include(::String) at ./sysimg.jl:14
 [12] process_options(::Base.JLOptions) at ./client.jl:305
 [13] _start() at ./client.jl:371
while loading /home/taohuang/treelstm_julia/knet/treenn.jl, in expression starting on line 327

**Comment by denizyuret** [comment]
There seem to be several problems: the Array warning suggests you are running an old (julia-0.5?) example on julia-0.6. Please upgrade to julia-1.0.0 and the latest Knet version if you can.  The GPU problem means either your machine does not have a gpu or it is not detected. We can tell more if you run `include(Knet.dir("test","gpu.jl"))` in a recent version of Knet.

**Comment by THuang001** [comment]
I run include(Knet.dir("test","gpu.jl")) with julia 1.0.0 and Knetv1.1.0 ,the results are followed:
julia> include(Knet.dir("test","gpu.jl"))
Knet.gpuCount() = 0
Knet.gpu() = -1
Knet.tk = String[]
Knet.libknet8 = ""
Knet.cudartfound = false
Knet.nvmlfound = false
Knet.cublashandle() = nothing
Knet.cudnnhandle() = nothing
Knet.dir() = "C:\\Users\\v-tahuan\\.julia\\packages\\Knet\\00vTf"
readdir(Knet.dir("deps")) = [".deprecated", ".gitignore", "build.jl", "build.log", "conv.cpp", "cuda01.jl", "cuda1.jl", "cuda11.jl", "cuda12.jl", "cuda13.jl", "cuda14.jl", "cuda16.jl", "cuda17.jl", "cuda20.jl", "cuda21.jl", "cuda22.jl", "Makefile", "README.windows"]
Test Summary: |
gpu           | No tests

**Comment by denizyuret** [comment]
There is no gpu detected. You can only use regular arrays without a gpu,
not KnetArrays.

**Comment by THuang001** [comment]
I have gpu,
![image](https://user-images.githubusercontent.com/10249982/45464863-1bb0d400-b745-11e8-89dd-b03a4bd4d2f5.png)

**Comment by THuang001** [comment]
I have gpu. NVIDIA Corporation GK110 [GeForce GTX TITAN]

**Comment by THuang001** [comment]
I have 3 gpus.
![image](https://user-images.githubusercontent.com/10249982/45466043-80226200-b74a-11e8-9e62-c76c3d48f317.png)
then vi ~/.profile and export CUDA_VISIBLE_DEVICES=0   ,then run include(Knet.dir("test","gpu.jl")) with julia -1.0 and knet v1.1.0 ,results are followed:
julia> include(Knet.dir("test","gpu.jl"))
Knet.gpuCount() = 3
Knet.gpu() = -1
Knet.tk = ["/usr/local/cuda-8.0", "/usr/local/cuda-9.0"]
Knet.libknet8 = "/home/taohuang/.julia/packages/Knet/hxjeS/deps/libknet8"
Knet.cudartfound = true
Knet.cudaRuntimeVersion = 8000
Knet.cudaDriverVersion = 9000
Knet.cudaGetDeviceCount() = 2
Knet.cudaGetDevice() = 0
Knet.cudaMemGetInfo() = (6147080192, 6377766912)
Knet.cudaDeviceSynchronize() = nothing
Knet.nvmlfound = true
Knet.nvmlDriverVersion = "384.130"
Knet.nvmlVersion = "9.384.130"
Knet.nvmlDeviceGetMemoryInfo() = nothing
Knet.cublashandle() = nothing
Knet.cudnnhandle() = nothing
Knet.dir() = "/home/taohuang/.julia/packages/Knet/hxjeS"
readdir(Knet.dir("deps")) = [".deprecated", ".gitignore", "Makefile", "README.windows", "build.jl", "build.log", "conv.cpp", "conv.o", "cuda01.cu", "cuda01.jl", "cuda01.o", "cuda1.cu", "cuda1.jl", "cuda1.o", "cuda11.cu", "cuda11.jl", "cuda11.o", "cuda12.cu", "cuda12.jl", "cuda12.o", "cuda13.cu", "cuda13.jl", "cuda13.o", "cuda14.jl", "cuda16.cu", "cuda16.jl", "cuda16.o", "cuda17.cu", "cuda17.jl", "cuda17.o", "cuda20.cu", "cuda20.jl", "cuda20.o", "cuda21.cu", "cuda21.jl", "cuda21.o", "cuda22.cu", "cuda22.jl", "cuda22.o", "foo.cpp", "foo.o", "libknet8.so"]
Test Summary: |
gpu           | No tests


but when i set export CUDA_VISIBLE_DEVICES=0,1,2 in ~/.profile then source ,the results changed:


julia> include(Knet.dir("test","gpu.jl"))
Knet.gpuCount() = 3
Knet.gpu() = 2
Knet.tk = ["/usr/local/cuda-8.0", "/usr/local/cuda-9.0"]
Knet.libknet8 = "/home/taohuang/.julia/packages/Knet/hxjeS/deps/libknet8"
Knet.cudartfound = true
Knet.cudaRuntimeVersion = 8000
Knet.cudaDriverVersion = 9000
Knet.cudaGetDeviceCount() = 3
Knet.cudaGetDevice() = 2
Knet.cudaMemGetInfo() = (6294405120, 6375669760)
Knet.cudaDeviceSynchronize() = nothing
Knet.nvmlfound = true
Knet.nvmlDriverVersion = "384.130"
Knet.nvmlVersion = "9.384.130"
Knet.nvmlDeviceGetMemoryInfo() = (6375669760, 6294405120, 81264640)
Knet.cublashandle() = Ptr{Nothing} @0x0000000007a24aa0
Knet.cublasVersion = 8000
Knet.cudnnhandle() = Ptr{Nothing} @0x0000000007ddb9e0
Knet.cudnnVersion = 7104
Knet.dir() = "/home/taohuang/.julia/packages/Knet/hxjeS"
readdir(Knet.dir("deps")) = [".deprecated", ".gitignore", "Makefile", "README.windows", "build.jl", "build.log", "conv.cpp", "conv.o", "cuda01.cu", "cuda01.jl", "cuda01.o", "cuda1.cu", "cuda1.jl", "cuda1.o", "cuda11.cu", "cuda11.jl", "cuda11.o", "cuda12.cu", "cuda12.jl", "cuda12.o", "cuda13.cu", "cuda13.jl", "cuda13.o", "cuda14.jl", "cuda16.cu", "cuda16.jl", "cuda16.o", "cuda17.cu", "cuda17.jl", "cuda17.o", "cuda20.cu", "cuda20.jl", "cuda20.o", "cuda21.cu", "cuda21.jl", "cuda21.o", "cuda22.cu", "cuda22.jl", "cuda22.o", "foo.cpp", "foo.o", "libknet8.so"]
Test Summary: | Pass  Total
gpu           |   20     20


and then export CUDA_VISIBLE_DEVICES=0,1 ,the results are same with  export CUDA_VISIBLE_DEVICES=0

**Comment by THuang001** [comment]
and when i export  export CUDA_VISIBLE_DEVICES=0,1,2 ,running bilstm-tagger.jl, it shows that there is only one gpu working,the others is not working.

**Comment by ilkerkesen** [comment]
@THuang001 did my answer helped you? If it did, could we close this issue?

**Comment by THuang001** [comment]
Thank you again for helping me to solving the problems !
