### ISSUE TITLE
Knet cannot check the gpu memory if it is full during the initialization

### ISSUE THREAD

**Issue by ozanarkancan** [denizyuret/Knet.jl#36]
If a gpu is full, Knet produces a memory error while checking the memory of that gpu. If there is an available gpu, it starts without any problem.

WARNING: cudart.cudaMemGetInfo error 2
INFO: Knet using GPU 0

**Comment by denizyuret** [comment]
I am using the nvml library now, which is the one used by nvidia-smi.  Can you test with the latest master?

**Comment by ozanarkancan** [comment]
It seems working. I'm closing the issue.
