### ISSUE TITLE
 How can I fix :"Cannot find libknet8, please rerun Pkg.build("Knet")."?

### ISSUE THREAD

**Issue by gasharper** [denizyuret/Knet.jl#362]
I can use Knet just with cpu, however, conv4 with cpu is too slow. While building Knet on windows 10 I got an error "Cannot find libknet8, please rerun Pkg.build("Knet")." I have Knet v1.1.0, Julia 1.0.0, CUDA 9.0, cudnn 7.0.5 and VS2012 installed. Do i need to install something else? 

here are outputs when building knet:
Error: Error building `Knet`, showing the last 100 of log:
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt\math_functions.h(5319) : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt\math_functions.h(6229) : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt\math_functions.h(7104) : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt\math_functions.h(7914) : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt/device_functions.h : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt/device_functions.h(776) : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt/device_functions.h(1636) : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt\device_double_functions.h : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\sm_20_intrinsics.h : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\sm_20_intrinsics.h(925) : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt\math_functions.h : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt\math_functions.h(838) : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt\math_functions.h(1772) : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt\math_functions.h(2628) : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt\math_functions.h(3477) : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt\math_functions.h(4417) : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt\math_functions.h(5319) : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt\math_functions.h(6229) : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt\math_functions.h(7104) : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt\math_functions.h(7914) : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt/device_functions.h : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt/device_functions.h(776) : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt/device_functions.h(1636) : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt\device_double_functions.h : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\sm_20_intrinsics.h : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\sm_20_intrinsics.h(925) : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ cuda17.cu
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt\math_functions.h : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt\math_functions.h(838) : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt\math_functions.h(1772) : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt\math_functions.h(2628) : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt\math_functions.h(3477) : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt\math_functions.h(4417) : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt\math_functions.h(5319) : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt\math_functions.h(6229) : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt\math_functions.h(7104) : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt\math_functions.h(7914) : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt\math_functions.h : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt\math_functions.h(838) : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt\math_functions.h(1772) : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt\math_functions.h(2628) : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt\math_functions.h(3477) : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt\math_functions.h(4417) : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt\math_functions.h(5319) : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt\math_functions.h(6229) : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt\math_functions.h(7104) : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt\math_functions.h(7914) : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt/device_functions.h : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt/device_functions.h(776) : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt/device_functions.h(1636) : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt\device_double_functions.h : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\sm_20_intrinsics.h : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\sm_20_intrinsics.h(925) : warning C4819: ���ļ�����ڵ�ǰ����ҳ(936)�б�ʾ���ַ��뽫���ļ��Ϊ Unicode ��ʽ�Է�ֹ��ݶ�ʧ
│ cuda20.cu(338): error: identifier "INFINITY" is undefined
│
│ cuda20.cu(417): error: identifier "INFINITY" is undefined
│
│ cuda20.cu(496): error: identifier "INFINITY" is undefined
│
│ cuda20.cu(575): error: identifier "INFINITY" is undefined
│
│ cuda20.cu(1128): error: identifier "INFINITY" is undefined
│
│ cuda20.cu(1207): error: identifier "INFINITY" is undefined
│
│ 6 errors detected in the compilation of "C:/Users/ADMINI~1/AppData/Local/Temp/tmpxft_00001b54_00000000-10_cuda20.cpp1.ii".
│ cuda20.cu
│ [ Info: cuda1.jl
│ [ Info: `'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin\nvcc.exe' -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir 'D:\VS2012\VC\bin\amd64\cl.exe' --compiler-options '/Ox /LD' -c cuda1.cu`
│ [ Info: cuda01.jl
│ [ Info: `'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin\nvcc.exe' -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir 'D:\VS2012\VC\bin\amd64\cl.exe' --compiler-options '/Ox /LD' -c cuda01.cu`
│ [ Info: cuda11.jl
│ [ Info: `'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin\nvcc.exe' -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir 'D:\VS2012\VC\bin\amd64\cl.exe' --compiler-options '/Ox /LD' -c cuda11.cu`
│ [ Info: cuda12.jl
│ [ Info: `'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin\nvcc.exe' -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir 'D:\VS2012\VC\bin\amd64\cl.exe' --compiler-options '/Ox /LD' -c cuda12.cu`
│ [ Info: cuda13.jl
│ [ Info: `'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin\nvcc.exe' -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir 'D:\VS2012\VC\bin\amd64\cl.exe' --compiler-options '/Ox /LD' -c cuda13.cu`
│ [ Info: cuda16.jl
│ [ Info: `'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin\nvcc.exe' -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir 'D:\VS2012\VC\bin\amd64\cl.exe' --compiler-options '/Ox /LD' -c cuda16.cu`
│ [ Info: cuda17.jl
│ [ Info: `'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin\nvcc.exe' -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir 'D:\VS2012\VC\bin\amd64\cl.exe' --compiler-options '/Ox /LD' -c cuda17.cu`
│ [ Info: cuda20.jl
│ [ Info: `'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin\nvcc.exe' -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir 'D:\VS2012\VC\bin\amd64\cl.exe' --compiler-options '/Ox /LD' -c cuda20.cu`
│ ERROR: LoadError: failed process: Process(`'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin\nvcc.exe' -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-bindir 'D:\VS2012\VC\bin\amd64\cl.exe' --compiler-options '/Ox /LD' -c cuda20.cu`, ProcessExited(1)) [1]
│ Stacktrace:
│  [1] error(::String, ::Base.Process, ::String, ::Int64, ::String) at .\error.jl:42
│  [2] pipeline_error at .\process.jl:695 [inlined]
│  [3] #run#505(::Bool, ::Function, ::Cmd) at .\process.jl:653
│  [4] run at .\process.jl:651 [inlined]
│  [5] macro expansion at .\logging.jl:307 [inlined]
│  [6] inforun(::Cmd) at C:\Users\Administrator\.julia\packages\Knet\hxjeS\deps\build.jl:9
│  [7] macro expansion at .\logging.jl:310 [inlined]
│  [8] build_nvcc() at C:\Users\Administrator\.julia\packages\Knet\hxjeS\deps\build.jl:92
│  [9] build() at C:\Users\Administrator\.julia\packages\Knet\hxjeS\deps\build.jl:136
│  [10] top-level scope at none:0
│  [11] include at .\boot.jl:317 [inlined]
│  [12] include_relative(::Module, ::String) at .\loading.jl:1038
│  [13] include(::Module, ::String) at .\sysimg.jl:29
│  [14] include(::String) at .\client.jl:388
│  [15] top-level scope at none:0
│ in expression starting at C:\Users\Administrator\.julia\packages\Knet\hxjeS\deps\build.jl:147
│
│ Full log at C:\Users\Administrator\.julia\packages\Knet\hxjeS\deps\build.log
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Pkg\src\Operations.jl:1068

here are outputs when I use KnetArray to calculate:
ERROR: Cannot find libknet8, please rerun Pkg.build("Knet").

here are outputs when I run the command "test Knet":
(v1.0) pkg> test Knet
   Testing Knet
 Resolving package versions...
    Status `C:\Users\ADMINI~1\AppData\Local\Temp\jl_685B.tmp\Manifest.toml`
  [6710c13c] AutoGrad v1.1.0
  [9e28174c] BinDeps v0.8.10
  [b99e7846] BinaryProvider v0.5.0
  [3895d2a7] CUDAapi v0.5.2
  [944b1d66] CodecZlib v0.5.0
  [34da2185] Compat v1.1.0
  [864edb3b] DataStructures v0.13.0
  [5789e2e9] FileIO v1.0.1
  [033835bb] JLD2 v0.1.2
  [1902f260] Knet v1.1.0
  [bac558e1] OrderedCollections v1.0.1
  [276daf66] SpecialFunctions v0.7.1
  [3bb67fe8] TranscodingStreams v0.8.1
  [30578b45] URIParser v0.4.0
  [2a0f44e3] Base64  [`D:\Julia-1.0.0\bin\..\share\julia\stdlib\v1.0\Base64`]
  [ade2ca70] Dates  [`D:\Julia-1.0.0\bin\..\share\julia\stdlib\v1.0\Dates`]
  [8bb1440f] DelimitedFiles  [`D:\Julia-1.0.0\bin\..\share\julia\stdlib\v1.0\DelimitedFiles`]
  [8ba89e20] Distributed  [`D:\Julia-1.0.0\bin\..\share\julia\stdlib\v1.0\Distributed`]
  [b77e0a4c] InteractiveUtils  [`D:\Julia-1.0.0\bin\..\share\julia\stdlib\v1.0\InteractiveUtils`]
  [76f85450] LibGit2  [`D:\Julia-1.0.0\bin\..\share\julia\stdlib\v1.0\LibGit2`]
  [8f399da3] Libdl  [`D:\Julia-1.0.0\bin\..\share\julia\stdlib\v1.0\Libdl`]
  [37e2e46d] LinearAlgebra  [`D:\Julia-1.0.0\bin\..\share\julia\stdlib\v1.0\LinearAlgebra`]
  [56ddb016] Logging  [`D:\Julia-1.0.0\bin\..\share\julia\stdlib\v1.0\Logging`]
  [d6f4376e] Markdown  [`D:\Julia-1.0.0\bin\..\share\julia\stdlib\v1.0\Markdown`]
  [a63ad114] Mmap  [`D:\Julia-1.0.0\bin\..\share\julia\stdlib\v1.0\Mmap`]
  [44cfe95a] Pkg  [`D:\Julia-1.0.0\bin\..\share\julia\stdlib\v1.0\Pkg`]
  [de0858da] Printf  [`D:\Julia-1.0.0\bin\..\share\julia\stdlib\v1.0\Printf`]
  [3fa0cd96] REPL  [`D:\Julia-1.0.0\bin\..\share\julia\stdlib\v1.0\REPL`]
  [9a3f8284] Random  [`D:\Julia-1.0.0\bin\..\share\julia\stdlib\v1.0\Random`]
  [ea8e919c] SHA  [`D:\Julia-1.0.0\bin\..\share\julia\stdlib\v1.0\SHA`]
  [9e88b42a] Serialization  [`D:\Julia-1.0.0\bin\..\share\julia\stdlib\v1.0\Serialization`]
  [1a1011a3] SharedArrays  [`D:\Julia-1.0.0\bin\..\share\julia\stdlib\v1.0\SharedArrays`]
  [6462fe0b] Sockets  [`D:\Julia-1.0.0\bin\..\share\julia\stdlib\v1.0\Sockets`]
  [2f01184e] SparseArrays  [`D:\Julia-1.0.0\bin\..\share\julia\stdlib\v1.0\SparseArrays`]
  [10745b16] Statistics  [`D:\Julia-1.0.0\bin\..\share\julia\stdlib\v1.0\Statistics`]
  [8dfed614] Test  [`D:\Julia-1.0.0\bin\..\share\julia\stdlib\v1.0\Test`]
  [cf7118a7] UUIDs  [`D:\Julia-1.0.0\bin\..\share\julia\stdlib\v1.0\UUIDs`]
  [4ec0a83e] Unicode  [`D:\Julia-1.0.0\bin\..\share\julia\stdlib\v1.0\Unicode`]
Test Summary: | Pass  Total
kptr          |    1      1
  9.952273 seconds (16.19 M allocations: 815.057 MiB, 6.06% gc time)
Knet.gpuCount() = 1
Knet.gpu() = 0
Knet.tk = ["C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v9.0"]
Knet.libknet8 = ""
Knet.cudartfound = true
Knet.cudaRuntimeVersion = 9000
Knet.cudaDriverVersion = 9010
Knet.cudaGetDeviceCount() = 1
Knet.cudaGetDevice() = 0
Knet.cudaMemGetInfo() = (1760352665, 2147483648)
Knet.cudaDeviceSynchronize() = nothing
Knet.nvmlfound = true
Knet.nvmlDriverVersion = "390.77"
Knet.nvmlVersion = "9.390.77"
Knet.nvmlDeviceGetMemoryInfo() = (2147483648, 2076385280, 71098368)
Knet.cublashandle() = Ptr{Nothing} @0x000000002b580080
Knet.cublasVersion = 9000
Knet.cudnnhandle() = Ptr{Nothing} @0x000000002e971b20
Knet.cudnnVersion = 7005
Knet.dir() = "C:\\Users\\Administrator\\.julia\\packages\\Knet\\hxjeS"
readdir(Knet.dir("deps")) = [".deprecated", ".gitignore", "build.jl", "build.log", "conv.cpp", "cuda01.cu", "cuda01.jl", "cuda01.obj", "cuda1.cu", "cuda1.jl", "cuda1.obj", "cuda11.cu", "cuda11.jl", "cuda11.obj", "cuda12.cu", "cuda12.jl", "cuda12.obj", "cuda13.cu", "cuda13.jl", "cuda13.obj", "cuda14.jl", "cuda16.cu", "cuda16.jl", "cuda16.obj", "cuda17.cu", "cuda17.jl", "cuda17.obj", "cuda20.cu", "cuda20.jl", "cuda21.jl", "cuda22.jl", "foo.cpp", "Makefile", "README.windows"]
gpu: Test Failed at C:\Users\Administrator\.julia\packages\Knet\hxjeS\test\gpu.jl:39
  Expression: !(isempty(Knet.libknet8))
Stacktrace:
 [1] macro expansion at .\show.jl:555 [inlined]
 [2] macro expansion at C:\Users\Administrator\.julia\packages\Knet\hxjeS\test\gpu.jl:13 [inlined]
 [3] macro expansion at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Test\src\Test.jl:1083 [inlined]
 [4] top-level scope at C:\Users\Administrator\.julia\packages\Knet\hxjeS\test\gpu.jl:5
Test Summary: | Pass  Fail  Total
gpu           |   19     1     20
ERROR: LoadError: LoadError: Some tests did not pass: 19 passed, 1 failed, 0 errored, 0 broken.
in expression starting at C:\Users\Administrator\.julia\packages\Knet\hxjeS\test\gpu.jl:3
in expression starting at C:\Users\Administrator\.julia\packages\Knet\hxjeS\test\runtests.jl:4
ERROR: Package Knet errored during testing

**Comment by gasharper** [comment]
I have no idea about it. I want to figure out what causes the error, but I can not fix the problem about "INFINITY". I try to use CUDA8.0, however, it did not work. Is Visual Studio 2012 cause the problem?

**Comment by denizyuret** [comment]
I tested with the latest Visual Studio (with C++ tools added) and the latest CUDA and it worked (you don't need CUDA if you won't use a GPU).
