### ISSUE TITLE
Trying to run examples

### ISSUE THREAD

**Issue by scrcro** [denizyuret/Knet.jl#364]
Hello 
I am trying to run the example "rnnlm.ipynb" using CPU. I keep getting the following error. Is there a way o avoid this? I cannot use gpu as my machine does not have one.
`ERROR: MethodError: no method matching rnnforw(::AutoGrad.Result{RNN}, ::AutoGrad.Result{Array{Float32,3}}, ::AutoGrad.Result{Array{Float32,2}})`

I have changed the code to use normal arrays instead of KnetArray and also set `usegpu=false` in the `rnninit` function.

Thank you

**Comment by scrcro** [comment]
Any insight on this one? Is there anything I am doing wrong here?

**Comment by denizyuret** [comment]
Hi, unfortunately the cpu implementation does not yet support all options (e.g. batchSizes in this example). I recommend looking at the examples under tutorial using the new interface which should work both on the cpu and the gpu.  However keep in mind that the cpu implementation is very slow.

**Comment by denizyuret** [comment]
You can also get free GPU from Colab to run the Knet tutorial: see https://github.com/denizyuret/Knet.jl/blob/master/tutorial/README.md

**Comment by scrcro** [comment]
Thank you for the response. I will try the new examples.

**Comment by scrcro** [comment]
Thank you, the new interface is much better and easier to understand.
