### ISSUE TITLE
Feature request for KnetArray: argmax and getindex(::KnetArray{T,3}, ::Colon, ::Array{CartesianIndex})

### ISSUE THREAD

**Issue by ngphuoc** [denizyuret/Knet.jl#368]
This will enable fast sampling and array access in discrete distributions-based method (text generation, etc.):

```julia
id = argmax(logits .- log.(-log.(rand!(similar(logits)) .+ ϵ) .+ ϵ), dims=1)
μ[:,id]
```

**Comment by ngphuoc** [comment]
With your recent support for conversion to and from CuArrays, can we use it for KnetArray unsupported getindex?

**Comment by denizyuret** [comment]
Yes, it needs to be tested.

**Comment by denizyuret** [comment]
CuArrays fallbacks fix getindex in https://github.com/denizyuret/Knet.jl/commit/85c4125fa64f6407b2f4a78e4c8655083f059af1, please test.

**Comment by denizyuret** [comment]
https://github.com/denizyuret/Knet.jl/commit/bc72cd2dff3aabe4834fd4b559203d173a9d2b7e adds support for argmax,argmin,findmax,findmin.
