### ISSUE TITLE
KnetArray general reductions

### ISSUE THREAD

**Issue by denizyuret** [denizyuret/Knet.jl#37]
KnetArray currently supports scalar and vector reductions only.  e.g. for a 4-D array A, sum(A) works, sum(A, (1,3,4)) works, but sum(A, 3) or sum(A, (1,3)) does not yet work.  The second argument in sum specifies the dimensions over which summation takes place, the remaining dimensions give the size of the output.  We need to figure out how to implement general reductions efficiently.  The existing implementations are in cuda20.jl (for scalar reductions) and cuda21.jl (for vector reductions).

**Comment by ngphuoc** [comment]
Could you provide a temporarily implementation or some hints in the meanwhile? That would be very helpful for model exploration. Otherwise it's very slow to run the whole model on CPU.

**Comment by denizyuret** [comment]
As a temporary workaround we can override the sum function so that when an
unsupported (a::KnetArray, i::index) combination is received it calls
KnetArray(sum(Array(a),i)).

**Comment by mambuDL** [comment]
There will be any improvement here soon? I mean, it would be amazing if reduction supports at least 3 dimensional KNETArrays.

**Comment by denizyuret** [comment]
Currently any number of dimensions is supported as long as the reduction is
to a scalar or a vector (along any dimension) which covers almost all cases
I encountered in neural nets.  Ilker and Enis are working on generalizing
this but it may take a while.

**Comment by denizyuret** [comment]
@enisberk vertical reductions seem a lot more efficient, let's fix this if possible in redesign:
```
using BenchmarkTools
a = KnetArray(rand(Float32,10000,64));
@benchmark logp($a,1)  => 289.876 μs
b = KnetArray(rand(Float32,64,10000));
@benchmark logp($b,2)  => 522.285 μs
```

**Comment by ilkerkesen** [comment]
By the way, I've implemented general reduction kernel successfully. Now let me perform some tests and then discuss about its efficiency (but I guess it's efficient enough for my cases).

**Comment by denizyuret** [comment]
Please add your tests to test/reduction.jl.

**Comment by ilkerkesen** [comment]
OK, I will add them, no problem. However, sum(A,d) works for all N-D arrays as long as d is an integer. If we have a tuple, we can do the following,

- Apply the first reduction, the second and so on (calling the reduction kernel more than once)
- We can embed the other reductions in a kernel (I think I can do it). But, when we go to the higher dimensions, my mind always become confused. Let me think about it and then we discuss.

Though, we still need to optimize block/thread numbers, it's another issue.

**Comment by ilkerkesen** [comment]
I share the timing results for three different kernels. Kernel 1 is the original kernel that you implemented. Kernel 2 is general kernel I implemented, and Kernel 3 is the non-buggy version of Kernel 1.

## sum(A,1)
Size | Kernel 1 | Kernel 2 | Kernel 3
--- | --- | --- | ---
(100,100) | 4.629 μs | 5.062 μs | 4.850 μs
(500,500) | 11.803 μs | 14.111 μs | 14.636 μs
(100,1000) | 12.120 μs | 15.856 μs | 16.407 μs
(1000,100) | 6.407 μs | 7.245 μs | 6.588 μs
(100,60000) | 527.203 μs | 729.050 μs | 762.506 μs
(60000,100) | 166.780 μs | 246.487 μs | 167.080 μs


## sum(A,2)
Size | Kernel 1 | Kernel 2 | Kernel 3
--- | --- | --- | ---
(100,100) | 6.115 μs | 6.577 μs | 6.244 μs
(500,500) | 52.513 μs | 55.516 μs | 55.045 μs
(100,1000) | 24.905 μs | 25.771 μs | 25.243 μs
(1000,100) | 26.636 μs | 32.321 μs | 30.976 μs
(100,60000) | 1.367 ms | 1.388 ms | 1.519 ms
(60000,100) | 1.424 ms | 1.655 ms | 1.648 ms

**Comment by denizyuret** [comment]
How did you measure the timings?

**Comment by ilkerkesen** [comment]
On aitest machine by using BenchmarkTools package. I constructed the table with mean time values. By the way, now we support general reductions fully (like ndims(A) == 4, sum(A,(1,2))) but I leave its speed-ups to another day for now :)

**Comment by denizyuret** [comment]
I commented out the failing tests, picked better random inputs for others, and merged the commit.  After broadcast is complete, we can uncomment the failing tests.  We should also add benchmarks for new reductions under prof/reduction.jl.  I am leaving this open for tests and benchmarks for now.

**Comment by denizyuret** [comment]
@ilkerkesen are there any N-D reductions we are missing?  should we close this?

**Comment by ilkerkesen** [comment]
There shouldn't be any missing reduction operation. We support reduction
for all shapes.
