### ISSUE TITLE
UnderVarError

### ISSUE THREAD

**Issue by lannisite110** [denizyuret/Knet.jl#377]
julia> using Knet

julia> @info("Testjing")
[ Info: Testjing

julia> @info("Testing")
[ Info: Testing

### **julia> @add_arg_table s begin
              ("--seed"; arg_type=Int; default=42)
              ("--nbatch"; arg_type=Int; default=100)
              ("--lr"; arg_type=Float64; default=0.00001)
              ("--epochs"; arg_type=Int; default=5)
              ("--gcheck"; arg_type=Int; default=0)
       end
ERROR: LoadError: UndefVarError: @add_arg_table not defined
in expression starting at REPL[5]:1**

**Comment by Sophylax** [comment]
The `@add_arg_table` macro is provided by the [ArgParse.jl](https://github.com/carlobaldassi/ArgParse.jl) package and not Knet. All the examples that utilize that macro should already be using that package.
