### ISSUE TITLE
PRUNE Implementation in Julia

### ISSUE THREAD

**Issue by aruniyer** [denizyuret/Knet.jl#379]
Hi,
I am trying to implement the network from this paper in Julia [A]. Following the tutorials, I wrote the following (code below) so far (it implements just the proximity loss function from the paper). I am attempting to do direct gradient descent (I am not sure I understand how to use the inbuilt optimizers yet). However, I am struggling to set the train function correctly with autograd. The @diff is giving me the following stack trace. Any pointers in the right direction will be helpful for me to understand what is going on here.

```
Stacktrace:
 [1] setindex!(::Array{Float32,1}, ::AutoGrad.Result{Float32}, ::Int64) at ./array.jl:769
 [2] (::PRUNE)(::Array{Int64,1}, ::Array{Int64,1}) at /run/media/aruniyer/Elements/Software/JuliaProjects/Playground/prune.jl:37
 [3] ProximityLoss(::PRUNE, ::Array{Int64,1}, ::Array{Int64,1}, ::Array{Float64,2}) at /run/media/aruniyer/Elements/Software/JuliaProjects/Playground/prune.jl:42
 [4] (::getfield(Main, Symbol("##3#4")){PRUNE,Array{Int64,1},Array{Int64,1},Array{Float64,2}})() at /home/aruniyer/.julia/packages/AutoGrad/eAmjh/src/core.jl:82
 [5] #differentiate#1(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Function) at /home/aruniyer/.julia/packages/AutoGrad/eAmjh/src/core.jl:54
 [6] differentiate at /home/aruniyer/.julia/packages/AutoGrad/eAmjh/src/core.jl:45 [inlined]
 [7] train!(::PRUNE, ::Array{Int64,1}, ::Array{Int64,1}, ::Array{Float64,2}, ::Float64) at /run/media/aruniyer/Elements/Software/JuliaProjects/Playground/prune.jl:47
 [8] train!(::PRUNE, ::Array{Int64,1}, ::Array{Int64,1}, ::Array{Float64,2}) at /run/media/aruniyer/Elements/Software/JuliaProjects/Playground/prune.jl:45
 [9] top-level scope at none:0ERROR: LoadError: MethodError: Cannot `convert` an object of type AutoGrad.Result{Float32} to an object of type Float32
Closest candidates are:
  convert(::Type{T<:Number}, !Matched::T<:Number) where T<:Number at number.jl:6
  convert(::Type{T<:Number}, !Matched::Number) where T<:Number at number.jl:7
  convert(::Type{T<:Number}, !Matched::Base.TwicePrecision) where T<:Number at twiceprecision.jl:250
  ...
Stacktrace:
 [1] #differentiate#1(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Function) at /home/aruniyer/.julia/packages/AutoGrad/eAmjh/src/core.jl:57
 [2] differentiate at /home/aruniyer/.julia/packages/AutoGrad/eAmjh/src/core.jl:45 [inlined]
 [3] train!(::PRUNE, ::Array{Int64,1}, ::Array{Int64,1}, ::Array{Float64,2}, ::Float64) at /run/media/aruniyer/Elements/Software/JuliaProjects/Playground/prune.jl:47
 [4] train!(::PRUNE, ::Array{Int64,1}, ::Array{Int64,1}, ::Array{Float64,2}) at /run/media/aruniyer/Elements/Software/JuliaProjects/Playground/prune.jl:45
 [5] top-level scope at none:0
in expression starting at /run/media/aruniyer/Elements/Software/JuliaProjects/Playground/prune.jl:71
```
(Code)

```julia
using CSV, Knet, Statistics

function calc_pmi(source, target, nodeCount, in_degrees, out_degrees, alpha=5.0)
    n = length(source);
    PMI_values = zeros(n, 1);
    for i = 1:n
        s, t = source[i], target[i];
        pmi = n / (alpha * out_degrees[s] * in_degrees[t]);
        PMI_values[i] = log(pmi);
    end

    PMI_values[PMI_values .< 0] .= 0;

    return PMI_values;
end

struct Linear; w; b; end;
(model::Linear)(x) = model.w * x .+ model.b;
Linear(inputsize::Int, outputsize::Int) = Linear(param(outputsize, inputsize), param0(outputsize));

struct Proximity; linear1; linear2; end;
(model::Proximity)(x) = relu.(model.linear2(elu.(model.linear1(x))));

struct Embedding; E; end;
(model::Embedding)(x) = model.E[:, x];
Embedding(embedding_size::Int, instances::Int) = Embedding(param(embedding_size, n));

struct PRUNE; e; p; W; end;
function (model::PRUNE)(s, t)
    n = length(s);
    pr = Array{Float32, 1}(undef, n);
    for i = 1:n
        pr[i] = model.p(model.e(s[i]))'*(relu.(model.W))*model.p(model.e(t[i]));
    end
    return pr;
end
PRUNE(embedding_size::Int, instances::Int, hidden_size::Int) = PRUNE(Embedding(embedding_size, n), Proximity(Linear(embedding_size, hidden_size), Linear(hidden_size, hidden_size)), param(hidden_size, hidden_size));
ProximityLoss(model, s, t, pmi) = sum((model(s, t) - pmi).^2)

function train!(model, source, target, pmi, learning_rate=0.01)
    for epoch = 1:10
        println(ProximityLoss(model, source, target, pmi));
        loss = @diff ProximityLoss(model, source, target, pmi);
        # for param in (model.W, model.p.linear2.w, model.p.linear2.b, model.p.linear1.w, model.p.linear1.b, model.e.E)
        #     ∇param = grad(loss, param);
        #     axpy!(-1.0 * learning_rate, ∇param, value(param));
        # end
    end
end

graph = CSV.read("graph.edgelist", header=0, delim=' ');
source = convert(Array{Int64, 1}, graph[:, 1]);
target = convert(Array{Int64, 1}, graph[:, 2]);
n = max(maximum(graph[:,1]), maximum(graph[:,2])) + 1;
embedding_size = 100;
hidden_size = 64;
M = length(source);
out_degrees = zeros(n, 1);
in_degrees = zeros(n, 1);
for i = 1:M
    node_i, node_j = source[i], target[i];
    out_degrees[node_i] += 1;
    in_degrees[node_j] += 1;
end
pmi = calc_pmi(source, target, n, in_degrees, out_degrees);
model = PRUNE(embedding_size, n, hidden_size);
train!(model, source, target, pmi);
```

[A] https://papers.nips.cc/paper/7110-prune-preserving-proximity-and-global-ranking-for-network-embedding.pdf

**Comment by Sophylax** [comment]
Whenever you are differentiating something, the values you pass to the function and values processed inside are wrapped around with a helper structure by AutoGrad. The resulting structure in most ways will act like the value within it should act, but their types don't match. If you are expecting a value to be exactly a Float32, it will cause problems within the `@diff` macro, since it is something a bit different now. And in such a case Julia will try to convert the value so the types would match, but AutoGrad doesn't provide such a conversion because keeping the extra structure is vital for the differentiation process.

That's why you are getting the exception. Your `(model::PRUNE)(s, t)` function tries to insert a value to a Float32 array, and within the `@diff` macro that value is not precisely a Float32 nor something that can be converted to Float32.

**Comment by aruniyer** [comment]
> Whenever you are differentiating something, the values you pass to the function and values processed inside are wrapped around with a helper structure by AutoGrad. The resulting structure in most ways will act like the value within it should act, but their types don't match. If you are expecting a value to be exactly a Float32, it will cause problems within the `@diff` macro, since it is something a bit different now. And in such a case Julia will try to convert the value so the types would match, but AutoGrad doesn't provide such a conversion because keeping the extra structure is vital for the differentiation process.
> 
> That's why you are getting the exception. Your `(model::PRUNE)(s, t)` function tries to insert a value to a Float32 array, and within the `@diff` macro that value is not precisely a Float32 nor something that can be converted to Float32.

Thanks @Sophylax , this was a useful hint, I was able to fix the issue now :-)

**Comment by Sophylax** [comment]
I did some digging around and as far as I can see the primary problem is no parameter under the `Ranking` sub-model receives a gradient. I believe the softplus function is causing this anomaly, but I have no clue about the precise why. Solving that will probably take a more in-depth analysis. Meanwhile I think if you replace the `(model::Ranking)(x)` function with `log.(1 .+ exp.(model.linear2(elu.(model.linear1(x)))))`, it should behave correctly.

**Comment by aruniyer** [comment]
@Sophylax Thanks so much for looking into this :+1: Yes, with your suggested change, the code is working, this will allow me to proceed with my work. Thanks a lot!
