### ISSUE TITLE
KnetArray general broadcasting

### ISSUE THREAD

**Issue by denizyuret** [denizyuret/Knet.jl#38]
KnetArray supports broadcasting for scalar-array, vector-array (vector can have multiple dims but only a single dim > 1), and array-array if they have the same dimensions.  General array-array broadcasting for multidimensional arrays is complicated and needs to be implemented.  The existing implementations are in cuda12gen.jl.

**Comment by denizyuret** [comment]
Ilker do we have any missing broadcasting ops?  Does everything work in 10, 20 dimensions?

**Comment by ilkerkesen** [comment]
isapprox fails (I guess this is because of too many accumulated rounding errors) but they work without any error.

**Comment by denizyuret** [comment]
how bad does it fail?  can we get it to pass by modifying atol and rtol options to isapprox?

**Comment by denizyuret** [comment]
@ilkerkesen are we missing any broadcasting ops?  should we close this?

**Comment by ilkerkesen** [comment]
We can close this issue, too.
