### ISSUE TITLE
update problem

### ISSUE THREAD

**Issue by lannisite110** [denizyuret/Knet.jl#380]
I want to use compile function and vgg-verydeep-16.mat to initialize vgg_model. while there is a error compile not defined 
> 
using MAT, Knet
file=matread("vgg-verydeep-16.mat")
global vgg=compile(:vgg_model;weights=file)
> 
` LoadError: UndefVarError: compile not defined`

**Comment by denizyuret** [comment]
There is no compile function. Please look at Knet/examples/vgg
