### ISSUE TITLE
ask for question

### ISSUE THREAD

**Issue by lannisite110** [denizyuret/Knet.jl#381]
> 
 In the following code, i want to using compile function to initialize vgg_model with vgg-verydeep-16.mat data. And vgg_model is a model i realized. I want to find a similar function compared with compile. Do you know that?
>

`
file = matread("vgg-verydeep-16.mat")
global vgg = compile(:vgg_model; weights=file)
`

**Comment by denizyuret** [comment]
There is no such function, please read the documentation and tutorial.
