### ISSUE TITLE
what's the meaning

### ISSUE THREAD

**Issue by lannisite110** [denizyuret/Knet.jl#383]
tofunc(op) = eval(Meta.parse(string(op, "x")))
forw(x,op) = tofunc(op)(x)
forw(x,op,w) = tofunc(op)(x,w)

**Comment by OsmanMutlu** [comment]
In the first line, tofunc is a function that takes an argument op which is another function's name whose type is string, then returns that function. For example;
```julia
asdx(x) = x ^ 2 # A function that returns input's square.
op1 = "asd"
tofunc(op) = eval(Meta.parse(string(op, "x")))
forw(x,op) = tofunc(op)(x) # In this case this equals to asdx(x)
print(forw(3,op1))
```

**Comment by denizyuret** [comment]
Please use the knet-users or julia mailing lists to get programming help.
