### ISSUE TITLE
Documentation on RNNs are not online

### ISSUE THREAD

**Issue by ahmetumutdurmus** [denizyuret/Knet.jl#387]
Hello, 

Are the RNN functions (namely: ```Knet.rnninit```, ```Knet.rnnforw```, ```Knet.rnnparam```, ```Knet.rnnparams```) deprecated? Currently the docs of the particular section is empty: 
[http://denizyuret.github.io/Knet.jl/latest/reference.html#Recurrent-neural-networks-1](url)
Or is it just me that I can't locate the relevant docs for them.?

**Comment by denizyuret** [comment]
Please use the RNN object, other functions will be deprecated.

**Comment by ahmetumutdurmus** [comment]
Thanks for your response.
