### ISSUE TITLE
update!

### ISSUE THREAD

**Issue by lannisite110** [denizyuret/Knet.jl#399]
`julia> Adagrad(;lr=0.1, gclip=0, eps=1e-6)
Adagrad(0.1, 0.0, 1.0e-6, nothing)
julia> update!(w,dw,p::Adagrad)
ERROR: UndefVarError: p not defined
Stacktrace:
 [1] top-level scope at none:0

julia> update!(w,dw,SGD(lr=.1))
ERROR: MethodError: no method matching length(::SGD)
Closest candidates are:
  length(::Core.SimpleVector) at essentials.jl:571
  length(::Base.MethodList) at reflection.jl:728
  length(::Core.MethodTable) at reflection.jl:802
  ...
Stacktrace:
 [1] update!(::Array{Array{Float32,N} where N,1}, ::Array{Any,1}, ::SGD) at /home/users/xdlan/.julia/packages/Knet/rKugL/src/update.jl:437
 [2] top-level scope at none:0
`

**Comment by ozanarkancan** [comment]
Hi,

In the first error, p is an argument of the update! function. You should feed a previously created variable.

In the second, length of w, dw and, p must be equal. There must be an optimizer object for each weight. Please, read the documentation of both julia and Knet carefully.
