### ISSUE TITLE
Feature request: group convolutions

### ISSUE THREAD

**Issue by skariel** [denizyuret/Knet.jl#407]
as explained, for e.g., [here](https://towardsdatascience.com/types-of-convolutions-in-deep-learning-717013397f4d). These are more lightweight than the regular convolutions, and are appropriate for some use-cases, for e.g. [this](https://arxiv.org/abs/1704.04861). They are available in tensorflow ad Pytorch

**Comment by denizyuret** [comment]
Does CuDNN support them? What library does Tensorflow and Pytorch borrow this from?

**Comment by skariel** [comment]
I changed the name to "grouped convolutions", these are a generalization and allow to trivially build depth-wise convolutions. The functionality is that the channels are divided into groups and are multiplied all-vs-all only withing their group

**Comment by skariel** [comment]
@denizyuret Grouped convolutions are implemented in `libcudnn` see the definition of [`cudnnSetConvolutionGroupCount`](https://docs.nvidia.com/deeplearning/sdk/cudnn-developer-guide/index.html#cudnnSetConvolutionGroupCount). Should be simple to add, I'll try this myself later today. Of course, a version for CPU has to be added as well....

**Comment by rened** [comment]
@skariel Did you have any success? I can add the CPU version.

**Comment by skariel** [comment]
the significance of this feature: MobileNets, EfficientNet, and basically all SOTA networks on Imagenet use grouped convolutions

**Comment by ngphuoc** [comment]
Related work done in Flux, NNlib, CuArrays: https://github.com/JuliaGPU/CuArrays.jl/pull/523

This is a nice reading with illustrations:

https://towardsdatascience.com/a-comprehensive-introduction-to-different-types-of-convolutions-in-deep-learning-669281e58215

**Comment by denizyuret** [comment]
This will be in the next release of Knet for KnetArrays, you can test with pkg"add Knet#bea8d4b8". CuArrays support is needed I don't think anybody is working on this now.
