### ISSUE TITLE
gradcheck is missing for modular interface

### ISSUE THREAD

**Issue by ekinakyurek** [denizyuret/Knet.jl#409]

**Comment by ekinakyurek** [comment]
I would like to have a `@gradcheck` macro to check gradients of `Param`s in the computation
```Julia
@gradcheck Model(x,y,z...)
@gracheck loss(M::Model,x,y,z...) 
```

**Comment by denizyuret** [comment]
Take a look at the new gcheck function in AutoGrad. Checkout latest master and do `using AutoGrad: gcheck`. You should then be able to do `gcheck(loss, model, x, y)` where all args are scanned for Params. I could probably implement a macro version that takes an arbitrary expression, but then we can't specify keyword arguments like `verbose`, `rtol`, `nsample` etc. Is there a way for a macro to have keyword args?

**Comment by ekinakyurek** [comment]
it is working and I also added @gcheck that support keyword arguments.
denizyuret/AutoGrad.jl#104
