### ISSUE TITLE
Cannot find cudnn bug

### ISSUE THREAD

**Issue by xiaodaigh** [denizyuret/Knet.jl#424]
I got 

* Nvdia RTX 2080 graphics card
* runinng **Windows 10 Pro**
* Julia 1.0.3
* Knet 1.1.2

I have followed the [Windows readme](https://github.com/denizyuret/Knet.jl/blob/master/deps/README.windows) to install all the CORRECT versions of software but when I run

```julia
using Knet; include(Knet.dir("test/gpu.jl"))
```
I get

> Knet.gpuCount() = 1
> Knet.gpu() = 0
> Knet.tk = ["C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.0"]
> Knet.libknet8 = "C:\\Users\\RTX2080\\.julia\\packages\\Knet\\pfgZS\\deps\\libknet8"
> Knet.cudartfound = true
> Knet.cudaRuntimeVersion = 10000
> Knet.cudaDriverVersion = 10000
> Knet.cudaGetDeviceCount() = 1
> Knet.cudaGetDevice() = 0
> Knet.cudaMemGetInfo() = (7003242496, 8589934592)
> Knet.cudaDeviceSynchronize() = nothing
> Knet.nvmlfound = false
> Knet.cublashandle() = Ptr{Nothing} @0x000000004ddb58b0
> Knet.cublasVersion = 10000
> gpu: Error During Test at C:\Users\RTX2080\.julia\packages\Knet\pfgZS\test\gpu.jl:3
>   Got exception outside of a @test
>   Cannot find cudnn
>   Stacktrace:
>    [1] error(::String) at .\error.jl:33
>    [2] cudnnCreate() at C:\Users\RTX2080\.julia\packages\Knet\pfgZS\src\gpu.jl:237
>    [3] cudnnhandle(::Int64) at C:\Users\RTX2080\.julia\packages\Knet\pfgZS\src\gpu.jl:187
>    [4] cudnnhandle() at C:\Users\RTX2080\.julia\packages\Knet\pfgZS\src\gpu.jl:181
>    [5] macro expansion at .\show.jl:555 [inlined]
>    [6] macro expansion at C:\Users\RTX2080\.julia\packages\Knet\pfgZS\test\gpu.jl:28 [inlined]
>    [7] macro expansion at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Test\src\Test.jl:1083 [inlined]
>    [8] top-level scope at C:\Users\RTX2080\.julia\packages\Knet\pfgZS\test\gpu.jl:5
>    [9] include at .\boot.jl:317 [inlined]
>    [10] include_relative(::Module, ::String) at .\loading.jl:1044
>    [11] include(::Module, ::String) at .\sysimg.jl:29
>    [12] include(::String) at .\client.jl:392
>    [13] top-level scope at none:0
>    [14] eval(::Module, ::Any) at .\boot.jl:319
>    [15] eval_user_input(::Any, ::REPL.REPLBackend) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\REPL\src\REPL.jl:85
>    [16] macro expansion at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\REPL\src\REPL.jl:117 [inlined]
>    [17] (::getfield(REPL, Symbol("##28#29")){REPL.REPLBackend})() at .\task.jl:259
> Test Summary: | Error  Total
> gpu           |     1      1
> ERROR: LoadError: Some tests did not pass: 0 passed, 0 failed, 1 errored, 0 broken.
> in expression starting at C:\Users\RTX2080\.julia\packages\Knet\pfgZS\test\gpu.jl:3

and when I run 

```julia
 p=Cint[0]; ccall(("cudaRuntimeGetVersion","libcudart"),UInt32,(Ptr{Cint},),p); p[1]
```
I get 

> ERROR: error compiling top-level scope: could not load library "libcudart"
> The specified module could not be found.

What seems to be the problem? ``CuArrays.jl`` works fine.

**Comment by denizyuret** [comment]
Can CUDAapi see your cudnn?

**Comment by denizyuret** [comment]
Take a look at
https://github.com/denizyuret/Knet.jl/blob/24dea54f7ecb3c6bbb9604f8b59e6b32d59b8455/src/gpu.jl#L236

I use find_cuda_library

**Comment by xiaodaigh** [comment]
Ok, so `find_cuda_library("cudnn")` returns `nothing`, so it didn't find it?

**Comment by denizyuret** [comment]
Correct, please follow up with CUDAapi.jl

**Comment by xiaodaigh** [comment]
Now all tests pass. I think I didn't install cudnn and I didn't realise I had to install it manually see my pr #427

**Comment by xiaodaigh** [comment]
Install cuDnn from https://developer.nvidia.com/cudnn to make things work

**Comment by MicPie** [comment]
I also was not sure how to solve my "cannot find cudnn" error on Ubuntu because PyTorch was running without problems.

However, I also needed to install cudnn like outlined here: https://docs.nvidia.com/deeplearning/sdk/cudnn-install/index.html#ubuntu-network-installation

Check your system status with:
```
using CUDAapi; tk=find_toolkit()
find_cuda_library("cudnn",tk)
```

After the cudnn installation with the rebuilt Knet you can check out the GPU test:
```
using Knet; include(Knet.dir("test/gpu.jl"))
```
or the more extensive tests:
```
using Pkg; Pkg.build("Knet")
using Pkg; Pkg.test("Knet")
```
(The infos from the tests are from point 4 from: https://github.com/denizyuret/Knet.jl/blob/master/docs/src/install.md#installation )

However, some conv tests didn't passed on my system while running the extensive tests but the QuickStart notebook was working without problems:
https://github.com/denizyuret/Knet.jl/blob/master/tutorial/15.quickstart.ipynb

I hope this can be useful for others! :-)
