### ISSUE TITLE
Saving Types using Knet bugged

### ISSUE THREAD

**Issue by denglerchr** [denizyuret/Knet.jl#435]
I found that when saving and loading Types using Knet, they appear to be the same, but have different behavior. As an example, one can try running this
```julia
using Knet

mytype = Array{Float32}

# Working fine
mytype(zeros(3))

# Load and save
Knet.save("mytype.jld2", "mytype", mytype)
mytype = Knet.load("mytype.jld2", "mytype")

# Looks the same
println(mytype)

# but is different (error message)
mytype(zeros(3))
```
Replacing Knet by FileIO does not produce the error message, so I guess the bug is somehow related to Knet. Tested using Knet v1.2.0 using Julia 1.0.3 and 1.1.0 on Windows.
Best regards,
Christian Dengler

**Comment by OsmanMutlu** [comment]
Hey,

This was fixed by #433 , are you sure that you are running on master? Be sure to delete any pre-compiled version of Knet before the update to master.

Regards

**Comment by denizyuret** [comment]
I confirm this is fixed in latest master.

**Comment by denglerchr** [comment]
Hello again.
Maybe I'm doing something wrong, for me it doesn't work :( 
Yes, its Knet 1.2.0 (should be master right?) and I ran Pkg.update() and rebuild Knet with Pkg.build("Knet"). Am I missing something?
I'll try on a different machine just to be sure and report later.
<img width="912" alt="errormessage" src="https://user-images.githubusercontent.com/15248169/52991610-fa64ba00-343f-11e9-8c3c-e389601e8780.PNG">

**Comment by ekinakyurek** [comment]
1.2.0 doesn’t mean you are on master branch’s latest commit. If you want to check-out a package to its master branch, you add them as:

 ] add Knet#master

**Comment by denizyuret** [comment]
I just pushed a 1.2.1 release. Do a Pkg.update() and try.

**Comment by denglerchr** [comment]
Hello again, it works with 1.2.1 :) Thank you so much!
