### ISSUE TITLE
Knet.randn! gives error: ccall: could not find function cudaGetErrorString

### ISSUE THREAD

**Issue by ngphuoc** [denizyuret/Knet.jl#448]
I am having the following error with Knet.randn! (both in `Knet` and `Knet#master`). My codes otherwise work fine. Not sure if it is due to my `]up` command, but downgrading CUDAapi to v0.6.0 does not help:

```julia
julia> Knet.randn!(KnetArray(rand(3)))
ERROR: ccall: could not find function cudaGetErrorString in library /opt/cuda/lib64/libcurand.so
Stacktrace:
 [1] macro expansion at /home/ngphuoc/.julia/packages/Knet/05UDD/src/gpu.jl:24 [inlined]
 [2] randn!(::KnetArray{Float64,1}, ::Int64, ::Int64) at /home/ngphuoc/.julia/packages/Knet/05UDD/src/random.jl:15 (repeats 2 times)
 [3] top-level scope at none:0
``` 
Update:
A fresh julia install on another Ubuntu with cuda 9.0 gives the same error. So it is definitely due to my package update command. 

The `Knet.rand!(KnetArray(rand(3)))` works fine

**Comment by ngphuoc** [comment]
Update all packages again and it works now.

**Comment by ngphuoc** [comment]
Sorry, still not work. I mistakenly used Knet.rand! and thought it was Knet.randn!

**Comment by denizyuret** [comment]
Confluence of two things caused this:
* Apparently curandGenerateNormal call does not like arrays with an odd number of elements.
* The error message was searched in libcurand instead of libcuda.
As a quick workaround use arrays with even length (ugh).
I will get this fixed soon.

**Comment by denizyuret** [comment]
Should be fixed in latest master. Please check.

**Comment by ngphuoc** [comment]
It's working now! Many thanks.
