### ISSUE TITLE
SpecialFunctions loggamma update

### ISSUE THREAD

**Issue by denizyuret** [denizyuret/Knet.jl#486]
Apparently julia 1.1.1 does not update to SpecialFunctions 0.8.0 where the lgamma->loggamma transition took place. Try to make Knet work with both.

**Comment by ianshmean** [comment]
This is true of master too. I just had the following error on an`update`d v1.4 (20 day old master)
```
ERROR: LoadError: LoadError: "loggamma" is not defined in module Knet
```

**Comment by denizyuret** [comment]
SpecialFunctions 0.8.x deprecated lgamma, so I replaced it with loggamma.
Did you try Pkg.update() and what is your SpecialFunctions version?  On
certain setups it seems Pkg.update() leaves SpecialFunctions at 0.7.x for
some reason I do not understand and cannot replicate...

**Comment by ianshmean** [comment]
I didn’t have SpecialFunctions or Knet installed in my main env, and `Pkg.update()` in both the main env, and the package that I’m dev-ing (that has Knet as a del) didn’t fix it. But adding SpecialFunctions to my man env did force it to update to 0.7.0

Hope that helps!

**Comment by Martijn-R** [comment]
I get the same error when `test`ing Knet v1.2.5#master:

`ERROR: LoadError: LoadError: "loggamma" is not defined in module Knet`

I am on Julia v1.1.   SpecialFunctions is v0.7.2 and passes `test`, but will not update to v0.8.  

Any help is appreciated!

**Comment by denizyuret** [comment]
I opened https://github.com/JuliaMath/SpecialFunctions.jl/issues/182 because I don't understand why some people cannot update to SpecialFunctions 0.8. In the meantime I suggest going back to Knet 1.2.4 or waiting for 1.2.6 which I will make compatible with both SpecialFunctions 0.7 and 0.8.

**Comment by ianshmean** [comment]
I hadn’t checked the Knet Project.toml before but just noticed that there isn’t a compat bound for SpecialFunctions. That’s most likely the issue, right?

**Comment by denizyuret** [comment]
That's right, but shouldn't Pkg.update() bring it up to 0.8 anyway?

**Comment by ianshmean** [comment]
That only happens if SpecialFunctions is installed by the user in the main environment (which it wasn’t for me). Deps that aren’t in the main env aren’t updated unless there are compat bounds enforced in parent Project.toml’s

**Comment by denizyuret** [comment]
I did not know that, thanks. In any case I am going to support both
versions in the next release so that should fix the issue.

**Comment by ederekGitHub** [comment]
Thanks denizuret, in my case was dependency with Distributions and Bridge for SpecialFunctions stopping the update to 0.8.0. Posted a workaround and successful resolution in: https://github.com/JuliaMath/SpecialFunctions.jl/issues/182.

**Comment by ianshmean** [comment]
@denizyuret I've checked my statement above and it appears to be wrong. Please ignore.. I'm trying to figure out what happened with this issue
