### ISSUE TITLE
Is Knet.jl running on Win 10 with GPU support?

### ISSUE THREAD

**Issue by apeano** [denizyuret/Knet.jl#50]
Hello,
this may not be an actual issue, however I am a quite puzzled because I read between the lines that Knet is not running with the GPU support on Win 10 (it has been tested with GPU support only on linux/osx), however I don't find any explicit claim about this. Am I right?

Is Knet.jl running on Win 10 with GPU support? If yes, where can I find some tips to follow?

Thanks,

**Comment by denizyuret** [comment]
We have not tried testing everything on windows, but if you try and find an
issue we'd be glad to help.

**Comment by apeano** [comment]
I guess the problem is here, in build.jl under Windows.
It tries to build the library as it was under Linux. Then it returns the warning.

`try success(`nvcc --version`)
    cd("../src") do
        run(`make libknet8.so`)        <<<<<<<<<<<< ISSUE!! UNIX-LIKE CODE!!
    end
catch
    warn("CUDA not installed, GPU support will not be available.")
end`

**Comment by AStupidBear** [comment]
@apeano I guess rename "libknet8.so" to "libknet8.dll" will be OK.

**Comment by amellnik** [comment]
Would the maintainers be open to switching over to CMake for the build system?  I think this would be a key enabler for Windows support.

**Comment by AStupidBear** [comment]
The problem is that the maintainers don't have a GPU installed on Windows.

**Comment by denizyuret** [comment]
@berkay-onder created a windows image to test this on Amazon:
Location: Frankfurt
AMI Name: Knet-Windows

**Comment by ilkerkesen** [comment]
Maybe running Julia/Knet on [WSL](https://msdn.microsoft.com/en-us/commandline/wsl/about) can be an alternative workaround.

**Comment by amellnik** [comment]
If anyone missed it on the developer slack, I have a small bounty for getting either `Knet` or `TensorFlow.jl` working on windows.  It looks like they recently allowed WSL to be installed without enrolling in the developer program (which is blocked in a lot of enterprise environments) but I don't know how that approach would work in general.

**Comment by imeano** [comment]
I have a softly related question. Is Knet.jl running on any Windows without GPU support?

I'm just starting to learn, and would like to be able to run simple cases and examples that don't require that much computational power. Have been trying (and failling) to get it to work on my windows setup

**Comment by denizyuret** [comment]
The only external requirement is the shared library libknet8 which gets
compiled and linked.  If it doesn't, convolution operations won't work, but
you should be able to run e.g. mlp examples.  What doesn't work for you?

**Comment by imeano** [comment]
I had done both Pkg.test("Knet") and Pkg.checkout("Knet") and both presented errors.

I just tried again, test still presents errors, but checkout was fine. I guess I'll try to go on with the tutorial, then. See what happens. 

Thanks

**Comment by denizyuret** [comment]
Latest master supports windows machines.
