### ISSUE TITLE
memory usage printings

### ISSUE THREAD

**Issue by ekinakyurek** [denizyuret/Knet.jl#523]
Below code converts byte number to human readable format. It is from TimerOutputs.jl repository.

@denizyuret Could you add this functionality (human readable gpu info) to gpumem(), gpufreemem() functions.  We can add keyword argument to these functions to not break existing codes.

```julia
using Printf
function prettymemory(b)
    if b < 1000
        value, units = b, "B"
    elseif b < 1000^2
        value, units = b / 1024, "KiB"
    elseif b < 1000^3
        value, units = b / 1024^2, "MiB"
    else
        value, units = b / 1024^3, "GiB"
    end

    if round(value) >= 100
        str = string(@sprintf("%.0f", value), units)
    elseif round(value * 10) >= 100
        str = string(@sprintf("%.1f", value), units)
    elseif value >= 0
        str = string(@sprintf("%.2f", value), units)
    else
        str = "-"
    end
    return lpad(str, 7, " ")
end
```

**Comment by denizyuret** [comment]
Since we switched to the CuArrays allocator by default, these functions do
not print the correct usage. Try CuArrays.usage[] and other similar
reporting features of CuArrays.
