### ISSUE TITLE
julia1.3.0/knet132 build conf.jl gradcheck error

### ISSUE THREAD

**Issue by obviousnic** [denizyuret/Knet.jl#528]
Getting this error,
```
cpuconv: Error During Test at /root/.julia/packages/Knet/LjPts/test/conv.jl:62
 Unexpected Pass
 Expression: gradcheck(pool, ax; kw=[(:padding, 1)])
 Got correct result, please change to @test if no longer broken.

cpuconv: Error During Test at /root/.julia/packages/Knet/LjPts/test/conv.jl:67
 Unexpected Pass
 Expression: gradcheck(pool, ax; kw=[(:padding, (1, 1))])
 Got correct result, please change to @test if no longer broken.
```

Strange I think it was not giving this error a week ago, and I do not see what has changed.

I edited lines 62+67 to change to @test as suggested, and it moves past this error. I hope this is ok and does not break it

**Comment by denizyuret** [comment]
Thank you. We were using NNLib for cpu convolution and these were broken, they must have fixed things. I will modify the test file as you suggest.
