### ISSUE TITLE
Knet build error

### ISSUE THREAD

**Issue by fatihtalu** [denizyuret/Knet.jl#531]
julia> **Pkg.add("Knet")**
  Updating registry at `C:\Users\Administrator\.julia\registries\General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
  Updating `C:\Users\Administrator\.julia\environments\v1.3\Project.toml`
 [no changes]
  Updating `C:\Users\Administrator\.julia\environments\v1.3\Manifest.toml`
 [no changes]

julia> **Pkg.build()**
  Building NNlib ───────────→ `C:\Users\Administrator\.julia\packages\NNlib\udnN
A\deps\build.log`
  Building CodecZlib ───────→ `C:\Users\Administrator\.julia\packages\CodecZlib\
5t9zO\deps\build.log`
  Building SpecialFunctions → `C:\Users\Administrator\.julia\packages\SpecialFun
ctions\ne2iw\deps\build.log`
  Building Knet ────────────→ `C:\Users\Administrator\.julia\packages\Knet\LjPts
\deps\build.log`
┌ Error: Error building `Knet`:
│ nvcc fatal   : Cannot find compiler 'cl.exe' in PATH
│ [ Info: `'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin\nvcc.exe
' -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-options '/Ox /LD' -
c cuda1.cu`
│ ERROR: LoadError: failed process: Process(`'C:\Program Files\NVIDIA GPU Comput
ing Toolkit\CUDA\v9.0\bin\nvcc.exe' -O3 --use_fast_math -Wno-deprecated-gpu-targ
ets --compiler-options '/Ox /LD' -c cuda1.cu`, ProcessExited(1)) [1]
│
│ Stacktrace:
│  [1] pipeline_error at .\process.jl:525 [inlined]
│  [2] #run#565(::Bool, ::typeof(run), ::Cmd) at .\process.jl:440
│  [3] run at .\process.jl:438 [inlined]
│  [4] inforun(::Cmd) at C:\Users\Administrator\.julia\packages\Knet\LjPts\deps\
build.jl:9
│  [5] build_nvcc() at C:\Users\Administrator\.julia\packages\Knet\LjPts\deps\bu
ild.jl:75
│  [6] build() at C:\Users\Administrator\.julia\packages\Knet\LjPts\deps\build.j
l:87
│  [7] top-level scope at C:\Users\Administrator\.julia\packages\Knet\LjPts\deps
\build.jl:93
│  [8] include at .\boot.jl:328 [inlined]
│  [9] include_relative(::Module, ::String) at .\loading.jl:1105
│  [10] include(::Module, ::String) at .\Base.jl:31
│  [11] include(::String) at .\client.jl:424
│  [12] top-level scope at none:5
│ in expression starting at C:\Users\Administrator\.julia\packages\Knet\LjPts\de
ps\build.jl:93
└ @ Pkg.Operations D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib
\v1.3\Pkg\src\backwards_compatible_isolation.jl:649
false

julia>

**Comment by denizyuret** [comment]
It looks like there is a problem with nvcc installation. Maybe you don't
have visual c++ installed?

**Comment by drozzy** [comment]
I also have an issue:
https://github.com/jonathan-laurent/AlphaZero.jl/issues/22#issuecomment-706556386

**Comment by denizyuret** [comment]
Knet does not have a build step, so I need more details to understand what is wrong. What version of Knet are you trying to install? Please try using the latest version.
