### ISSUE TITLE
KnetArray error : expected UnionAll, got typeof(Knet.CuArray)

### ISSUE THREAD

**Issue by johncwok** [denizyuret/Knet.jl#540]
When trying to define a KnetArray like : 
```Julia
a = KnetArray{Float64,2}(undef,(2,3))
```
the following error gets thrown at me.
```Julia
ERROR: TypeError: in Type{...} expression, expected UnionAll, got typeof(Knet.CuArray)
Stacktrace:
 [1] KnetPtrCu(::Int64) at C:\Users\cnelias\.julia\packages\Knet\LjPts\src\cuarray.jl:90
 [2] Knet.KnetPtr(::Int64) at C:\Users\cnelias\.julia\packages\Knet\LjPts\src\kptr.jl:102
 [3] KnetArray{Float64,2}(::UndefInitializer, ::Tuple{Int64,Int64}) at C:\Users\cnelias\.julia\packages\Knet\LjPts\src\karray.jl:76
 [4] top-level scope at none:0
```
Same if I this, or any other variant that I can think of :
```Julia
a = ones(5)
b = convert( KnetArray{Float64,1}, a )
``` 
I googled a bit but couldn't bring my understanding of this any further. 
Do you know what it means ?

**Comment by andreasdominik** [comment]
Same for us!
We are on a Nvidia DGX with installed: 
- cuda 10.2
- cudnn 7.6
- julia 1.3
- cudaapi 3.1
- knet 1.2.7

With cudnn 7.5 and cuda 10.1 everything worked fine but with the warning "cuArrays only support cudnn 7.6 or higher" - which was the reason for us to upgrade.
We highly appreciate any help or work-around!
Cordially
Andreas

**Comment by andreasdominik** [comment]
I have to apologize - at least for us, it was a mistake setting up GPU access in the docker container.
When done correctly, Knet works as expected!

@johncwok : our installation produced the error because no GPUs were available; not Knet to blame! You may want to double check if it is something similar on your side. Our part of the issue can be closed.

@denizyuret : sorry again for the trouble!

Cordially 
Andreas

**Comment by denizyuret** [comment]
No problems.

I would recommend the following tests:
- Make sure the julia cuda packages pass their tests: CUDAapi, CuArrays
etc. if not troubleshoot those packages.
- Follow the instructions on
https://denizyuret.github.io/Knet.jl/latest/install/#Installation-1 --
there are some troubleshooting notes.
- If all else fails open an issue with the output of
`include(Knet.dir("test/gpu.jl"))`.

**Comment by denizyuret** [comment]
Added some better error messages in latest master...
