### ISSUE TITLE
test with CUDAapi v4.0

### ISSUE THREAD

**Issue by denizyuret** [denizyuret/Knet.jl#543]

**Comment by denizyuret** [comment]
Fixed in latest master.

**Comment by iuliancioarca** [comment]
Sorry for reviving this, but now matter what I tried I cannot make Knet use the GPU in the latest release with CUDAapi 4.0 on Windows.
```
using CUDAapi
tk=find_toolkit()
1-element Array{String,1}:
 "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1"
find_cuda_library("cudart",tk)
```
returns nothing.
If I try instead:
```
find_cuda_library("cudart64_101",tk)
"C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1\\bin\\cudart64_101.DLL"
```
it does find my dlls.
Please also see the discussion here:
https://github.com/JuliaGPU/CUDAapi.jl/issues/110

Any advice is welcome! 
Thank you!

**Comment by denizyuret** [comment]
@maleadt any advice? Is `find_cuda_library("cudart",tk)` not the right thing to use?

**Comment by maleadt** [comment]
No, there's an example in the tests that show how to find `cudart`:

```
julia> using CUDAapi

julia> dirs = find_toolkit()
1-element Array{String,1}:
 "/opt/cuda"

julia> ptxas = find_cuda_binary("ptxas", dirs)
"/opt/cuda/bin/ptxas"

julia> ver = parse_toolkit_version(ptxas)
v"10.2.89"

julia> find_cuda_library("cudart", dirs, [ver])
"/opt/cuda/lib/libcudart.so"
```

The reason for this change is that Windows encodes the version in file names, differently for some libraries, so it's hard to guess for CUDAapi (and I wanted to get rid of some version databases for easy of maintenance).

**Comment by denizyuret** [comment]
@iuliancioarca can you please test this and submit a pull request if it works?

**Comment by iuliancioarca** [comment]
Thank you for the quick reply! Not at the computer at the moment but I see `gpu.jl` from `Knet ` calling `find_cuda_library(lib,tk)` in a few places. I will try to track all of them, update these calls and see if I can use `Knet` with GPU again.

**Comment by iuliancioarca** [comment]
So I did some modifications in `gpu.jl`:
```
const tk = find_toolkit()
const ver = parse_toolkit_version(find_cuda_binary("ptxas", tk))
```
and:
```
path = (lib=="knet8" ? libknet8 : find_cuda_library(lib,tk,[ver]))
...
path = find_cuda_library("cudnn",tk,[ver])
```
Now  Knet sees `cudart`, but still cannot find `cudnn`.

Digging inside `CUDAapi` I ended up here:(https://github.com/JuliaGPU/CUDAapi.jl/blob/fcf574076ddfba6f5689c96ec4d00bc6ec51ccff/src/discovery.jl#L46)
This appends to `"cudnn"` the version returned by the code in your example above. In my case:
```
 "cudnn64"
 "cudnn"
 "cudnn64_10"
 "cudnn64_102"
```
But the `cudnn` library name is actually `cudnn64_7.dll`.
@maleadt, I saw in v2.0 it relied on some hardcoded versions.
How to solve this?

**Comment by maleadt** [comment]
> path = find_cuda_library("cudnn",tk,[ver])

That's wrong, you're requesting CUDNN with the CUDA version, but as you noticed the current soversion is 7. So you need to pas `[v"7"]`, indicating you support the CUDNN v7 APIs.

**Comment by iuliancioarca** [comment]
I understand. Is it safe to hardcode this into Knet code? I see CUDNN stayed at version 7.xx since ~2017.

**Comment by maleadt** [comment]
> Is it safe to hardcode this into Knet code? I see CUDNN stayed at version 7.xx since ~2017.

I think so, CuArrays does the same. If they ever move to v8, I'd assume there would be some breaking changes that need adjustment anyhow.

**Comment by iuliancioarca** [comment]
Thank you, @maleadt !
@denizyuret , I will submit a PR with `gpu.jl` modifications.
