### ISSUE TITLE
Bug: Loading a model made using the Chain struct fails

### ISSUE THREAD

**Issue by madprogramer** [denizyuret/Knet.jl#557]
Loading a model into another file I receive the following error:

``` julia
Knet.@load "EmRec256.jld2"
println(model)

(model(reshape(SAMPLES,26,1,598)))
```

```bash
> JLD2.ReconstructedTypes.var"##Main.Chain#253"((RNNRELU(input=26,hidden=256,bidirectional),
JLD2.ReconstructedTypes.var"##Main.Dense#254"(P(Array{Float32,2}(2,512)), P(Array{Float32,1}(2)), identity)))
> ERROR: LoadError: MethodError: objects of type JLD2.ReconstructedTypes.var"##Main.Chain#253" are not callable
```

I don't think it's just about JLD2, Serialization doesn't seem to work either:
```julia
model = deserialize("EmRec160")
```
```bash
> ERROR: LoadError: UndefVarError: Chain not defined
```

For the record I added the chain definition to my file:
```julia
# chain of layers
struct Chain
    layers
    Chain(layers...) = new(layers)
end
(c::Chain)(x) = (for l in c.layers; x = l(x); end; x)
(c::Chain)(x,y) = nll(c(x),y)
```

**Comment by denizyuret** [comment]
This typically happens if the same struct is not defined before
loading/saving the file.

**Comment by madprogramer** [comment]
What exactly do you mean by "defined before loading/saving the file" ?

I know this is probably very simple to do in a notebook environment etc. but I need to have it inside of a static file (i.e. I won't be able to modify this while it's running). 

I was able to find a solution but it's very ugly. I had to define Chain and Struct **outside** of the module. In practice I suppose I'll have to do this for my main module instead:

#### EmRec.jl
```julia

#Outside of Module Definition 
using Knet: Knet, AutoGrad, gpu, param, param0, mat, RNN, relu, Data, adam, progress, nll, zeroone

# chain of layers
struct Chain
    layers
    Chain(layers...) = new(layers)
end
(c::Chain)(x) = (for l in c.layers; x = l(x); end; x)
(c::Chain)(x,y) = nll(c(x),y)


# Redefine dense layer 
struct Dense; w; b; f; end
Dense(i::Int,o::Int,f=identity) = Dense(param(o,i), param0(o), f)
(d::Dense)(x) = d.f.(d.w * mat(x,dims=1) .+ d.b)

#Inside of Module Definition
module EmRec

# ... 

function detect(fileLoc)

	SAMPLES = (preprocess(fileLoc))
	println(size(SAMPLES))

	Knet.@load "EmRec256.jld2"
	println(model)

	(model(reshape(SAMPLES,26,1,598)))
	#reshape(Xs[1],26,1,328)

	#TAG
	tag(model, 26, SAMPLES)
end

end
```

**Comment by iuliancioarca** [comment]
I hope this helps a little:
https://discourse.julialang.org/t/how-to-deserialize-inside-a-module/37020/3

**Comment by denizyuret** [comment]
From @iuliancioarca's example I think two things must hold:

1. The type should be defined within the same module before saving and
before loading.
2. At the point of the load, the type name should be visible in the current
context (i.e. either the load happens inside the module, or if it happens
inside Main, the type has been imported).

does this help?

**Comment by madprogramer** [comment]
> 2. At the point of the load, the type name should be visible in the current
context (i.e. either the load happens inside the module, or if it happens
inside Main, the type has been imported).

I think that's it. I'd like to contribute to the Wiki myself when this semester ends, so I might add this in as a tip for anyone who is working with a multi-module project.
