### ISSUE TITLE
NLL loss

### ISSUE THREAD

**Issue by jbaron** [denizyuret/Knet.jl#563]
I noticed if I use `nll` as loss function I get dispatched to the wrong nll method. These are the types of parameters I pass to `nll`:

`nll(::AutoGrad.Result{Knet.KnetArray{Float32,2}}, ::Knet.KnetArray{UInt8,1}; dims::Int64, average::Bool, o::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /home/peter/.julia/packages/Knet/bTNMd/src/loss.jl:353
`

And I end up in (which of course will throw an exception):

`function nll(model, data; dims=1, average=true, o...)`

and not in the expected:

`function nll(y,a::AbstractArray{<:Integer}; dims=1, average=true)`

Should `nll` not be used as a loss function?

**Comment by denizyuret** [comment]
`nll` is a loss function with a number of methods for different uses. `@doc nll` lists them but maybe it can be better formatted. `nll(scores,answers)` takes individual arrays and calculates negative log likelihood for a single batch. `nll(model,data)` calculates the aggregate loss of a model over a whole dataset. Please see the tutorial examples.

**Comment by jbaron** [comment]
I guess I was not that clear, sorry for that. 

I understand the different versions of nll. But I just noticed that when I use a KnetArray for the answers, I get in the wrong method. This is because nll(model, data) is more generic and nll(scores, answers) expect a AbstractArray not a KnetArray for answers. So the multiple dispatch send me to nll(model, data) if I use a KnetArray for the second argument.

Was hoping this could be fixed?

**Comment by denizyuret** [comment]
No problem: answers are expected to be integer CPU arrays. They are used for indexing into the scores array, so there is no advantage in keeping them on the GPU (which is what KnetArrays do) -- in fact it will slow things down because we index into individual elements of the answers array. So I can think of a couple of ways out:
* Accept KnetArray answers and let the user suffer a slow down (not my favorite).
* Accept KnetArray answers but give a warning/error.
* Accept KnetArray answers and implement an efficient cuda kernel (this may not happen soon given my schedule).
* Update the documentation to make the type requirements more explicit with one of the above.

What is your preference?

**Comment by jbaron** [comment]
I thought for now about adding a small wrapper (and perhaps later implement a good kernel)?

`nll(y, a::KnetArray; dims=1, average=true) =  nll(y, Array(a); dims=dims, average=average)`

It can be added it in Photon.jl or in Knet, what you think is best ? 

P.S The root cause is that my framework moves both input and labels automatically to the GPU if the model also resides there, and of course here that goes wrong.

**Comment by denizyuret** [comment]
I tried to fix the doc and add the following in the latest master:
```
function nll(y,a::KnetArray{<:Integer}; dims=1, average=true)
    @warn "nll(scores, answers::KnetArray{<:Integer} is inefficient, nll(scores, answers::Array{<:Integer}) is better." maxlog=1
    nll(y, Array(a); dims=dims, average=average)
end
```

If you are ok with the warning, this should be sufficient. If you don't want the users to get the warning, just override my method in Photon.jl with the same signature defining `Knet.nll(y,a::KnetArray{<:Integer}; dims=1, average=true)`.

**Comment by jbaron** [comment]
I'm fine with the warning, and then will overwrite it with in Photon.jl:

`nll(y, a::KnetArray{<:Integer}; dims=1, average=true) = nll(y, Array(a); dims=dims, average=average)`

Of course there is a small performance degradation to bring it back from GPU to CPU, but until we have a kernel, this is more than fine. Thanks and I close the issue.
