### ISSUE TITLE
Is it possible to provide Knet GPU support in BinaryBuilder

### ISSUE THREAD

**Issue by ViralBShah** [denizyuret/Knet.jl#566]
I was just wondering with the recent BinaryBuilder inclusion of GPU libraries, if Knet can ship what it needs on the GPU in BinaryBuilder.

**Comment by denizyuret** [comment]
I discussed this with Tim Besard. The cuda stack installs all necessary gpu
libraries but not the nvcc compiler. Knet still has some manually compiled
cuda kernels that need nvcc at setup. Some of these are probably
responsible for Knet’s speed advantage. Until I have time to port them to
Julia I need nvcc. A good project would be to integrate these into CuArrays
so we can get rid of KnetArrays and the nvcc requirement for good.

**Comment by ViralBShah** [comment]
@maleadt fyi.

It wasn't clear to me how to build Knet's GPU support. It seems that `Pkg.build("Knet")` is not sufficient. And the instructions felt a bit too involved.

**Comment by ViralBShah** [comment]
Seems reasonable to package the CUDA kernels that Knet uses into a BinaryBuilder package.

**Comment by ViralBShah** [comment]
We now have Torch.jl which is supported through BinaryBuilder. I don't know if that gives the right high performance kernels for you to leverage.

**Comment by ViralBShah** [comment]
cc @dhairyagandhi86

**Comment by denizyuret** [comment]
TODO: test Torch.jl and/or Julia kernels to replace libknet8.so.

**Comment by denizyuret** [comment]
The latest version downloads libknet8.so as an artifact and does not need the CUDA toolkit for installation.
