### ISSUE TITLE
Feature request: Depthwise and groupwise convolution

### ISSUE THREAD

**Issue by ngphuoc** [denizyuret/Knet.jl#574]
These convolutions are increasingly popular in state of the art methods. 

Related work done in Flux, NNlib, CuArrays: https://github.com/JuliaGPU/CuArrays.jl/pull/523

**Comment by denizyuret** [comment]
Related to #407. Any recommended reading describing these operations?

**Comment by ngphuoc** [comment]
I missed that issue. Thanks. Will post there
