### ISSUE TITLE
Update the example in the homepage / make it run smoothly for new users

### ISSUE THREAD

**Issue by sylvaticus** [denizyuret/Knet.jl#577]
Hello, totally new to Knet here.

I did try to run the MINST classification example in the [github homepage](https://github.com/denizyuret/Knet.jl) and got the following problems:

- `include(Knet.dir("data","mnist.jl"))` returned the error that package CodecZlib was not installed
- `adam!(LeNet, repeat(dtrn,10))` returned the warning "Warning: repeat(d::Data,n) is deprecated, use IterTools.ncycle instead."
- the same code, without GPU is running for several minutes without any sign of progress. I would suggest that, as this is code to be run by new users, either you add some callback indicating the progress or you choose a less computationally intensive task as first example.

Thank you :-)

   Antonello Lobianco

**Comment by denizyuret** [comment]
Thank you, fixed in latest master.
