### ISSUE TITLE
Make CuArrays work with Knet.load/save.

### ISSUE THREAD

**Issue by denizyuret** [denizyuret/Knet.jl#587]

**Comment by jbaron** [comment]
Perhaps something additional to consider to include if you are going to refactor the load/save functionality (I added this to my own Photon.jl package to make load/save also work on GPU  arrays).

```

"""
Enable saving and loading of models by specialized KnetArray methods for Julia serialization
This will effectively move a GPU weight to the CPU before serializing it and move it back to
the GPU when deserializing.
"""
function Serialization.serialize(s::Serialization.AbstractSerializer, p::Knet.KnetArray)
    Serialization.serialize_type(s, typeof(p))
    Serialization.serialize(s, Array(p))
end

function Serialization.deserialize(s::Serialization.AbstractSerializer, t::Type{<:Knet.KnetArray})
    arr = Serialization.deserialize(s)
    return Knet.KnetArray(arr)
end
```

**Comment by denizyuret** [comment]
This looks great! Is this all you need to have FileIO, JLD, JLD2 etc. work? If so I should just put this into Knet and remove custom load/save. Should also do this for CuArrays if not done already.

**Comment by jbaron** [comment]
I only used serialization directly to a file for my framework, so Serialization.serialize(...). But anything that uses serialization under the hood should work and all of this thanks to the multiple-dispatch ;)

**Comment by denizyuret** [comment]
It turns out CuArrays inherit serialization from GPUArrays, so serialize already works on them. However JLD2 does not seem to use this and I could not get customserialization to work yet: https://github.com/JuliaIO/JLD2.jl/issues/40. 

With direct serialize, one can only save one variable in one file, correct? Or is there a way to save multiple variables like with JLD or JLD2?

**Comment by jbaron** [comment]
Not sure I understand 100% correctly, but you can serialize arbitrary variables to IO and multiple times if you want to. So for example:

```
using Serialization

open("mydata", "w") do io
      serialize(io, [1,2,3])
      serialize(io, "hello")
end

open("mydata", "r") do io
     deserialize(io), deserialize(io)
end

```

**Comment by denizyuret** [comment]
This answers my question, thanks. I added KnetArray serialization and CuArray JLD2 support for the next release.
