### ISSUE TITLE
Knet.randn! not defined in v1.4.0

### ISSUE THREAD

**Issue by ngphuoc** [denizyuret/Knet.jl#598]
`CUDA.randn!(a::KnetArray)::KnetArray` works fine. Does this mean we should use all functions from CUDA for KnetArrays? You will replace KnetArrays by CuArrays eventually anyway.

**Comment by denizyuret** [comment]
There is no CUDA.randn! or Knet.randn! AFAIK, they both import and add methods to Random.randn!

**Comment by ngphuoc** [comment]
I see, thanks
