### ISSUE TITLE
Knet GPU OOM with recent CUDA/Knet updates

### ISSUE THREAD

**Issue by andevellicus** [denizyuret/Knet.jl#602]
With the recent CUDA upgrade to 1.3, I'm running into OOM problems with my models. I can't seem to revert CUDA 1.2.1 with Knet 1.4.

Attached is a MWE.
[train_unet.txt](https://github.com/denizyuret/Knet.jl/files/5109201/train_unet.txt)
[layers.txt](https://github.com/denizyuret/Knet.jl/files/5109203/layers.txt)
[resunet.txt](https://github.com/denizyuret/Knet.jl/files/5109204/resunet.txt)

Layers are just taken from KnetLayers and changed so that Conv3D operations are supported, as well as recent changes to Knet 1.4.

Working:
Knet 1.3.9
CUDA 1.2.1
Julia 1.4

Not working:
Knet 1.4
CUDA 1.3
Julia 1.4

Running on Julia 1.4 b/c of #589, which this MWE reproduces.

**Comment by denizyuret** [comment]
Did the problem improve with the 1.4.1 fixes?

**Comment by andevellicus** [comment]
Well, I closed it since it seemed to be more related to CUDA.jl, and because it was hard to consistently reproduce, especially with all the changes. Haven't really been able to push things with 1.4.1 due to #610

**Comment by denizyuret** [comment]
1.4.1 fixed some memory related issues and it should be able to train 50% larger models/batch sizes. That's why I was curious. I will look at #610.
