### ISSUE TITLE
pooling of matrices of different sizes

### ISSUE THREAD

**Issue by pevnak** [denizyuret/Knet.jl#61]
Hi all,
I am doing research in multiple instance learning and I require two key features:
1) Each sample can be of different size
2) Pooling operator has to be able to deal with samples of different sizes.
I have not find a DL library that would have such features, and therefore I have written everything by myself, which is slow as I do not use GPU. I would like to ask, if your library support this, or how difficult it would be to add the support. 

The paper where I describe the models I am interested is available here:
[Discriminative Models for Multi-instance Problems with Tree Structure](https://www.researchgate.net/publication/309040375_Discriminative_Models_for_Multi-instance_Problems_with_Tree_Structurel).

Thanks for help.
Tomas

**Comment by denizyuret** [comment]
Hi Tomas,

Can I assume you are talking about the same pooling operator that convolutional neural networks use?  In that case Knet has no problems dealing with inputs of different sizes.  You may have difficulty if you try to minibatch instances of different sizes, but that is a different matter.

deniz
