### ISSUE TITLE
Error converting CuArray to KnetArray

### ISSUE THREAD

**Issue by ngphuoc** [denizyuret/Knet.jl#619]
```
julia> KnetArray(CuArray(rand(2)))
ERROR: UndefVarError: Knet not defined
Stacktrace:
 [1] KnetArray(::CuArray{Float64,1}) at /home/ngphuoc/.julia/packages/Knet/8aEsn/src/knetarrays/karray.jl:156
 [2] top-level scope at REPL[50]:1

```

**Comment by andevellicus** [comment]
Assuming that is the entirety of your code, you need to install the Knet package:

```
julia> using Pkg
julia> Pkg.add("Knet")
```

Also, don't need to convert CuArrays -- the following will suffice:

```
KnetArray(rand(2))
```

**Comment by denizyuret** [comment]
Fixed in latest master, please check.

**Comment by ngphuoc** [comment]
It works. Many thanks.

@andevellicus I need the conversion to use functionalities supported in one or another. I am waiting for when Knet completely switches to CuArray.
