### ISSUE TITLE
tutorial/30.lin.ipynb

### ISSUE THREAD

**Issue by ilkarslan** [denizyuret/Knet.jl#621]
When I run the 30.lin file I get the following error for the line `ypred = model(x)`.

MethodError: no method matching *(::Array{Float64,2}, ::KnetArray{Float32,2})
Closest candidates are:
  *(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:538
  *(!Matched::Knet.KnetArrays.Bcasted{Float32}, ::KnetArray{Float32,N} where N) at C:\Users\ilker\.julia\packages\Knet\1uvp7\src\knetarrays\binary.jl:132
  *(::Union{StridedArray{T, 2}, LinearAlgebra.Adjoint{var"#s828",var"#s827"} where var"#s827"<:Union{StridedArray{T, 2}, LinearAlgebra.LowerTriangular{T,S} where S<:AbstractArray{T,2}, LinearAlgebra.UnitLowerTriangular{T,S} where S<:AbstractArray{T,2}, LinearAlgebra.UnitUpperTriangular{T,S} where S<:AbstractArray{T,2}, LinearAlgebra.UpperTriangular{T,S} where S<:AbstractArray{T,2}} where var"#s828", LinearAlgebra.LowerTriangular{T,S} where S<:AbstractArray{T,2}, LinearAlgebra.Transpose{var"#s826",var"#s825"} where var"#s825"<:Union{StridedArray{T, 2}, LinearAlgebra.LowerTriangular{T,S} where S<:AbstractArray{T,2}, LinearAlgebra.UnitLowerTriangular{T,S} where S<:AbstractArray{T,2}, LinearAlgebra.UnitUpperTriangular{T,S} where S<:AbstractArray{T,2}, LinearAlgebra.UpperTriangular{T,S} where S<:AbstractArray{T,2}} where var"#s826", LinearAlgebra.UnitLowerTriangular{T,S} where S<:AbstractArray{T,2}, LinearAlgebra.UnitUpperTriangular{T,S} where S<:AbstractArray{T,2}, LinearAlgebra.UpperTriangular{T,S} where S<:AbstractArray{T,2}} where T, !Matched::LinearAlgebra.Adjoint{var"#s828",var"#s827"} where var"#s827"<:SparseArrays.AbstractSparseMatrixCSC where var"#s828") at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\SparseArrays\src\linalg.jl:147
  ...

Stacktrace:
 [1] (::Linear)(::KnetArray{Float32,2}) at .\In[4]:2
 [2] top-level scope at In[7]:1
 [3] include_string(::Function, ::Module, ::String, ::String) at .\loading.jl:1091

**Comment by denizyuret** [comment]
Fixed in the latest master, you can test with `using Pkg; pkg"add Knet#master"`.
