### ISSUE TITLE
MLDatasets uses MNIST label 0:9 instead of 1:10 as in older Knet

### ISSUE THREAD

**Issue by ngphuoc** [denizyuret/Knet.jl#623]
This affects all examples using MNIST and `nll` loss function, which ignores zero-labels.

**Comment by ngphuoc** [comment]
I think you missed it in mlp.jl and lenet.jl. I haven't checked others but I did
 ack "y[y.==0] = 10"
in the Knet example folder and it shows nothing!
________________________________

**Comment by denizyuret** [comment]
Thank you, good catch.
