### ISSUE TITLE
Error: no method matching sum_outgrads(::Array{Knet.KnetArray{Float32,2},1}, ::Array{Any,1})

### ISSUE THREAD

**Issue by ngphuoc** [denizyuret/Knet.jl#63]
I got the following error
```
ERROR: LoadError: MethodError: no method matching sum_outgrads(::Array{Knet.KnetArray{Float32,2},1}, ::Array{Any,1})
in backward_pass(::AutoGrad.Rec{Array{Array{T,1},1}}, ::AutoGrad.Rec{Float32}, ::Array{AutoGrad.Node,1}) at /home/phuoc/.julia/v0.5/AutoGrad/src/core.jl:214
...
```
when I apply mean over an array
```julia
function predict_multi(w, xs)
  a = []
  for x ∈ xs
    x = predict(w, x)
    push!(a, x)
  end
  mean(a)
end
```
The forward pass is OK. I temporarily fix it by adding this line to AutoGrad/src/core.jl, line 453
```julia
sum_outgrads(a::AbstractArray,b::AbstractArray)=[sum_outgrads(x,y) for (x,y) in zip(a,b)]
```
Is my fix correct? If it is correct, could you insert this line to AutoGrad/src/core.jl, line 453? 

Otherwise, do I have to define a new `@primitive`? Will something like the following work?:
```julia
mymean(a) = sum(a) / length(a)
@primitive mymean(x),dy (dy/length(x)) .* ones(size(x))
```

**Comment by denizyuret** [comment]
The problem was AutoGrad not preserving the type of array.  Your solution would risk being slow if you have isbits arrays. I fixed this in the latest autograd master.  The fix was adding a single 'T' character :)
```
sum_outgrads{T}(a::AbstractArray{T},b::AbstractArray{T})=(if isbits(T); (a+b); else; T[sum_outgrads(x,y) for (x,y) in zip(a,b)]; end)
```
Please reopen if you find this solution does not work.
