### ISSUE TITLE
ERROR: LoadError: ArgumentError: indexed assignment with a single value to many locations is not supported; perhaps use broadcasting `.=` instead?

### ISSUE THREAD

**Issue by serhatsoyer** [denizyuret/Knet.jl#631]
Given the following definitions:

```
a = Array{Int, 4}(undef, 6, 1, 3, 1)
b = Array{Int, 4}(undef, 4, 1, 3, 2)
c = Array{Int, 2}(undef, 2, 2)
A = KnetArray{Int, 4}(undef, 6, 1, 3, 1)
B = KnetArray{Int, 4}(undef, 4, 1, 3, 2)
C = KnetArray{Int, 2}(undef, 2, 2)
```

These lines work properly:

```
a[1 : 4, 1, :, 1] = b[:, 1, :, 1]
A[1 : 4, 1, :, 1] = B[:, 1, :, 1]
c[:, :] = C[:, :]
C[:, :] = c[:, :]
```

However, this line does not:

`a[1 : 4, 1, :, 1] = B[:, 1, :, 1]`

It throws the following error:

> ERROR: LoadError: ArgumentError: indexed assignment with a single value to many locations is not supported; perhaps use broadcasting `.=` instead?

Is this something expected?

**Comment by denizyuret** [comment]
Setting Arrays from KnetArrays is in general not supported. Setting KnetArrays from Arrays is partially supported. Please convert the RHS to the same type as LHS before the assignment.
