### ISSUE TITLE
Julia crashes when I run "using Knet"

### ISSUE THREAD

**Issue by ilkerarslan** [denizyuret/Knet.jl#652]
When I am running the command "using Knet" Julia crashes. It happens in both Julia REPL and also in Julie Jupyter notebook. I tried and it only happens with Knet not with any other package.

**Comment by emirhan422** [comment]
It seems to be working for me:

```
julia> using Knet

julia> using Pkg

julia> Pkg.status("Knet")
Status `C:\Users\PC\.julia\environments\v1.5\Project.toml`
  [1902f260] Knet v1.4.5

julia> Pkg.status("CUDA")
Status `C:\Users\PC\.julia\environments\v1.5\Project.toml`
  [052768ef] CUDA v2.3.0

julia> conv4 # a random access
conv4 (generic function with 5 methods)
```

**Comment by ilkerarslan** [comment]
Still doesn't work for me. I realized that it throws InitError before closing. Probably it is the same issue as Issue #643 so I'm closing this one.
