### ISSUE TITLE
Knet.@save is broken

### ISSUE THREAD

**Issue by ilkerkesen** [denizyuret/Knet.jl#653]
I'm working with latest release. `Knet.save`, `Knet.load`, `Knet.@load` works, but `Knet.@save` is broken. Here's the minimal example to replicate this issue,
```julia
using JLD2
hello = "world"
foo = :bar
@save "example.jld2" hello foo # this works

using Knet
Knet.@save "example2.jld2" hello foo # this used to be working
```
Here's the error backtrace,
```
ERROR: UndefVarError: hello not defined
Stacktrace:
 [1] top-level scope at /kuacc/users/ikesen16/.julia/packages/JLD2/aRhgS/src/loadsave.jl:66
```
I'm continuing with `Knet.save`, its macro is broken. It'd be good to work with the macro, since it is less cluttered.

**Comment by denizyuret** [comment]
Fixed in latest master.
