### ISSUE TITLE
type DataType has no field mutable

### ISSUE THREAD

**Issue by andreasdominik** [denizyuret/Knet.jl#672]
Dear Deniz, 
after new installation of Julia/Knet on a new Computer  AutoGrad gives me a "type DataType has no field mutable".
A brief look-up at AutoGrad.jl tells me, that the issue is due to a design-change in Julia and is fixed in AutoGrad long ago. However it seems, that Knet still imports an old version of AutoGrad by default? 
I double-checked this by installation on another machine -- with the same effect.
Installing the head of AutoGrad.jl (Pkg.add("git@github.com:denizyuret/AutoGrad.jl.git") ) fixes the issue but is not an ideal solution ...
Would you please have a look into it?

**Comment by denizyuret** [comment]
Dear Andreas: Could you let me know your Knet, AutoGrad, and Julia versions?

**Comment by andreasdominik** [comment]
Dear Deniz: please close the issue - Knet is fine!
Mea Culpa! 
the problem was a wrong decency in one of my own packages. Please accept my apologies.
