### ISSUE TITLE
Speed of Knet

### ISSUE THREAD

**Issue by pevnak** [denizyuret/Knet.jl#70]
Hello All,
I would like to ask if anyone experienced with KNet can explain me, what I am doing wrong and why a simple code like this is incredibly slow

```

using StatsBase
using Knet
function predict(w,x)
for i=1:2:length(w)-2
x = max(0, w[i]*x .+ w[i+1])
end
return w[end-1]*x .+ w[end]
end

x=randn(Float32,64,100000)
y=sample(1:2,100000)
loss(w,x,y) = mean(max(0,1-y.*predict(w,x)))

function train(k)
w=[randn(k,size(x,1)),zeros(k),randn(k,k),zeros(k),randn(1,k),0.0]

lossgradient=grad(loss)
prms=Sgd(;lr=0.001)
for i in 1:100
idxs=sample(1:size(x,2),1000);
xx=x[:,idxs];
yy=y[idxs]
dw = lossgradient(w,xx,yy)
update!(w,dw,prms)
println(i," ",loss(w,xx,yy))
end
end

train(25)
```

**Comment by ekyurdakul** [comment]
Your input,output,weights matrices aren't KnetArrays; calculations are being done on the CPU.

**Comment by pevnak** [comment]
That means that whole package is optimized for GPU and slow on CPU?

**Comment by ekyurdakul** [comment]
Yes. GPUs are better at these type of calculations. Although I haven't tested your code, it should run much faster on a GPU.

**Comment by denizyuret** [comment]
On both CPU and GPU, the grad calculation should take roughly 2x time as
the plain loss calculation. The speed of the loss calculation in turn, is
up to your code and the Julia compiler. When you mention slow, what is your
point of comparison?

**Comment by pevnak** [comment]
Hi Dennis,
thanks for the answer. I think that the core issue is that weights of the model is vector of Any, which causes Julia to make ineffective code. I have copied that from example in ReadMe, but it is not something I am quite content. I have tried to change it to tuple, which should give it a rigid definition and julia can better optimize. Though I run into this error:

`
no method matching axpy!(::Float64, ::Tuple{Array{Float64,2},Array{Float64,1},Array{Float64,2},Array{Float64,1},Array{Float64,2},Float64}, ::Tuple{Array{Float64,2},Array{Float64,1},Array{Float64,2},Array{Float64,1},Array{Float64,2},Float64})`

which I think is caused by missing overloaded function. But I was not able to find, where do you overload axpy! for lists of matrices or how to add handling of tuples such that it will work with update!

**Comment by pevnak** [comment]
I have modified the code by replacing the array by tuple (which made the compiler aware of types) and removed the update!, because of the problem mentioned in my previous comment and it flies really nicely.

That said, the update! should be modified to handle tuples, especially if it is encouraged in the documentation to do so.

Tomas

**Comment by ozanarkancan** [comment]
Hi,
You can use a tuple to hold your weights, but update! accepts only one weight array. You should iterate over your weights to update them. Your initial examples works since julia can perform the minus operation on list of arrays (e.g. [rand(4,2), zeros(2)] - 0.1 * [rand(4,2), zeros(2)]). Optimization parameters should also be a list or tuple (if you do not use Sgd). Because, the optimization methods other than Sgd need to store some additional arrays to perform the update rule.

You can check this [example](https://github.com/denizyuret/Knet.jl/blob/master/examples/optimizers.jl) .

**Comment by pevnak** [comment]
Hi,
thanks for the answer. I was thinking about solution like that, but before writing that, I wanted to know if there is some machinery inside that makes this explicit.

Thank you very much for the answer. 
I really appreciate it.

Tomas
