### ISSUE TITLE
Cannot `convert` an object of type Array{Float32,0} to an object of type Float32

### ISSUE THREAD

**Issue by denizyuret** [denizyuret/Knet.jl#74]
[Msg from Davide Nitti](https://groups.google.com/forum/#!topic/knet-users/RlUbjUKe1JA
)

**Comment by denizyuret** [comment]
Ozan, Emre, Davide'nin koduna bir bakar misiniz, en son master ile calisiyor mu, bozuksa nesi bozuk.

**Comment by quaertym** [comment]
Self-contained code: https://gist.github.com/quaertym/087e596e50513f06e35f2faf33291c31

**Comment by denizyuret** [comment]
Fixed in latest AutoGrad master.  Problem was a'*s with array a and scalar s turning into Ac_mul_B. Added support for scalars in Ac_mul_B etc.
