### ISSUE TITLE
Question about loss function

### ISSUE THREAD

**Issue by georgeblck** [denizyuret/Knet.jl#81]
Thank you for this package!

I am wondering about the Euclidean loss function you use in the housing-example:
`loss(w,x,y)=(sumabs2(y-predict(w,x)) / size(x,2))`

Why do you divide by `size(x,2)` and not by 2, as is normally done when using this loss function? 
Thanks in advance for an answer.

**Comment by denizyuret** [comment]
Dividing by size(x,2) gives you the per-instance average loss.  If you did
not do this, the loss numbers would depend on the minibatch or batch size.

**Comment by georgeblck** [comment]
That makes sense. Thanks for the quick answer!
