### ISSUE TITLE
Performance of hyperband.jl

### ISSUE THREAD

**Issue by AStupidBear** [denizyuret/Knet.jl#87]
Previously, I use hyperopt to tune a MLP and can quickly get 98%+ accuracy on the test set . However, hyperband.jl cost me hours to approach 97%+ on the same data set. Have you done benchmarks for hyperopt or spearmint for this? I really doubt the powerfulness of this method.

**Comment by denizyuret** [comment]
I haven't run any benchmarks, just trusted the ones in
https://arxiv.org/abs/1603.06560.  Did you try any of the benchmarks they
tried?

**Comment by AStupidBear** [comment]
No, just feel that hyperband is not efficient enough. Moreover, I notice that in your code
```T = [ getconfig() for i in 1:n ]```, at every  iteration you choose the first third best configurations and restart training them with more epochs from scratch. Will it be better to preserve the best networks?

**Comment by denizyuret** [comment]
Just pushed a new algorithm `goldensection`, which may be faster in certain cases.

**Comment by AStupidBear** [comment]
Cool
