### ISSUE TITLE
array of optimizers

### ISSUE THREAD

**Issue by zahachtah** [denizyuret/Knet.jl#88]
This got a bit confusing post, next (following) comment below is minimal code to illustrate the issue...

I use a MLP according to the softmax.ipynb example as well as the winit function to initialize the wheights. The winit function gives me an array of arrays of Float32's (3 hidden layers)

```julia
8-element Array{Array{Float32,2},1}:
```

I modified a function in another example to make a list of optimizer parameters as:

```julia
function updatePrms(w,optFun)
   map(x->optFun(), w) 
end
```

so that calling `updatePrms(w,Adadelta)` gives me a 

```julia
8-element Array{Knet.Adadelta,1}:
```
array. Calculating a gradient, `g` which has type `8-element Array{Any,1}:` and then calling `update!(w,g,p)`  or `update!(w1[1],g[1],p[1])` however gives an error as:

```julia
MethodError: no method matching length(::Knet.Adadelta)
Closest candidates are:
  length(::SimpleVector) at essentials.jl:168
  length(::Base.MethodList) at reflection.jl:256
  length(::MethodTable) at reflection.jl:322
  ...

 in update!(::Array{Float32,2}, ::Array{Float64,2}, ::Knet.Adadelta) at /Users/raukhur/.julia/v0.5/Knet/src/update.jl:339
 in update!(::Array{Array{Float32,2},1}, ::Array{Any,1}, ::Array{Knet.Adadelta,1}) at /Users/raukhur/.julia/v0.5/Knet/src/update.jl:346
```
How do I have to construct the list of updatePrms to get the right type to use in `update!` ?

Also, tried using
```julia
function updatePrms(w,optFun)
   map(x->optFun(x), w) 
end
```
gives 
```julia
MethodError: Cannot `convert` an object of type Array{Float32,2} to an object of type Knet.Adadelta
```
Its probably something trivial I missed, I am not fluent in julia yet :-/

I did just notice that in the winit function, if I change `map(atype, w)` to just use return `w` as default Float64 `update!(w,g,p)` does work, so its seems to be something about converting from Float32?

**Comment by zahachtah** [comment]
The above may be a bit confusing, here is the relevant code:

```julia
function mlp(w,x; pdrop=(0,0))
    for i=1:2:length(w)-2
        x = relu(w[i]*x .+ w[i+1])
        #x = tanh(w[i]*x .+ w[i+1])
    end
    return w[end-1]*x .+ w[end]
end
        
function winit(h...; std=0.01, x=784, y=10,  # use winit(h1,h2,...,hn) for n hidden layer mlp
    atype=gpu()>=0 ? KnetArray{Float32} : Array{Float32})
    h = [x, h..., y]
    w = Any[]
    for i=1:length(h)-1
        push!(w, std*randn(h[i+1],h[i]))
        push!(w, zeros(h[i+1],1))
    end
    #map(atype, w)
    w
end
        
function updatePrms(w,optFun)
   map(x->optFun(), w) 
end

function diffloss(w,x,y,model)
            sumabs2(y-model(w,x))/size(y,2)
end

diffgrad = grad(diffloss)

w=winit(100,50,25)
g=diffgrad(w,rand(784,100),rand(10,100),mlp)
p=updatePrms(w,Adam)
update!(w,g,p)
```

The above will work. However, when uncommenting `#map(atype, w)` and using 

```julia
function winit(h...; std=0.01, x=784, y=10,  # use winit(h1,h2,...,hn) for n hidden layer mlp
    atype=gpu()>=0 ? KnetArray{Float32} : Array{Float32})
    h = [x, h..., y]
    w = Any[]
    for i=1:length(h)-1
        push!(w, std*randn(h[i+1],h[i]))
        push!(w, zeros(h[i+1],1))
    end
    map(atype, w)
end
```
instead I get:

```julia

```
MethodError: no method matching length(::Knet.Adam)
Closest candidates are:
  length(::SimpleVector) at essentials.jl:168
  length(::Base.MethodList) at reflection.jl:256
  length(::MethodTable) at reflection.jl:322
  ...

 in update!(::Array{Float32,2}, ::Array{Float64,2}, ::Knet.Adam) at /Users/raukhur/.julia/v0.5/Knet/src/update.jl:339
 in update!(::Array{Array{Float32,2},1}, ::Array{Any,1}, ::Array{Knet.Adam,1}) at /Users/raukhur/.julia/v0.5/Knet/src/update.jl:346

**Comment by denizyuret** [comment]
Hi Jon,

In 0.8.1, update! only accepts single numeric arrays not lists of weights.
You will have to iterate over the elements of w,g,p and call update! on
each set of corresponding elements.  In 0.8.2 (which should come out any
day now), your code should work out of the box.  You can try it using the
latest master (Pkg.checkout("Knet")), and let me know if you run into a
problem.

best,
deniz

**Comment by zahachtah** [comment]
Thanks for the quick response! much appreciated!

I did a checkout and get 

```julia 
INFO: Checking out Knet master...
INFO: Pulling Knet latest master...
WARNING: AutoGrad is fixed at 0.0.5+ conflicting with requirement for Knet: [0.0.6,∞)
INFO: No packages to install, update or remove
```

After Pkg.status says I have Knet 0.8.1+ and Autograd 0.0.5+

I tried using update!(w[i],g[i],p[i]) but still same error as above

I really like Knet as it is so transparent in what is does while still very convenient!

**Comment by denizyuret** [comment]
Your weight arrays are Float32 (when you map atype), your data arrays are
Float64 (rand default).  The code assumes you use the same Float type
throughout.  If you use atype=Array{Float64} in winit, or generate data
using rand(Float32, 784, 100), things should work.  Julia is picky about
types, I should add a better error message for this case...

**Comment by zahachtah** [comment]
ouch, I knew julia was and should be picky, but was staring at the parameters array and the weights, forgot the data. Many thanks (again :-) ), it works as intended now

If you ever get to it, an actor-critic reinforcement implementation in Knet would be a nice addition to the examples, or some of the more recent ones from deepmind... !

**Comment by denizyuret** [comment]
I definitely plan spending some time on reinforcement models this year.  Of
course outside contributions always welcome as well :)
