### ISSUE TITLE
Suggestions on optimization methods

### ISSUE THREAD

**Issue by AStupidBear** [denizyuret/Knet.jl#95]
Since most of Knet's examples use Sgd, I'm uncertain about the effectiveness of other methods such as Adam, Adadelta. Could you provide some suggestions on how to choose those methods?

**Comment by denizyuret** [comment]
The documentation for each optimization method refers to the paper it comes from. In practice I find Adam usually works best with the least amount of fiddling.

**Comment by AStupidBear** [comment]
Thanks.
